services:
  backend:
    image: ghcr.io/mprove-io/mprove-lab-backend:$MPROVE_RELEASE_TAG

  blockml:
    image: ghcr.io/mprove-io/mprove-lab-blockml:$MPROVE_RELEASE_TAG

  disk:
    image: ghcr.io/mprove-io/mprove-lab-disk:$MPROVE_RELEASE_TAG

  front:
    image: ghcr.io/mprove-io/mprove-lab-front:$MPROVE_RELEASE_TAG

  dwh-postgres:
    image: ghcr.io/mprove-io/mprove-lab-dwh-postgres:$MPROVE_DWH_POSTGRES_TAG

  dwh-mysql:
    image: ghcr.io/mprove-io/mprove-lab-dwh-mysql:$MPROVE_DWH_MYSQL_TAG

  # dwh-clickhouse:
  #   image: ghcr.io/mprove-io/mprove-lab-dwh-clickhouse:$MPROVE_DWH_CLICKHOUSE_TAG

  mcli:
    image: ghcr.io/mprove-io/mprove-lab-mcli:$MPROVE_RELEASE_TAG

  # integra:
  #   image: ghcr.io/mprove-io/mprove-lab-integra:$MPROVE_RELEASE_TAG
     
