services:
  grist:
    image: ghcr.io/mprove-io/mprove-lab-grist:$MPROVE_RELEASE_TAG

  disk:
    image: ghcr.io/mprove-io/mprove-lab-disk:$MPROVE_RELEASE_TAG

  backend:
    image: ghcr.io/mprove-io/mprove-lab-backend:$MPROVE_RELEASE_TAG

  backend-scheduler:
    image: ghcr.io/mprove-io/mprove-lab-backend:$MPROVE_RELEASE_TAG

  blockml-single:
    image: ghcr.io/mprove-io/mprove-lab-blockml:$MPROVE_RELEASE_TAG

  blockml-main:
    image: ghcr.io/mprove-io/mprove-lab-blockml:$MPROVE_RELEASE_TAG

  blockml-worker:
    image: ghcr.io/mprove-io/mprove-lab-blockml:$MPROVE_RELEASE_TAG

  blockml-main-worker:
    image: ghcr.io/mprove-io/mprove-lab-blockml:$MPROVE_RELEASE_TAG

  front:
    image: ghcr.io/mprove-io/mprove-lab-front:$MPROVE_RELEASE_TAG

  frontnode:
    image: ghcr.io/mprove-io/mprove-lab-frontnode:$MPROVE_RELEASE_TAG

  dwh-postgres:
    image: ghcr.io/mprove-io/mprove-lab-dwh-postgres:$MPROVE_RELEASE_TAG

  dwh-clickhouse:
    image: ghcr.io/mprove-io/mprove-lab-dwh-clickhouse:$MPROVE_RELEASE_TAG

  integra:
    image: ghcr.io/mprove-io/mprove-lab-integra:$MPROVE_RELEASE_TAG

  mcli:
    image: ghcr.io/mprove-io/mprove-lab-mcli:$MPROVE_RELEASE_TAG
     
