ingress:
  host: 10003b5b2bb3d3da14388566acc0f3175e58dcf0d98db0bd2175062f129eee460912bb8eb46c060a5eb89579c5aefd4a4054
  certProdSecretName: 1000d1c3b106c3186e10136931ecc9bcc5ae6bc159dc48d5e6d99d11ac8ce5eb3e6c356e07baf1c2e747c168bf5f2ccb7135
  certStagingSecretName: 10002801bee8e3f5f48117e88271c546f83c54cb28f6eb646e03e504ef03bcab4cd033f695db65948f74f624b55e1513be72
  acmeEmail: 10001b03c0353c37a546ca4b1b4c0dbc9378d46174d70fdc48af5ddc1dd1022e4b30089c14c9c6ddbc5830eb539f18c61bd1
  routeGrafana:
    enabled: 1000d0a7e7afcd4ef4451ca9039dbb755d8805a2fc0aeef5c7a8c56104ba3a02c7cf
    host: 100005dede7d5024412bc32bfec2b54298ff497708032bbbd6268d447b4bce6499f6028cbe10c4574a27a239324788ea6047
    destination: 100007bfd6afd4923dd5f62939c726da32d4b0c2f316c2edafb9c9e719bd992093bfe7e5795f532209b3e3484e5a6962b042e6d3e9a1c6125b3573134c8958aa67837b88fbace08f9720166916846afd7a26
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 10002aff4b01f60933ded3c7ac11faf4ea28457d209c310f3149f5ac6aeec0a0c7f314006ca462292c7406fbf3ff42c77847114d76f4342b44601e49a0990246e0c9
    MYSQL_DATABASE: 1000b7ba8feb88f6f3698b5390f4ba345ab0b6a58341d06a75832e5733465f188368
    MYSQL_USERNAME: 1000bf050fecf83f3fb174aad302d5c7042d8ebccc3076dd6842906ee259155d5a86
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 1000fd361fc5aff89a0078e771288fa05fc091753074ab7af2408e5255aedd766c32
    RABBITMQ_DEFAULT_PASS: 1000cf544c332651266894336af624c4a8754e1c51eb2756d4835c8f03effa28c2356d25ed7ddba0fc6ce74c71dfef62e7cb63a5de03a1babf8784157113d0780197
    RABBITMQ_ERLANG_COOKIE: 1000325e1439d3425c60dc47108896feee5a21ed17094d555174f097516648165a9f829c92b1486d62ec520486c7cf89b867e488192069ac8cb78c71004f0b6888c4
grist:
  secretEnvs:
    GRIST_SANDBOX_FLAVOR: 100032e65fc0a7d731b5b2f8ad1fc7d94587510f81111c5d220f1d20813935cbdac0
    GRIST_SESSION_SECRET: 10002c8ab18e23a298a60ed485153f8ed62c50a88813b9b460f9924fad44ad4cb46f902efaaca0e43cf48760beadd93aac31b2229d78d0c0097af1db80a384e92281
    COOKIE_MAX_AGE: 1000b4738a76f6884c0f4e6852533aef31100e48e090f59701f6a6f5da17da4ba785
dwhPostgres:
  secretEnvs:
    PGDATA: 10007f0dc7b01cb965461b13cccc0f76c071577603af0f723a7967a74b35db4e76020800cf53d2af3da100b38feef90e3a6d
    POSTGRES_PASSWORD: 100052552f098989a2f99cfc4e9b2c40d1a0c0852bb3f06a0cc71b2aaedba9a5137d108b71533dd0a17da264b03b76307b9ffbb8c529731088efc543c98370a735da
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 100056a5703e0bfcd9176577dafe3ff728bd0089fb9cb6a79493b3e9426b4931df08
    CLICKHOUSE_USER: 1000d2b86e4bf788a07acbf49b7e02e7a56ca532e68e782ae148b925339c631fa004
    CLICKHOUSE_PASSWORD: 1000b3db84227f1a12c1b2c01db0d5fc28390203cb7af6cbe3c7b72d90a843930929856a407ce070a99adb9009888bffecce937a74e235a58391eb3e0e011ba741d9
mcli:
  secretEnvs:
    NODE_ENV: 100087064a3f95cdd783d0e04b17a0a67f8ef9e379aa52462588ed1b4b00d13622b1
    MPROVE_CLI_HOST: 1000968eae696f30592daeea735e7c047a4c00c10465d8ed660ac039a25d2ca014b6bac19e64d704582d6d0e0ee1fc7a0135
    MPROVE_CLI_EMAIL: 1000b5a842a26fe54da7b7171f4ca33a3dea6f29bd43c3968570db62d3cfd9631cf67447f6165a72dacfc9208cb399ae5032
    MPROVE_CLI_PASSWORD: 1000ba8813f9915822cebdbff0c8602813f2d11e9adb438bbf6a5e7cbd48182867f9
    MPROVE_CLI_PROJECT_ID: 10008750b6405fe508686a07f470304ac860dff642d025bb5b56b2614c0eae828f3c9410c5483ba718cb3dc90d4bce84f38b
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 1000b9a0bbb8bffe924b245eafcda9164a3673c89e10e37a97dce713157b228f76637d782d299db35373d32e5cf47a1050d02b3b44a7dcb2e13eeaf3760f7243b791
    MPROVE_CLI_TEST_DESTINATION_URL: 10005a50e370ad42fa7312f4cfe7b68da7eaf5a7dbdb3c5cf4bd3415c8ee2cde9b24e15f6735d39bc371b133a654617fee2fa2196d3ec1cf9c95a43a193c72e235a9
    MPROVE_CLI_TEST_REPOS_PATH: 1000f89bef9b1aff0922f2a481b93eed2e88d6f3fa96b9c8b8bc654a24466fdab7cd3dde3d80594f512b183b65d09926e77d
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 1000a776cd66540b923ae2b294119ad0d5845eee374144ea0476a54a88c34e6d5564eb120d14f2f4f20db2412ec7dcb52f23a68d7f41ce806fd9d2fd1f9af75057ee96b7c8e2a80352b78133f54f90238e53
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 10003090c9ec991c509d87db7d018350c0f27fcd69518efb58e8a3037352548491325dd9f1c8b26377143d191a0a076c4631ede8ef7c4faee71f850e0be3aa9aab5e2cf256af05bbb373c929e951a6b40ae7600f77cbd4c536df18857b18c3596e1ef7c8edb4c8be469ff82030cbb7a634b4
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 1000efb45dad6d1d20904e24a571d72c2b3909ea1f0c5e35bf64bdd93cdb75dff11ddf21535bbbff12f406ea2c034377eefa1a2688a570093d07352cadfc806b5c37
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 1000f9d455531cdf0cbb4a4240615ebf7e07525ec60cf18cb17ccb7c77d5d76049c54c4d92ea874487ff4156f0ee3bec3a3e75ad598fb2cbac133484d4d7de1e0f5f
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 1000d7560c5473e3e751daaa2a5896b04d1a6990071e70ef1a3e04d040ce320453ecae63b9b5fc8c192dd9acaef08d4ac9b4bc4021e55244a7efe5fa1f5c0ad24639
disk:
  secretEnvs:
    NODE_ENV: 10006e775f5c11604d2a36bbb26f2af221721226f30e50a64559b3b28b829d520969
    DISK_ENV: 1000ec5b86f6ccffdb6ea4fd1b40551295777c58229383c2cddf0a8036656d507b22
    DISK_ORGANIZATIONS_PATH: 10002f29f87745353066a35592b94b74349e54957458ca1c74290f376622cdf296a0f33ed884bf1c4eb0e21af81612c5ea68
    DISK_RABBIT_PROTOCOL: 1000c0d532a7b6933167bf9e6e29ecc6c30611ad57dd80bb5cac697e263cff7046ba
    DISK_RABBIT_USER: 10001930613fec5829ca378ef30ffeffbd2ec9d89ce91111723e1016e0dae54e9941
    DISK_RABBIT_PASS: 100076795b8d446fe9ebf9defd979d714343d90e86ede832d1a237b7c930c1eb8aa3ce1ba5d6eede8e4b6125e4834e4b175f53d099f8dc029de34892ec2588363556
    DISK_RABBIT_HOST: 1000d80af555886acdacfa6ce8b798abef2382cb8c2034864f6a0078ac81a65dba64
    DISK_RABBIT_PORT: 1000b1f9652e1edb18a1f5ceaaa68cc3dd70359b1ace24e27911c2bb59c238c07858
    DISK_LOG_IS_JSON: 10006a286f327de28ff7673b6adbe23fc20cd71a8c53a249a6a2d3688cff2623d0db
    DISK_LOG_RESPONSE_ERROR: 1000a9915e13596a74a97f968364ad7a4b05bab17aeb7c0348f08dccad2bf3955084
    DISK_LOG_RESPONSE_OK: 10000c33172e54d0e0e6b29a7475a36bbeff60a2775cc6f83d2c0adb20cfda45a639
blockmlCommon:
  secretEnvs:
    NODE_ENV: 10005921a9469a0368c07d59f4b512844d7c9f4bbb120b920d80e5f80a6e2c738e34
    BLOCKML_ENV: 1000bef25e1583f70ad224a9744251266b06bed0f225616a10e3d85a428b536b180e
    BLOCKML_RABBIT_PROTOCOL: 100045a20489fbbb5fa95cf9a2eb490400a7981b60b7a4b6fc941288601a72a604b5
    BLOCKML_RABBIT_USER: 1000721364df869f94294dc1abd2ddcc7c5efbc33450551e9db7a440a63454bea27c
    BLOCKML_RABBIT_PASS: 10008f11226469c8b386047afdae64d9b6960ca55985d3bc994db39c4c46f63c55a21076d42934a01977945ac1d473960d58148bc196b1e19fa307f910ac17133a5a
    BLOCKML_RABBIT_HOST: 100001f209576bf5ba44ba82a3b3ace3569c681caa045d371aa2bb640951a9cc1dc0
    BLOCKML_RABBIT_PORT: 100014dbace1a8acbc6778013407e521e9fc366c4291fbe1c49b348c6b673f34399d
    BLOCKML_LOG_IO: 1000fbb56d1c05fd52ababaafa86603cb091599e39065c44dc62af79348ad2e446a7
    BLOCKML_LOG_FUNC: 10006df288fac758d0c0ff2f6bb40d6f68c55a5d6b1bb0b1e07e6be238c32a7aeacf
    BLOCKML_COPY_LOGS_TO_MODELS: 1000d8796ef13fc7fadce7a04665e5c99fbb74db3dade8368011ac00978b44fbaa7b
    BLOCKML_LOGS_PATH: 1000716d45e8a38bd0e6ffadfa7d0ddd7426d1f7171b01ca11788711e91739fe99a0772c84b0c52d962dde835692ec512b3c
    BLOCKML_IS_SINGLE: 10002cd04240bd688f7186bf51295ee0f56c21cdbc981bad9e6842de7d8db8247383
    BLOCKML_IS_MAIN: 1000da378164a93bd75395b75cc17c5d41467a31da31dc8776732cb14304e0c937fe
    BLOCKML_IS_WORKER: 1000bf0954f0c47518731eaa87018af0dbe53ea37f59d86209a356784bd73861a5fb
    BLOCKML_CONCURRENCY_LIMIT: 100030fe65ac48c4c03fe1ed77341a1b6f713e426f143016045c0fe4b0437ce81a33
    BLOCKML_LOG_IS_JSON: 1000ac499049f0104524e242a816f463b315931557e3e5c82b575b16d4e2f361d654
    BLOCKML_LOG_RESPONSE_ERROR: 100019ef50991dfe753d9320e8924ce80b9e6cadab2dab5235cd9ef46be859755b36
    BLOCKML_LOG_RESPONSE_OK: 1000227ed4ea3d486a54210d2ff75e52455f9dc89b725b73db16a4f430f90fc1cdd7
backendCommon:
  secretEnvs:
    NODE_ENV: 10001276322beac12d320a2fdba8a61b26a5a32947f9ecf7061263d61e9d7c264bfb
    BACKEND_ENV: 1000d53d0c78f32b58316a593ce298373ed66be0e8341ce7dfdc88767cc46343bad6
    BACKEND_MYSQL_DATABASE: 10001ad3429bf0b96c453cd57eb1583bb64a429f30385cdeb0daa0440ee60799f878
    BACKEND_MYSQL_PASSWORD: 1000f5e894df2f5ce4c71e5d6d1730aac725f3d50648c03d392d7f941602c1f497506828591439a9b023666c6b7c2a7f73e3ad271b2328b656d19c194b43ce42e5f7
    BACKEND_MYSQL_HOST: 1000ccd1ec7a6347c356acbcc7807980131e97515da98b0c1aa8948d56b42598e8d0
    BACKEND_MYSQL_PORT: 1000bf2a56ce27f7c8dcc4935977a3c56ff993727806519d20cf13697c213326818a
    BACKEND_MYSQL_USERNAME: 10009618315bf483063cf2ecfdfb5c0928ecf41095109ec76a8ac6220f6e1961c42e
    BACKEND_RABBIT_PROTOCOL: 10003f78abfce83c54e174548ff1cfb3bd4fae94a23a4873aff09f2fd207d937d67d
    BACKEND_RABBIT_USER: 10001303afe7a7fda414b8901545621d0c36b83cd8b4e6a0a03848aa0dba68d0d269
    BACKEND_RABBIT_PASS: 10003093810e7b50ce95915e2755de5460461ac3ca28c14ca5c07ec6b57a440e5895112133ef8a81149dc1a59351061e3203d5d95b4c5cec3b014c06303b0d9c4dd5
    BACKEND_RABBIT_HOST: 1000c1f2edbf1e812463358c23213837afa3d7fede0425d295c826a0c67a9dbbb5fd
    BACKEND_RABBIT_PORT: 10000464bb123a3d0261e07990a6142f2bb800d0bc3ae4012ec248342e4f2427a108
    BACKEND_IS_SCHEDULER: 10001604c312d2480822dc473ae3f199a27ec875e78ee9f373b39f47d6e608c45dd2
    BACKEND_JWT_SECRET: 100025da1a06a3f56cf895f6739772a69414d8614938e3bfa06b83127aa330c4ee074cca7d1ccd54b78443c486f1a1cf17759c38f6e5b331e208f53bddc5d31b2d47
    BACKEND_SPECIAL_KEY: 100056b6ec5284c740a281d42acf78ca18b4a5c951f48c6b417c51e8f3756966e68c13b11cd2c1865884061181e24e8e896b2e959999013c9de909294e4cdc4753af
    BACKEND_ALLOW_TEST_ROUTES: 1000bf4f79de828fc4da34bba7e6a938d56f81e33e84d96b1d59066831ea778f4d66
    BACKEND_FIRST_USER_EMAIL: 1000d233995b65365c39b96043d6c8096f3ece12e3d212b87828a7a142f2449d54eb0331c6ed0723f6f8420fe76d7b32aea0
    BACKEND_FIRST_USER_PASSWORD: 100034d7b18ad6d287577d4861867f9ab239d1e6f43907faeb859960651a564317ca
    BACKEND_FIRST_ORG_ID: 1000a11e6363e72bda29bfc336ca903a9c77a7c7d8e4dc4375cdf8d0f2c26c7628d1b5cc8dc1d371260a2c2cfdc6c6e91611
    BACKEND_FIRST_PROJECT_ID: 10008d2bf4963752365e3dfa6c601b68f697d07567effdee2bc46831df9c9bea5cc576c4c100520ea91b09059965073d8031
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 1000edb932fd4eeb369e42c4924c2bbcb1652f589de6bfd26f23422f1cf94bef49a1
    BACKEND_FIRST_PROJECT_GIT_URL: 1000610437ac881b8133f55b7017d3ab0e01b83f8cb5efffd7802e7dbd1faf0d1a09d51412736dcc11cca9790f12af56baebf45f2a1672d950e817c0a7ce64100ffa
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 100061f3d188861ed97fc1b5cfb1534711248918e64a73b05c4ea01f45615f21112af6da40482c83af09e8d6b3dcbb4ddf770f6b83e04f5768ec9cce4a157b08b429
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 1000b87c81ea95743f1ef480d46b0ec6a6932c06700cb6397d68ccb2bf6fac601a57b283c5978d5667117e48b360a59ef2c7ca50b3e468ec6b818706f3fa233296ff
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 1000f203685f784aabd0f99ecc841e32ca66cc00be2ce4e92aea81b9ebe5d41b5477
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 10004a97003ad300b068a857a10d4f0542e7dc1abfe1d7bb680df427d7c0c9f5788773bad3a850be766eb7bb9fd3646a0ed180c07981463eabf008dc4ee47769e58e
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 10008c863800ae2f6b5099b8e117127f85841b2f6270e56a0e54beef2348563afbac368515aa7f3c62b8df34d966dd1725fffd7d83b567b778c66aa69a0c60613617
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 100042b64ceb16d3bbba80eeccbff831618fe73792c640dc9c7e0cf0704512d7110637c41134b137394d843006b8ebb6c8871b7839316bb31eab6784b35227fa9577
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 10006a307be122157c2db8b7a5ec9e1c1ecdd2e7c0981d4ef78cade1053a22caa55c39960f19cc6d7de29ed3b74b68129f7e
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 10003409e098c1ac775fec466f27497f469a199a63daabb09e8980698283be115528
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 100090880bffec3ff6bc63c3e07f13e6864b2cd7bc18715d0f80f35a9b000240eeb8
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 1000d34946a8cb4b449af65764f22896b6f71a26572078d1b175eb212587081931eea52a52a25336c6c0bb34f061c812742a
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 10006daabe65266393918f2eeaadbb24bb33fd8b66fdea069bd6ab8649f8552bf41d
    BACKEND_REGISTER_ONLY_INVITED_USERS: 1000c3dbe3328bf7ea7710c4ba4ce25de80744787cf4ec480b6414e83b2dd3fe6dbd
    BACKEND_HOST_URL: 100019c52ebbebd1eb80f6e5b5e997506889a85247ed8a9f0309d5c67fbb81f7cf41f375bce72db0ae17b6916fe3972d5d90
    BACKEND_SEND_EMAIL_FROM_NAME: 100049ff5f726c20ff88b5999ea5ff1877990fa1bdc1ed5a8e64d89221c777e720c2
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 10007f0b1578a93636b889c118222165ba9e6041adc8328a5427a73927e7fa5aad9046bfc1735e31e0778e1fc4836cfa6f9d
    BACKEND_EMAIL_TRANSPORT: 1000fea0935bccc19ac1e6a2fb3877fb5d4f5f40e38144012d852d3458e3662e1432
    BACKEND_MAILGUN_ACTIVE_API_KEY: 1000b66f1e610b3e573803fb4b030ccdb3b1593668f6c4ada6c6a8ea4a2e66a36c493a439f99aac009509279e8315a2eb2833e37b78e112477d0ede701c66e8de606
    BACKEND_MAILGUN_DOMAIN: 10003ef7dc2b96c4fb3f29f7aef2fd1d02458fc9fb894fe19786921c36ab26c541bc
    BACKEND_SMTP_HOST: 1000b9e4b378e9798aac90903588807efee8bc5247cc24a3c37cb641ac60c17d366df96f26fdb064311ce93b08375a818dd4efddfcbf4a79fa82fa9f0a341f7227e4
    BACKEND_SMTP_PORT: 1000e465e80fd46e9c77ec7255204ce28dfc1cf95b41708b1e438d311d5e77ac4947
    BACKEND_SMTP_SECURE: 10002ac0e56decae5d0a93efc9666c41664b6c6dbca1e55517b961949956b252ed21
    BACKEND_SMTP_AUTH_USER: 1000e6f8d0981b1b91fbd16ad5660ed986e0fc6621f877d34f1bd4854bdd3433e493044fa0b916dcb988e4a3f4684e56b8c3
    BACKEND_SMTP_AUTH_PASSWORD: 1000667b0d9e5320e814711487ccbed495ce06fc58e0c46ad42fb9d1be681835aa8c96d916fb1401adea1a1e1debae114d0005cdfb84bdb6dc9a374c00f7716802fc
    BACKEND_LOG_IS_JSON: 1000b95c3e79b77d8721d0e911ae58ca3343a6950ea1bd1d0fb1432ac4aafb77481a
    BACKEND_LOG_RESPONSE_ERROR: 1000e9d863048275a076d9aac3e08bf0c6a724bc33a1a4edff502b7c3b7a3f9fe0af
    BACKEND_LOG_RESPONSE_OK: 10007a92688b789380190bf285f0bbe3db34fd747693efbf0034b44f52326353d83e
