ingress:
  host: 1000b0b956cc852e48b04e398e97a079462568a6118478ec0dc26a3f881dfab977b9afef1c2d4ddee9ff69aa9fc962555de6
  certProdSecretName: 1000ca72aad0568e482447d4aa9e2e92b19cb94982a0385a806d18e674315c44b2ee535842085595722a294a7fbfd89edf75
  certStagingSecretName: 100038e799df6596dd45f1c07da1cb7fc653510a90546c70c562881c27841cf3d2463cd0f84881df584a2c188ce90e3ccdf5
  acmeEmail: 10009b62121517fbb1c7cca551daafe8dd8d602ffd026bc84a74ae1f9c893b55b6b26562b01f149b91fdd41931edfe8a6073
  routeGrafana:
    enabled: 100085871e72046a0e762c85d4357740cee320ac2a23b99f1148ea70e538706a50c5
    host: 100027a421ecbe0987ac03e441d12e6ec81ef9d7cb0e93c6ebda4db9c4a2a0d69f495240a8284db7de2f32fbf9a01a4db98e
    destination: 1000490b8bf08dbc207ea716bee8b0d4ea68a69f3673b7aba790f52624f44e49526c6e73d0bde57d5718510b2cf1137e3b19841068f3dd7dfff236ae6bf2f44b8406692a9a053e9b4ab99e46a996c9085447
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 100019e1490a52ee401a2202e45627d1755010d3e6daf3633b7ad17e9760a5b8e483cb4b0ec9e7110de5cd885cd25d5584b164c5f1d6343712a764bef5892a2461dd
    MYSQL_DATABASE: 1000f5d80a725a7f0869eb2fdaf79cae3bcfe5937178c746c24cf08c708ffcb6fc2d
    MYSQL_USERNAME: 10004dc5a2603accda5237d9d0fe8da276e5dd7da2a4a0dc668fe2d39ad95ca76eaf
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 1000fa4842f45d52c9378f0a40c4e99142bf9a2325dfd25a2722f61d3ac8a8fb3d6b
    RABBITMQ_DEFAULT_PASS: 1000ac39bed86e53020ef3227d97354333450c36db4c792277ed85117a8af4fde419a2857f828473d3e1626a38238e9fc28261674c7d8e834bdbaf07a0dbbe4bd6a7
    RABBITMQ_ERLANG_COOKIE: 10001bad9f47411d85ebbc72e6c4abbc4fbcef454924fe76749f4e6f959dda4e1f459b44d24c985c653e60ad9ed4513bd7e264a54e56aa6dd0e8dafb5d75a3b4445c
grist:
  secretEnvs:
    GRIST_SANDBOX_FLAVOR: 100032dff4e30f19f6302cda50747de82acbdd362a74179f74a080d09267a2aa2bfe
    GRIST_SESSION_SECRET: 1000ea22a61f04e7ca9d44e1c3da792a033c9aa10c566ac5e956cd1f936dd473b07dc16b44a7a4d15c5eeb87943fa86ac52fcb0f29f1fa268f6c4d09ca2bf94d1be2
    COOKIE_MAX_AGE: 10004d15401803d5fb5e105bb8020f4b3d8a48803c7ac19c4521c1d7db3eccaffa23
    MPROVE_GRIST_API_KEY: 10009afc979e23ae790d8315863b761f979cf68c790482b36b2101c4579dfb8ed8bfe7c9cb4902869d0caa3a93aca2a0812d56f3cec0a987407bdab2e03e763bec0e
dwhPostgres:
  secretEnvs:
    PGDATA: 100029c06f5413143f3a4c2c4d9574631a918d9e12eb6a95244e9de79de86a73ffe4027283b39e05c511ec98f5e7ae942555
    POSTGRES_PASSWORD: 100014695f9e6e079b0ce1a0c3b8d96f894c65eb9778460bae151b2645df2ae7cfa02478e552f6ef851784ac7eec416e4fe36ff5d83881c880e9e310775e825309e7
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 1000897f4e3c1add90514c9d910889a6180c3f839a2dbe1dfa9f2c67f3a89ac7d253
    CLICKHOUSE_USER: 10001230f782d7bf4f9a8203cdedd2bae0c49a4a65999687fbdc57b81b9e2f0ce3c2
    CLICKHOUSE_PASSWORD: 10007cb35d851c8f06dd441b3578234a9fdc039e03b3e8e90e2bfe8854f0fd46223556a51ebda36b297695267d18f0b5c15694cf04102529c5e2c8c1dbc995ce144f
mcli:
  secretEnvs:
    NODE_ENV: 1000789e1562db17c0042f65da99ee9fa736d3e7acd26c9a6c82950fc4c082aa55b1
    MPROVE_CLI_HOST: 1000c18350d55c4ba92ed5ee00fc3c076d7309346f36c9730b463d719091ce1e2d85771898de614318625108d76513ed0c6a
    MPROVE_CLI_EMAIL: 1000983dde626cf14f0a300a799e8efe3a862a2a5b2c1857ee4549a80c2ce7734fb6541fc7517b335036fe25ca56d0addbce
    MPROVE_CLI_PASSWORD: 1000197d71cfa4302a9de0407f3eef20dc45e14598e0ac4ecdf5295d5fa3f6fe6d79
    MPROVE_CLI_PROJECT_ID: 10008f87d6ba18d6cd5670d09e02ac9d9ca8a09c2ddf98c5f0be672424af75c36552f2ef2eac8b8678474b1b1e9b2b7fedf0
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 1000593a6018e9aaee9cc1e02b62fc341af3ef809abfd06ebf22df8cefdcb532a74bd5f4acb8a2954b11c72b4b4be1f9e275fc8856b8351da2357e8b3ba5b4fe40bc
    MPROVE_CLI_TEST_DESTINATION_URL: 1000cc103440c3e343fb10eb1df81b2894222cfdffc0677858793a6511e1d5f2b3d1a1254f3c12b9bd1e2eb747e81864c4f9bba41969e8ed8e61704967e14dd73c63
    MPROVE_CLI_TEST_REPOS_PATH: 1000736d08675329d2d3104b37e041c027e9007dcc60b3bd919490dcc6db8079b091f87fd1a992ea4a0b157f4681ecc4cc74
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 10001e63e0f3dbd96d95a01d32d0f9766ba8570cccdf98b685a9e2847231a2e6b1876cf82bff1e930bb860d789496ae45787e150a2840ae7f9ba645ca7f6d675cedd
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 10001111d0fe1495a5860d1017cb34023d0e4eab355774c57f4b52cfda551a9427c6f8c558abfd761c0ec1d0914c7f1083120e4b7c1e7b5dca5e699a59b83ff6aba52429f1da7472fcdd08677600db753e7064d1e8ffa97f718a244433af801d972bc5b98b22642ded5a5ec0258c953b6c0f
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 1000ee6c7baa01307478f5f3b7602a7cfaa38fd88dbc874c489765b42d4393d878bf1fa1f189716848c4e304c4e436c01b3a37de7203ca22aa2b24fa733cfc72d81b
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 1000a4525360d5702f1439ee8b20fb39cfe8bf38c2ba731b0d0a9e761937f25e0c91ce464ecab60b5ed42c2ea757a279a7eaab931b29f961d0d2da3b41550e0aa235
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 100096f959c755fc4a39a20a3dc598af47f2a34a21c8a1475f12534098d1695e273ac81c88b8ae02023984a16ce32c722fa8892f0b70b65d19bea9026e9064c272ea
disk:
  secretEnvs:
    NODE_ENV: 1000763fe53c5dc584b1fb013b5010231679089379d8ff05a3eef2d56569a4766d50
    DISK_ENV: 1000b79d8b3f36fbf355c60e25399406bba2a2bca4790b9fcb7224a7699a9130b9a1
    DISK_ORGANIZATIONS_PATH: 1000587dce518ffafcf7870ab409b940d48e29e9ab5d5eb0b9c19b2ebf7232d597b10c0fe7679b573e5c7374da79cfd98196
    DISK_RABBIT_PROTOCOL: 10005fe6edd62e75a4ddd2acb838777d54034bf8b7d4cfdbae3ce520be1e2046a0ae
    DISK_RABBIT_USER: 10000d0466340de86957b63bbb3455667dd252390c2430fb841d300aa5f40cb54874
    DISK_RABBIT_PASS: 10008dcb2e59159f8fc2904e752773231c9d6eb5ffc151c3c24993cdfa32de42e7e5ac025077ec91dbf75ad6666f135d9f1a4172c8c6e431bbc21ec485349047462d
    DISK_RABBIT_HOST: 1000b4fb36d95ecbde5e0f4c12dc632fca27f40e5d95b6bdbf47495590b0fdaae7ce
    DISK_RABBIT_PORT: 100015a53aaad8eb7fa93375a5c56a65fd8e59afec664e8cae232f32a96063a87fca
    DISK_LOG_IS_JSON: 10000dacf889e6982cc8d4f12700d5426934c580d2f0d315461787c080d8d43e2db4
    DISK_LOG_RESPONSE_ERROR: 100029ec86c71077252264970319ea849a295451f999289d61f335d23fe7a7060c96
    DISK_LOG_RESPONSE_OK: 10007bd40a41096bcb6c8a58faf0ab50006921e77862d8f0a9307efaaaf0537451ee
blockmlCommon:
  secretEnvs:
    NODE_ENV: 10004ec72da7a8a17f90f229bfd679854bc7e790f172954cd5d03d90319d01cfea5d
    BLOCKML_ENV: 10006b884947c6530f55dbc26a96d62a303a348cca08ae0d89f5775dd8f637a49af6
    BLOCKML_RABBIT_PROTOCOL: 1000bbf7a1d82ede38d7e76b27372d4a4ea1f2ff7dfb62eda6dc0a70f5b3fed9c8bd
    BLOCKML_RABBIT_USER: 1000b3b971eee0ae2a2581d6530840ef5d25901e1d7ada00eb3ac1f878bdb581663d
    BLOCKML_RABBIT_PASS: 10002cfe37bdf7626ce0b38e5135c673c63094a08c71a6fe4425f9e0f42159b7ae1fad97500e04f19cfdd30a0a5242f899ccfadaaceffc883cbc295edc5800bbd7b6
    BLOCKML_RABBIT_HOST: 1000f578d6e780326a22c002c085a1a6614789682c4a5437dcda8326a6926e6a6005
    BLOCKML_RABBIT_PORT: 100059f6930b6928b39f9c511609ebd653fe93b8cc82239830bc0c5461f9d728e44b
    BLOCKML_LOG_IO: 100006daa9075914869457274b1f4993d40edc4d9a8a7e0521496a007c06508771ae
    BLOCKML_LOG_FUNC: 1000d2d1edb0a7c54126a51cc6631677ca31eddb5623b0f67a6529419c97b2aaf920
    BLOCKML_COPY_LOGS_TO_MODELS: 1000aa7267d4e91dfbc4dc5882e1c5262bbb2dc373b0e24b70c3650af705b1d879f3
    BLOCKML_LOGS_PATH: 1000a93422428c4b9b664d7df0af5e71e295e1af0e6d6e6a20b3f71e72d81f319fb9bd9e1aa5fec0d7f7389f55713941c4ad
    BLOCKML_IS_SINGLE: 1000a0a2b7aa145dc69287d2f19d2e2de67333afc63c9a044ecb1cbfcca38279e5a3
    BLOCKML_IS_MAIN: 10005387165a26477735b0090084d05e78ac6cff3d40b7db542fdca7e0907ce2dd80
    BLOCKML_IS_WORKER: 1000a7b418a9d1c7a56a47d29983ab26114d3dfb712dbc29d2e79a79d5c0eaadcf81
    BLOCKML_CONCURRENCY_LIMIT: 10009bcd24e3606d5b763acbb2aed2e4fcb6dd074a6ca6f3dfe7b77fe0e7d915c025
    BLOCKML_LOG_IS_JSON: 10005e78cdabb7ffe732a125a716dcb35cf54fb59b168555e04182acd578f38437d0
    BLOCKML_LOG_RESPONSE_ERROR: 1000eba343e9236cff47feae5cd23164cdacf855fce4781c57ddf0a0225b331f067b
    BLOCKML_LOG_RESPONSE_OK: 10002b6f5a0ae2b692d670b77baee9a8c51af307b6f5451634453a6909d898b1efc4
backendCommon:
  secretEnvs:
    NODE_ENV: 1000bfd07047e25567784d3e188559ee97519c6f400adbebf12a3da751bdfffeb4b2
    BACKEND_ENV: 1000eca44cbbc3cb207470d3bbd731b84a98f797057c879f3f4dc94f2f6e76d6a1ed
    BACKEND_GRIST_API_KEY: 100043a731bd2414299b772d7a6514a7ae57002742d4a88bdb95e52f9e0b652a8955ecdbcc261c27f9a7d60a2e9c85905ce08aebd80e3ac42a875b8d62fb3edb20e8
    BACKEND_MYSQL_DATABASE: 1000b61429835f2a8051044f006e50ba2a7bd3c2b04e6b24d391f9cd5e1eaaf28f56
    BACKEND_MYSQL_PASSWORD: 1000748c593e6126b29f34e148efc08c94d89c176ea3d4b1b277f88a1bb4543a000dbce019feda10330d101742a455bb3170b27bf498ac155a0778a19e4bd28879bd
    BACKEND_MYSQL_HOST: 1000ee62f2fc3cba89e491500f0ed431b6b5a5235f2ce60a3bf7d65ec60dbdd9e8cf
    BACKEND_MYSQL_PORT: 1000dab80433e71a1ceb918ec95279fc3ff82c92f3c51e8f04dc852b409ca94e2dd9
    BACKEND_MYSQL_USERNAME: 10000cbf4878c579dd02415e894608c03019d018fdad285883380cca8d50de06d834
    BACKEND_RABBIT_PROTOCOL: 1000b85a6029dd7da8dc54e1b4836213c737b804a379cae5146980d89b6bc1dff9d5
    BACKEND_RABBIT_USER: 10000527311dd70ec33c23a806ea95a84da92d6534a240a048d6fe08aedae8788436
    BACKEND_RABBIT_PASS: 1000313fb426579eb8b0c4578bb5782b4f48c3baec111b31fe5f81fbaac097250ecb49319d66631f43a50d6158ff9d27c6e7385955c08c0cbdea84aa6e19827c6d92
    BACKEND_RABBIT_HOST: 100059638aa7963b3371252fc1e98682a57199dc1c6de6c7d0c2381830580ca84ace
    BACKEND_RABBIT_PORT: 1000fdc68beacd2653a2026a11403b563b5dabc3649efe6b357ce7dd320a36a840d1
    BACKEND_IS_SCHEDULER: 1000ec59e96c5af3f318cd3e1085594d5169596c41621b7ce3e954af76074442335a
    BACKEND_JWT_SECRET: 10007e6e5839da9a1f2f551d88e557c3e0d2cebed4701e4af7612275ee8a75ca0bdc3827440489c92cde2c62b567536221b11e3bbef58cf99371c5fa930747fb3312
    BACKEND_SPECIAL_KEY: 1000867db4df3d770c500065f383fda3d7020610034ca51d70785c51093ca74a684220b3282b733ad04bd2bea4d1c5b99026b0fb885a2eb661e189b91998dfc24d08
    BACKEND_ALLOW_TEST_ROUTES: 1000271520c46f66b0598517287e8d00565613375f65b709245d243fe31376060f19
    BACKEND_FIRST_USER_EMAIL: 100090b4bc6c81ace652bace3b15d34fe7be0fec9f2d6b75f4b40e550c1d7d0c1c8945ad46946d9c0b9ccc778ac865c1a91b
    BACKEND_FIRST_USER_PASSWORD: 10001e6fd99a7f2cbcddbd7fa61b5bfa003ffd8d997bfcc0b8c9033c807415408b42
    BACKEND_FIRST_ORG_ID: 1000a3bb7d56512f438c212a5be97f84477a9c66ebf845904bd0c889d1cc19422c02feccf8e9f9a93a0fc283e96fc554a683
    BACKEND_FIRST_PROJECT_ID: 10007ca63339794868906599ed88a93d9c7470fd9ba8eb5e65a8aebe993a993c08215a9c99067dedbb895863ed5b6d92dea3
    BACKEND_FIRST_PROJECT_NAME: 1000a5af047700dd7e58359e2938bdbc751e4fa8d8a69d18348d5c3640edc4c72e89
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 1000b762e85fe8f9bbf8626c08082c63eb92e73576f29c3faff297ab9df2b34cfcd9
    BACKEND_FIRST_PROJECT_GIT_URL: 1000a011b96214ff84c6ae78fd94fb60b901e27eb9ef3ee997082009d76ece20fc9f8a6eefb197ba2bba1a71a5db8a3110fcd5416ac4e2a5cdf63765d4258983183e
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 1000ff2b3b6d616122ae8d6cea804928e9cd1fa3c93c8a08bbf6cd0bb3bec9a9031ab149752940655d1d16ac7fce4901bcfee76ab5621681aa112e63f72027c4ce09
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 1000ec5adb9cab95cf2adfc3c02d9b0ac97677b76964c9b68a8b22b70ce685f9ff708bcae1d146135e7f23e4aaf0bb159430f5bef0cbb102a7b70d67669cbadecf54
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 10008aeb8e585bbd7271998ae79257326b5a87bd3307becd13128045e1b7a0b0471c
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 100075aaf94d68c2b4831966a39b823707def6721465d9fcdea8c155303555d691bd9f86eb30f95c3fab69253c3e5be27437f522480bd6712cf7a66886380afb2ecf
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 100054eb2fb7e82fc14a4439b9a163cb2da1273e22a659f517768c69f4084141ea0dc1432fbef5348b0dc94f16afee55d07fc52f8e3bdc1f2f78a0646517a275c2d6
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 1000f6573cc7654e3d20ae989fd9c4a321c76b785639019e02e064f25977e565f7c8b30f15ae7564843969274f34291bd038602b78f7bcc188bfeaed4952332ebaee
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 10009299dcd7ea771ca91009b0c5bf3e58eae599004884ecc6efa744801c3c09c42fef17d79d410ecb6c980ba9a8ed014afd
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 1000e31ec2ed6d32d1f0aa56c29739b71d3c71ed58640964c42e057cae3ee4531cda
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 1000a0138b477d377315db9957b1e0562c4e282f2575e04304aef883a119cf2e77be
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 10000ebe2b9ed6953c4b8c09caa470463de25c6a05f51b27fc33988d4e0ca3b94d9d0e94d25f854337e8ae58d22be79fdef2
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 10004566f13ad2ec126f8c870bbdc26081e3717811bc2586420cffa021bdff4eedd6
    BACKEND_REGISTER_ONLY_INVITED_USERS: 10009f690733f97c518fac4d75f411f2b18b698230c564ac45a2c326026a0a3dee03
    BACKEND_HOST_URL: 1000c197f8d18bd18505c68626ea0826af7d56b6836186a65adafc0cea77b865d44f79ad8b2179f50a763ad7e2c7b2f1ed38
    BACKEND_SEND_EMAIL_FROM_NAME: 1000e613689526c37fd967c96ff1fe158bb8c0da30591da859e0b5d8f71ef4357a4e
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 1000dc3ae31e8f0834b1cfeb1a0fc34677267dbe01e1c76faee1adf76a61316bc0b11dd1d8970090e335ec9496ab0b40f204
    BACKEND_EMAIL_TRANSPORT: 10000020761bfec5698f2190217e77442b0a76729b8e2d7233f0ab5bc98f54618682
    BACKEND_MAILGUN_ACTIVE_API_KEY: 10002bfa1b08a3fab012c2ef8d2204031afdd77756dcc1ef55fb043d8a153b3b106d334d68b4a55f0f3ddbbc832c58664e35eb68c602cca86b57cd2dbae6cfa807ca
    BACKEND_MAILGUN_DOMAIN: 1000b4274a9fb7be96967f323300d21d4b22db0155b8f926476ee1bc2eb35f3ebf96
    BACKEND_SMTP_HOST: 10008e72559133f989c69327da5883dbb632eb506948f689e15e27957bc53209dbb238ec292edcad587593bf2485fd0153c98c47f4ae5f4dd43692a09d494709253d
    BACKEND_SMTP_PORT: 1000c63836a311a00b92128047a1398f547109e243ec6e6dcd4eaaec5ef60560208d
    BACKEND_SMTP_SECURE: 1000da8efd1f78cca552d8a350594257755e72020f978fd60b46350da901436d3787
    BACKEND_SMTP_AUTH_USER: 1000e434278bdb15f8b2bb686516a7764fa10b963da7deb53c0f8833bd4540f2324adfcd66438ba595f793fde7ce714b7d0d
    BACKEND_SMTP_AUTH_PASSWORD: 10005aa5b734e87a6235c91da710ca62db10c70e8d4c6480510af29515bd14334160f223c66d386fb03ccef2a1315438a16089b3cd2bf7ae11e3ba9a468011dbfd74
    BACKEND_LOG_IS_JSON: 1000a065e467cc07f931f72ab8870a28c23da37731201cba8d34a21b7ac3368965d5
    BACKEND_LOG_RESPONSE_ERROR: 10009e0da12bd05f46d070b6cbe34d4886293db60e735e0334bdbaa93005ff817bf9
    BACKEND_LOG_RESPONSE_OK: 1000b84a4b4e687fb3555f4c21e12fd8e0ad6787edd009259d7abfb205045b9c5987
