ingress:
  host: 10007788ddc54920737f33b497afd9f6da9a28984e30e62981f43e194a44c12ffd3151d823041fc98b23feaf9a5a7cd6692f
  certProdSecretName: 10001a1c38ef26ba670ff72564bb8aefa585c74dfba33cd397167e45e93018e7fe210436e1d1e13639a1d8db4eb199d29dfc
  certStagingSecretName: 10009925707abf818af56131839a4e11ef7bb0d14b7b2365101943525854b4deeb5edaedbf924a6995522272c3207971f436
  acmeEmail: 1000569257073edc6808ab37f81f98e335f3bc4e5510532e098f96bd9a06172a794eb2b2f6e16668bc7a05d6c417934e1142
  routeGrafana:
    enabled: 1000a88dcb9dcdaa8c8c4a4ee030a8eef2514c66d9d42958bf3f7f46ecf30720a3fb
    host: 1000f223fe8fbc7d90cece6b4350ca519582bc6fb6fceec614c836141ae9931886a33d7b0028757e2f925b4d160f514ee0b6
    destination: 10001239297f762aabcae409c5a212b9245f27cfa7c658f20c33286ef97e693d4be252211715931febcedf0fd8289bb5e287ebec47bc545141ca9d596226045c2e6668fe3b8ec9a112693f36c67a3cbe2b72
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 1000fa6fb6c9405e31c881790edebf52516383a90a3b7a467b99a88cc256b791d250ad5e63fc6b9a385df88ee13b9997fe0d1a50349f1faa174358b3878442ea6035
    MYSQL_DATABASE: 1000ff9db5302bbc506f65ec6908d37ec12bc9f2b41ee4e9b14463310c536e46642d
    MYSQL_USERNAME: 10001e7baae77e2631f730b6db278a00d3ec38c8e5fda2db6d8aa1e5022dd74eadde
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 10008f5588c8261114077eafd8024e92409d31aabae5fe4e0f07d2c62374fca7df32
    RABBITMQ_DEFAULT_PASS: 1000970280e4ee20f78c72bf61caec511ae10417834ae08f8db2f1ccf96eb6a9d3d62a8516ae9ec11d3c968c46a2457e44262eddf2d3e6e3666377c7694467ce4679
    RABBITMQ_ERLANG_COOKIE: 1000df51dcf5e1e72286162eb8c2d06ad619abb87b288d098452258ebfc597225e3655ebb2969e72856bd5b750788774257927f5d969f66690187c3b029d93667186
grist:
  secretEnvs:
    GRIST_SANDBOX_FLAVOR: 1000129ab88f96244557e2398dfc83828719fc1f8c97d862f9c24f033be5be1d2996
    GRIST_SESSION_SECRET: 1000f2694f21b33e67da12809b5bcacdd0d16532370ab410d52c3118e217560b54cb9bcf6c0dd43f0e6c6c2caf4e04c49a4e2e6724e6aa8b87a06f7f7a499146749b
    COOKIE_MAX_AGE: 100000cb74570ce17068677301ef77f46c1b6e8d0605f282f8fef14fc1ccdcf11bfb
    MPROVE_GRIST_API_KEY: 10004306161e9dac3da5f506bd5826e2151dc001c86c085551689a7ed6e1f49614a9fc595a45d60c2e5dbf46acfeb2dbf157c1f59687321750bb14966f0234d6b2ee
dwhPostgres:
  secretEnvs:
    PGDATA: 10005a7ddd3d11123ca21126d80c3c4d4af8cd53041cc9e5329365412c35274384cac5810ee632ca9e6d1300fa3e6d67ba72
    POSTGRES_PASSWORD: 1000d711ac8b2b464488108ec4420c989125f5e133ec1c34da178921f4b22faf25e1581893b74873752afe7a4d4d557547baaecc49608a04799ca759de65d3942dea
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 1000af94efd44619dfe4dc73767d31e6402783f04cb04c4b9e32b3bbeac8333c9402
    CLICKHOUSE_USER: 100093b876cc467e3a597f4787d32960186e5d576d77f285ce2303f2bc2c863ff290
    CLICKHOUSE_PASSWORD: 100091e4c8fc1fb5c8840d986cb763d7d56ac92b9fb0f1f00d78a038ab240f99d5b33f6158a5376e4b540da646d0e5a6bef98317a71be636ff08ba697419e89dcd72
mcli:
  secretEnvs:
    NODE_ENV: 10007214cafe91b658be6b6674014b8af739c518ea8e0ddcb47adf43e5c1c73765e6
    MPROVE_CLI_HOST: 1000cec3c3adb19ca3af12b33da9830da2e51a82a4ad9ed37869dbeb2c5b9cc2b4418e9e166051947950edd8573d8488aa03
    MPROVE_CLI_EMAIL: 1000a9143f5b178236c524728d1fcf6d13bc1dade81c255acd396d5b03d0108ca549f50311bbd67b0bd13408fc89f80bfe11
    MPROVE_CLI_PASSWORD: 1000af2c9124ba545024fd4d47ec795439cbb2ddeb142904aef2645ae335f3a1ad84
    MPROVE_CLI_PROJECT_ID: 1000fb5a371d36de33f30fb99402f4f8d77a6937478ed651b8f2a86781966276803310893b746e2319633d7a35e5556d6eee
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 10004a05bac392a5b01c6a5007ec0b48c9163222ea0ee4d31d418fd85358ae95f1067f7650de726a8f076930d8199d4f8a8b5ac7f0dc9ee0b830a8a81834c0f6412d
    MPROVE_CLI_TEST_DESTINATION_URL: 10003d0d45f10b7d2dae7226d3cf5c1e7051b88bc2289911df7f34762e2020b1eb8c8741f96d4d7ec6572e2c102bd96c7188d3e7613423aed3b3bffe417b1fc505ce
    MPROVE_CLI_TEST_REPOS_PATH: 100093696595622cad33afbd448c38b8945523cf3e13585783d7c37065d434742e094f840498cbdfc417983d2ffdecd063df
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 10008408f1533b48e643c91844a4d3ba40d1d8cb7f81ae0526048b2930bfcad22b66497dd519d50cfb8ac3b9ef47034f933befb5ac272c97a05789fd1ca72f84b73e115d4abd85267339dfb11fd4d92852e5
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 1000338a9a671fd0b90ef4c4d30de2e6e17c9c1213447439253cdad826b20d1a459d70d72efec604b950fb446b01b51132ce0d03d691397351badab723f7a0213853cdc2310e5bbc8848fb1622bdcf8b52dedd6606abc6eb6941c74f01d3aa73d66ff8bed76049226f9556ab99710adcbc38
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 100029a7ed7cfd0f91eec70d49aa1752962e08f467eac7f2759868278ceb190e6631b2bf94c67821a5426dc738c9b35bcb08a23d0fb9b5ef2c730b9196d4c46472d6
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 100074bae34d14ae61dd36c877204bc1ae151700df2411050b3e490557ce15e0d692e2562398d52ae990129d1dd7d088c8d6a56eae068c4c1d3e3d5c5607f38004a5
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 10002f84b110493d3dc5958b78667ed8d4af58a6082a3c6e6fc6831d00334e4dad3c2dff71d29b283f4d3ff5cd66cb900a9a53a3797c484a23106eee902c5cd9357a
disk:
  secretEnvs:
    NODE_ENV: 1000cacdfe462a3bdc0bf2e98f4a97a8e156abde3554d55fd7122887f31f031a8eb9
    DISK_ENV: 1000f1b13ee9ce417b35d927f8abfec3735d3a0fbc118c86c22699eb80f643ddd367
    DISK_ORGANIZATIONS_PATH: 10000c4b1df5ef20ec74ddf3d1c5049f71de9ddfcc5527d54a53b28e6e111b24c1ea91662f289c63a4f30ef405b76449dec7
    DISK_RABBIT_PROTOCOL: 1000b57f55f9bd433c6da811b473063b18a61f88459bfa803b92b37f3d5c704a38f1
    DISK_RABBIT_USER: 100045ea4f0e4f3859429e68f4e7ed37adb9d5371fc2246af549795298be52521efb
    DISK_RABBIT_PASS: 1000fb7edfd50063ac1daa153dbd5ddb405e64550975e11fbe76e2a5d2ce2911d62d9974987a9a052536517db8b461d32a4acec0961ffaf75958c47f50fddb6a097f
    DISK_RABBIT_HOST: 10007949f79f3907783ac2c9d246bda53bc5ae7bf0a99c46710aa3611a20c5947571
    DISK_RABBIT_PORT: 10004b5cfbb09dc6faccb770a5866b172449c41a98daa6cb44555f105cc034d9a7b2
    DISK_LOG_IS_JSON: 1000fbecb34d01aa35614c55879210712665102c28856b117bbdcfd79d2cb8d0ea68
    DISK_LOG_RESPONSE_ERROR: 100005290d728004595ca1232c63e392b9ab4ca9c17af930481e8027796c87b9785a
    DISK_LOG_RESPONSE_OK: 10002e615b68f157f9271d80ae9afcac22857bb4e46205b896ec537fa8f407229414
blockmlCommon:
  secretEnvs:
    NODE_ENV: 10002460b2ea0355fee4bac84cfc4a3cd148f8eba354599421274b1208949d24f937
    BLOCKML_ENV: 1000605e1150bd6ff770144806ba4ebeecf4b98eab18c205eaa8f08758699e3d4cee
    BLOCKML_RABBIT_PROTOCOL: 10008cc31cce0a14caf9b35dbd441f2011414162d76190ebbf25187d2c9cb54c3bdd
    BLOCKML_RABBIT_USER: 1000a571741a42d916da04b3bd758d042646bf4839b16ef0ecff61026acc9867bafa
    BLOCKML_RABBIT_PASS: 1000c5e337c8618401e9c033ce27aa5927d9fed70bf276e5b0884f1f875ac4b25058911349672b21ecfbbcbefc6d35e7d4c676f21a6617f542408d0be3e7327e6bae
    BLOCKML_RABBIT_HOST: 1000101afc8aa43460f570ce0bd8cc3f00cb2d70b30000cb83d6fbfd2ea00a5765e1
    BLOCKML_RABBIT_PORT: 1000fec55750608f73eafdc3e3848827341c7e461976d6c690ca3cc70248a1f92819
    BLOCKML_LOG_IO: 1000523fac089c89f251e08f6733d4ae72410ab9025fbcba1a401d59083af77f2103
    BLOCKML_LOG_FUNC: 10006773f49bf459ceb12648228612f51c07edee479d72d8d3ebc4b55b19f5bd9126
    BLOCKML_COPY_LOGS_TO_MODELS: 1000895585b9627e44ef13c159178fd589ebcf5ca239365fba33f331477e304769b8
    BLOCKML_LOGS_PATH: 1000cfb76b23235d98c1ffcd169baddd331d87600867f8447097a5bb27dac3300ec83f8766a2c35f7b57d9845d4a5b450e95
    BLOCKML_IS_SINGLE: 100084490f3b5cb115ff9e9624c6c959cf0a1259e21f481de6ca51052d89c628f3ea
    BLOCKML_IS_MAIN: 10003a7c90735ea2dde669deff42cedf057a6f419afd6f22d620c97207dd2e844785
    BLOCKML_IS_WORKER: 10001b471eb3839cc26f2325b22f37551b7f7ecebc105aba9c0f0b82affd0075eda6
    BLOCKML_CONCURRENCY_LIMIT: 1000a6c35698eb60802be8ae70e60dfc0a5b1779c9ffd65bcfa069981671e568f416
    BLOCKML_LOG_IS_JSON: 1000450b343a73be0aa06083b3182e40f4d67651fd2f14bbcb6cb9e521a8641a70cf
    BLOCKML_LOG_RESPONSE_ERROR: 1000787c6ae2b27bb4b5d50f0258644bd66e21a89d2bda03f93180b61d4d2de183d2
    BLOCKML_LOG_RESPONSE_OK: 1000c9e1542a488af919a23596fdebe17b52efdc91a1c1fd81298861bd9049b74d14
backendCommon:
  secretEnvs:
    NODE_ENV: 1000eaa856892584759995ca67326fe4d1ce0ba98f47246353d4ed079e9286bfef56
    BACKEND_ENV: 10007e3b2ed33dfbf926ad64b160693cc2bb0ab6c87266ee2de1c811e0cd600aae95
    BACKEND_GRIST_API_KEY: 1000bbdc0fb9cf1f6662804daa93d906129594388d2dc43ad26857852ebe34519a5c2e33bb5fb71eec1b8d22efe1fc35f58f18bcf9e720565158af4d3ccac837bf2b
    BACKEND_MYSQL_DATABASE: 1000fb3305bed7e2879bd5ad7e681da669499db764cb624e5c6945ab4840a010a5f8
    BACKEND_MYSQL_PASSWORD: 100068b24f4526395741560a9d551f95c52f4c1cb1cae4f391df4ff2ac44fc0e5072819e79159414769ac76bf10108865b50d7d7d11e3b37488d25c84ff0f5653372
    BACKEND_MYSQL_HOST: 1000dcf7a718375b6d7e7b2e4d39ee04eb5f089028f148497992fa74255efdb78e3a
    BACKEND_MYSQL_PORT: 10004bc0bb99000e9227ac9403f559d462b07ae3b06afefa1c3b3d02e808b58956cf
    BACKEND_MYSQL_USERNAME: 1000247e2cbf968db98b0522939f79e06b17230bda3c6ad25dc4b57082ad38c53337
    BACKEND_RABBIT_PROTOCOL: 100069806f80c387c6c7ab6e5a190d2258514605f512567745864fcc9b2d4c79d9f5
    BACKEND_RABBIT_USER: 10002f91686d503e57daf3606a87f932576f38b65b9415c081f316cba3d8f58b0744
    BACKEND_RABBIT_PASS: 1000db8f2423ad200e9721d2206ecb2a1f55e4eb02cabcef14621257fdc953e5fedc4a82e58650bf77dd8c12ee7a399f17f51c020ec64b03c574bccb2a7e248673c1
    BACKEND_RABBIT_HOST: 100077cd062390aa53d2756ea8f0d8ddf367fe596433ac64afc582ed816e63a060da
    BACKEND_RABBIT_PORT: 1000524f9c124245dd21804e301a4081f78bde0f8f6e00c05b9da52c396db2e2f666
    BACKEND_IS_SCHEDULER: 100056d74a4e50d57adb764e8b6a0a028c6e5b778499147e6a421974ce4ae1a615e8
    BACKEND_JWT_SECRET: 10003ba5f8e27e4df93fb4275912339de4ca53a4aa7ad6aac9611a9f8cfa8789800628364b4d7c00e5ca8aff617fab82b21ca375216ce4be5eafe2bd78994efcd1bc
    BACKEND_SPECIAL_KEY: 10009d82fb11456635a29438c5df3ad0482fe3e4344c245ae2df1aaa9650710bb3d150371def16b236b33cf99e61c59cf490390931db301653ef1e9b66b48da4fbbe
    BACKEND_ALLOW_TEST_ROUTES: 1000664faa5320665531797a83b99330d76f99e925ebec529eb8d0fe2dd325a4ae8a
    BACKEND_FIRST_USER_EMAIL: 10004bc79829b9d8b73022f7844bab6c06a6ba103a418c301a3ab57b376fc994a8f03f8b498d146982882cd5231faa5f7f63
    BACKEND_FIRST_USER_PASSWORD: 1000054f03c16f628358b194c27a2802819577d004a77c8e28ee9195868ad9409d07
    BACKEND_FIRST_ORG_ID: 1000aae0aa761b85322d69abaaa156c38e970868ce1852393a9790fa244e3373efd5c4e7c3f5c6d5cee61d0d5b8fb99063fb
    BACKEND_FIRST_PROJECT_ID: 1000c4215c366e48b874a43419b51903a14c58456f504ddc86c1e5a0191d8685e6db26ed72a95e5c9214f46e869372508667
    BACKEND_FIRST_PROJECT_NAME: 10003a8b6b1d543c87c0f4ddca700c51d4fa0d3d599023714284c38887f7a2ee8739
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 1000ae38539b6601cdf3e5204ce6e0f35c851d807acc915401399b4402f86dd2a9e2
    BACKEND_FIRST_PROJECT_GIT_URL: 1000e059d7312db3e89d7edb060d26ed2cf1de31cda6ea1e72d2752337c97be38be3bdb15c41f1cf52726eef525c6ead5ce1e16861f3aa68fa6e14b90f65cb2d0f1c
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 1000e55d2abf881f85f866dbb17b3407f97415c3df4aac46c46ca5b740bee1b28d5e47455dab3301f52f6546fc15a422bfe3e9ed95f9413a481a0ec1ffd037f54355
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 10000a1cb1ad1aac2b34740814588acc51e0684c2a02c1c32a3c94f6a0d1c261b68841979d1195ddb9467a458c6d613fcc9e65f873050150a284bd77196326befa30
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 1000fa912c8de487b628aee09e32258578c93873be5c275b3268887a44507a7258a5
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 10001549c9b30399786dd5b281f3dde3cae158f8aa8fa1a8200a74e5afe650a71129bd29f8a4de52697746acfc79c5a00aafaea2e8c3741d5326a494b2a72f2780cb
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 1000abbe2af7599d352692930229865dc9b9468ec8d6b89bb9d0a1acf192bca0c520a61ad8b68b215559aa73248d1ccf4560eda41081191954c365658954beb0b6d2
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 10003cec5c3f35f319c011be8e373cb0549045cb8dc450e4817ba2717d92710a53012815222caafc575662bcac30978d2a0aae8fde29e055246e612a6bd943765d14
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 10007e1fe42df1bd8f9e502e272abd68450313ccc9ef06e08c66e0a56d348eeeada0d1b397593cae4d88e61f3556a2c16936
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 100045ced1df2d48d61dfe565eef1bb98ad89d7529a04f37504951f365c7f8a0a629
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 100096d691d1474698c4ce69d4c436402bc9f34951a0cc30eb14b90db49583821271
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 10004e2c2fed714019b66d1b86c39f86a1b71877cd4fd580b09d05a03e3ea77b2ee89861bd76ead1fab5a91fbb5ab5e38ac6
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 100021920a8a152424d06ab829420668d8ce384cf1ac741f35bd919a11bffbb10336
    BACKEND_REGISTER_ONLY_INVITED_USERS: 100030ec9a5d15b37f02b6b4426a138bbd459e16ce0e29475878d0df72e44f3ab660
    BACKEND_HOST_URL: 1000b67358a47cf611c0e6ecb24dde3fa76a32fb7a9be1796251fb42b2c5868c0791ff2aa18d6a16cd4788c0d2df403b4840
    BACKEND_SEND_EMAIL_FROM_NAME: 1000f16853314e0ec3b0cd4055ae51f3db56e774c0771854d7a4cc285a3f317b4010
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 1000a0553d379c4dcbfe12719f98b3ee5de3dc43a4c8afc735e04681e55d2a30275314cc147cdc8ddea7b4dc2806e4cea7cb
    BACKEND_EMAIL_TRANSPORT: 1000f1fbcc08feb48f038fbca8c6b5e0565bfc0f891401d2d08b340d33651c74aaf1
    BACKEND_MAILGUN_ACTIVE_API_KEY: 10007e873e56ce8f14aafb77aafa9c34259b5e5828f24eee7c17d67e356ec1e9992457a175b07546ebe9c13f050026913152d503a45fa83245d1e825bb660f1b7e2d
    BACKEND_MAILGUN_DOMAIN: 1000be16212d2b8189181fe22d95c145db34fc762e2dc8a7e95165787e6ada8e7054
    BACKEND_SMTP_HOST: 10004d507ef806459701eb2b4d42e64fa8c55b4d0c3c1e0f0831ab341155d772a22378d1f1a94338a21bbac739989edd92a3f8ac11d822c47aafb2237acf870856a0
    BACKEND_SMTP_PORT: 100089c9a4623d6ef2513833898c039139caca25ea19a77bac24a3d826387dfbddc6
    BACKEND_SMTP_SECURE: 10008d4a8666ae270c63ff45ff80f8c4f5f24f583ba10a6792a965b0925af82eec02
    BACKEND_SMTP_AUTH_USER: 10005e93da8b60dcb9ff7c6e9e209d7c2204d7e0fb0e9ce7c782f2191da8ad75ae0622d1328ad9bb0b4bf773aef8efa3ad6a
    BACKEND_SMTP_AUTH_PASSWORD: 1000b197f83f41cd1e69cf31de6f279adfdbfd6934c3af7968c8b4d47a5e550b256cea286e0408044301dfd02e6cf5d2fe3542bc86927e8163bd5db08467bbafcb62
    BACKEND_LOG_IS_JSON: 100001350a1871fc32759a4ebb29bf4063283bb9ee1f4f2c3fee8ce95b230ebcb88b
    BACKEND_LOG_RESPONSE_ERROR: 1000432bb6f8dcb689ec4e26304b6fedfa270e5bd8442689a22edadc5f2ab1b32896
    BACKEND_LOG_RESPONSE_OK: 10001ed8d2b8db046e7dbe099a7746982565562ab6c34f8d476d7b9252263668e844
