ingress:
  host: 1000f7e6ddbc3d30724bd5efec62ba171b7695042598f93c5d2a80bde4032dd08de04664507f19a3de7b622d402eb52c8199
  certProdSecretName: 10004b0a6f993f576613ba05c56d85eca35bcf00ec2e91707ae334f0a06b7814f560ea92d48547560e10dec32ea180d4a322
  certStagingSecretName: 10004ac7431c0395c04d45129787890fa3806ece61a8733b9627913570f6aa52d8ec3c4288bfa22302d394c0348f769f40c8
  acmeEmail: 1000c379f0172b8e38f62f3ebe4b50d31159bbf806cf56a66f8c5a81efc99f5b4ec826e15c37a54d661948c2a3e25264228a
  routeGrafana:
    enabled: 1000184939d44ca7bca84437e3c8c115e12ee44f9d574a057b517f11253a123783d4
    host: 10003a052f11835d44ba1935a267683c79f19bba43bbde67db342ae9d545c5ac7fb29cbb16d6d7973e63fa3d3e0998e04811
    destination: 10009a203c807911960f2b7b0447d6f87b4552669ce5a2e5cd3de086bb5b1ca7d935c3873b112614d46523e9e9fb2be8112872bc8a80e439a2ce151e130f48e66361b620f357ff4217512d0df92aed886480
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 10000697a9004a8b5171205c6bcbdb636039b6815d7b7b67682fd966491df82997b9e1adb0e7bfba86eaba944b5938f016ff053fb7fef64c438b1803f09d87b52a6d
    MYSQL_DATABASE: 1000bf9ca3a3a76e95a1b6afbc6eb8a0c5aa107bc229be9be58bd0524c6da98be7dd
    MYSQL_USERNAME: 1000a85e3b596ec94eb52a207fd5c289717a16103348b3ab1b12178b34aa0ccfb80d
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 100091dab18a33ed2e01708aa7fe04d25b30822fd4ddb538cb580b13f51de58a5c2e
    RABBITMQ_DEFAULT_PASS: 1000319dd87c361c31a3839faf86b359dcddafb18cf1fedc4971e2f5a459d97325f82afbd292f87748d0c914341d6eb4b2fa1479604dcf9a5be3de2e5e7fd1bce27c
    RABBITMQ_ERLANG_COOKIE: 100085bc8ec2284f424c83206f51bb5cff33d549d052000dff22ced22f8341a47b6a50f13153c4e9cffebf7be1aa31303ccfdaefc2ccb08d3c042ed8fed6641fca67
grist:
  secretEnvs:
    GRIST_SANDBOX_FLAVOR: 1000475739cf642f142d688418428f682cb9eae8a46d378944d6eaf4aeb8d8fbd695
    GRIST_SESSION_SECRET: 100035b7e5ad8f4b034fbb52f658482eb7f41ff5488840d4c68c5de6123dd6030babd04a73beebacd84ea4544793ec42706473bcff06c077fcee603da3f0d9aac3ce
    COOKIE_MAX_AGE: 1000a0f30b255ec84e9e12e6beb5c82045c90d98dfb4169c5ac3e4a15fe923dce45c
    MPROVE_GRIST_API_KEY: 1000e7d2e6a00ae96fbc446fb3fb27a9b759ab319fc3acb93e85cc0d957ae296f706c4a522db02a355db2a7f5dc7444499acb3ce83e0bc2edfa02ffc2b4728b0f383
dwhPostgres:
  secretEnvs:
    PGDATA: 1000588fc121a9da058e0d339d1a788092ffcf35cd9695c9e7dd95a382ff02a0b19717fb1bd0bdc24ba4e671568a9a5556d6
    POSTGRES_PASSWORD: 1000c80abe672db785b28e03bd18f6b031a9932e19d8574f65e3fd7318d16fd7110c4df31e4675947ce96a34e255e70c822ac75594d51dd547e53af59ffd7e42dbd4
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 1000b1a04be3817c393b8796ce511e5696769d3a3e9980c6a37e1d5f7d428189f4ba
    CLICKHOUSE_USER: 1000ba95294250f8f6e5d590b7ef454bc81aa1e02edaf25cc98e6df4602652e05b6d
    CLICKHOUSE_PASSWORD: 100084003689220a8e7e3da0953745f282eb1b07a5b81f66be1bbf3953bd41aa510e7fe1bf9b5cf74486774a5166f7330a43efe9df699498e2cd9acf6b74c68c73e7
mcli:
  secretEnvs:
    NODE_ENV: 1000fde257d82c04085fb5700ae7b1abdb0e4163a7c2d906ad6d68823dc4bf23a474
    MPROVE_CLI_HOST: 1000fbcc32515149c37016f34703d3c6dd909a6d4e4af6cd50e23f15c4821fa0fb508334e052ba545db3d5b675fc38e9e9fc
    MPROVE_CLI_EMAIL: 1000d8fccc4e45d2acd1e29edd08e1e45d79e6d67c8da7aec18ed502ce16308c25ddbcf35fb976e586e75fcb9e08ee4fe7fe
    MPROVE_CLI_PASSWORD: 1000056574b74e2fd5065828341169c19e7bae3109a9c3c51054c539805e862ced5d
    MPROVE_CLI_PROJECT_ID: 10003fa948a25614a8caf003f3fa42fe9431c34efbf176a1a42c41a8387c53e48bba3119ab8d589d842bc38754a5a0953c4c
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 1000df6862467750bb43ecf5bd54bc95b6fc0db786832db8bb0cf22faa30ec0bd1cb5ffed04de7e3d9b5cd9355272d0c7be29d442657a7abfd5b2848289d0e5e18c0
    MPROVE_CLI_TEST_DESTINATION_URL: 100026d77ac704570458744e5b05548df6370609f76cadf48af338413974a7ff863183887322d1d3d7dece04c9986d772698e20046230ec5ceb801e82c12ca1ed4ec
    MPROVE_CLI_TEST_REPOS_PATH: 10001ef3b5db195459acefc9b7bfd2b14d40f0fd749fff27829de5c6a28067ff73b7ea75bc25d3b98e3f5da07e36f6cd7922
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 10000d207ff9a0315df44da7598c170bbbe5040fce2cee73121f45fe58aa75fe187e5332eda5221d9393f5c81227464fbebc4faaf3fda02f1b2404be60584b9ab5dc8581935e593bd6e3320df88558a02b5c
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 1000c67b4260b274879946209d985aae7968ac4e10dc973e06a2f7f712afa259e5b7db601d2676861725ca1d0a567f45166bce0e3076f2b278d812b48850a033dd6b93de55ddd7344b7c713dfcd0a44d35f01e65440d0b4f6e21464593a86ee72ab54eaf7fb39427c24000069aebd3309e24
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 10003eaf2cd9ff498ca4b5df8175f0b3ff258e1de2deb24b9341f83b13cdc7ca55649dd70ba65c19b2f8bfe85208852708f1ec4c1280fbf1a77ca290e791d3c4a3d3
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 1000e96af4a8211b0778e2fa618629a4e4293fd09f1b2d903dd5c37f1723e306d97191c385c535ee55892632caaa070309a377fc2cb30fc05dc790893ad00151de8f
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 100067e187e007b70976dad21e0ee0c7831ee7fbceda28448ae6b53414458a8c7a0c419fefed3dc3cc08f48a8fc0aaa1bc79a02f77ad4b00279bbc420402b3bd9a46
disk:
  secretEnvs:
    NODE_ENV: 10008fc1aa4bb9cc546ea5a9f9388441cc1f694a0bb110379753cb10572711664734
    DISK_ENV: 10007bd244b9ba9284eb5fed297b586b7d14105df1308355ab3b20b337c899b336f9
    DISK_ORGANIZATIONS_PATH: 1000232ffa993a96f3a6113c72ebd5228198ff5c079d35ca324ff220a2b41eb4f75431d4f163c0a3d7b0d935fd4a9ad4c22b
    DISK_RABBIT_PROTOCOL: 100025f6cdb65596c5bece2acec60bea448757742aab72f0a0079534937c1f302ad5
    DISK_RABBIT_USER: 1000c48eba73caddc695103f7268b290bfdbbfa5568b02eed6eddadcd95ab8ce3b6e
    DISK_RABBIT_PASS: 10003c343d0b038499dac889b2bdce0ffe995632d48ff6ef1376564882f4546cb4c2e0851725dd9221950aa862c733269cc31c5e2408543ed9518258320c0499fb37
    DISK_RABBIT_HOST: 10006df04b0f001d7f38685e899540a5af2fdbf14613dcf5ecbc38553384e17af7db
    DISK_RABBIT_PORT: 1000ec930f0fa112797dc7afda096fec35a1d7be1e46ae033f065727d365f881da8c
    DISK_LOG_IS_JSON: 1000eed5e5c6e140a853307af38073c5242d0e1bbb40ba40532623cbaa8085249fbc
    DISK_LOG_RESPONSE_ERROR: 1000d1d5daf42082a9119f659bf2ead5873f02c545f7e9ed7d108fda9e56dec532f0
    DISK_LOG_RESPONSE_OK: 10006f6a6bea4d9efce0967ec0af5c887097188d7fcb32bfe1f1cdd811b4fd4e60eb
blockmlCommon:
  secretEnvs:
    NODE_ENV: 10009dc9d43e1155605a97325aa07d1a8f262e315f12865bfd1326b92aa7c597a445
    BLOCKML_ENV: 1000cfa7b428625c776a7132b2fdd2529fa3a25936bfdf949276548a8251e024fab1
    BLOCKML_RABBIT_PROTOCOL: 1000934f94d5a93ce0b0ef9d6a77f49cb03e54c7af0294ff2dcad604c55a84088020
    BLOCKML_RABBIT_USER: 1000dc476904b479c9a885e51b936fdfdd6c8d89c9d27fa1f606c1c2a6b3cabefe6e
    BLOCKML_RABBIT_PASS: 100060fb257ed1ffbb5df80bdc60617e06c595c433a75c92fc5887687ca72cf80ce3febedac3db7ab980583c916e6f2afde4052ebdfc0084da06c50bbaa0ecdb0099
    BLOCKML_RABBIT_HOST: 10003fb9877baed7c83cc9c6da511e12b15d6a65d45fa62273767ff623f286bad47f
    BLOCKML_RABBIT_PORT: 1000029a22f0aa53ef6e1daa84e34b50e60a0434cc673153586b8c467d991ead2812
    BLOCKML_LOG_IO: 1000ddd039c3533fd4158e3023cb59845d9a29d0f48a3b57e13721eb2236b6e5d151
    BLOCKML_LOG_FUNC: 10007d6c04c6e382cd37bbd94213cc6c7c5d1c3b1c9904917f1e41a1353c59d36999
    BLOCKML_COPY_LOGS_TO_MODELS: 10007a0c2ebca646bb48967f8e7e96e3192b02215cefc00fd1165fc4ad049285eae1
    BLOCKML_LOGS_PATH: 1000ac5b2c14c8d4d19626e766c4b13d467c7bf8ead5013f019c029ded1ed4e28e2adf57308d64579c17c93de3319be21dee
    BLOCKML_IS_SINGLE: 10007982fd9f19e8ed4e6acffd2970f3a6c6d110b83f0efb6bff98ca85030cdd965b
    BLOCKML_IS_MAIN: 1000854d67ef95d9f83c77c675cd39fe31818b447ea7799c087e99f6456dad0b177f
    BLOCKML_IS_WORKER: 1000e5a26b1dabca9dfe44f25c73a130259d825fdb3ef554f182c75fb539846fd77c
    BLOCKML_CONCURRENCY_LIMIT: 1000544ee570bec14e83fbd84211a509f36b6a0bb32f0fb4733db56386288ebdb856
    BLOCKML_LOG_IS_JSON: 100086cf3e6e7e15333bc6f6eba2f2c8627e021b3e6a003e4b186d09db8cb04a5742
    BLOCKML_LOG_RESPONSE_ERROR: 100032047d6f1f28d763c91d46f3b738b4941f8299b1286e3e4c99bd6cc15ce48f1f
    BLOCKML_LOG_RESPONSE_OK: 100043263fac661ed2d4ef806d9a96e928de043275cc100b8c070462ee04d5a72726
backendCommon:
  secretEnvs:
    NODE_ENV: 10008dce29db9f6f33ef4d4618c3b7aa5632619663222a3010c683eb16b48bff69cc
    BACKEND_ENV: 1000cebd4547894bc2e5aca731d71399fc25d61c45ae1e65960898321ae831a5cbc1
    BACKEND_GRIST_API_KEY: 10001e2227a7fc850f8e69280a0bc0ce95e38a3caab32c53435ec6ea5fc3a06a013d12f965f6a9cf4a0b5ad45c284b2095c8dfcad37afd29d164a92687ee8a4b2e10
    BACKEND_MYSQL_DATABASE: 100008fb50806891c3f22643f3e0a14f399b5e55827fffcea3e14334bd1ae246cc75
    BACKEND_MYSQL_PASSWORD: 1000a9bbc955a7e49f5313cee7911fbfc7d27addd0a8b1efa584baea8f52ffffbbef598e69b8e38a816852a60708412e90eb64a29edf270d9669c73f929ef664bea1
    BACKEND_MYSQL_HOST: 100092ba9296b4716d839f99762dccdc2f48f99721c801deddbd1f14bd6192c875b4
    BACKEND_MYSQL_PORT: 10008635b68adf9aeebc5576e95d39be8449cf9b1d695e78a23b39860c3b1f630699
    BACKEND_MYSQL_USERNAME: 10002697a32885ccf94eed28bacef87a19897fd15eed0f0e866edff5de2d7ab25f8c
    BACKEND_RABBIT_PROTOCOL: 100070d3eed504515c1fdae8a4efae522d804b151d4b37fe7971d57332fc937c1636
    BACKEND_RABBIT_USER: 1000783319c0609bde1bf913a52ef9d7ad4c1deda9185b06f06fb6ee700cb168eb81
    BACKEND_RABBIT_PASS: 1000aa5a05a3e622afc048de3bbe4c7e66a46b4e3031a2902b702954f20432fea33042d1032eabe90c5dff54e9f5191acc01968de70849d0c3e99c4a31c120008a65
    BACKEND_RABBIT_HOST: 1000612c1c25e1e0a2ef3751bdfc3bdfceb5ac4d3e7cfeec9113783a7cef5a44f345
    BACKEND_RABBIT_PORT: 100045ed843af5ef66c73e4b65796e693904eb38bc0d0259d6392fbbbc328505187d
    BACKEND_IS_SCHEDULER: 1000462c8a4d0b79972b244392d79240bd2760c8ff60a2e797d2e1c6f0b6fc8895d8
    BACKEND_JWT_SECRET: 1000df64c6be8955b621b4f7f7f11806c98db46a0ae2562e330ecfca402b2b253e959f794011751c2a1f89033f7679196e2cf77d30d7960934d505ead67653b2190b
    BACKEND_SPECIAL_KEY: 10009b403192c3db676abcd263ef17a1116bfa3035a06682a26676653e509d4c4f52bf29907452d988a80065101b8ee5dddce0365dd37a14d69ca60429bea77d5848
    BACKEND_ALLOW_TEST_ROUTES: 100003da9963c1538d8d2fc98d968ad6d09831ee0a78d7149289884435b61fce7a51
    BACKEND_FIRST_USER_EMAIL: 10005a45973b381bcaa48a433a467aecbd694cf5337b19f298542854d478af1e2a41a222171df4d155a231d65deb1b318f0e
    BACKEND_FIRST_USER_PASSWORD: 10003b2fd30a17ea187e1bf63c75eb58836f504cfb06bf86f55fb7b9683db61cb3f8
    BACKEND_FIRST_ORG_ID: 100019db54739328c4d85bb401ff654df01e73439d99423d252fec86b8d41ce864dd6139b10eff9526f4aaf39e465fd6f6bd
    BACKEND_FIRST_PROJECT_ID: 1000d3b3c4507d8793f65b11569febc580390e0828610d3ccfa6d92600ebea37462463c70694e847fdcf073d2e852af05bcb
    BACKEND_FIRST_PROJECT_NAME: 1000ad5c86ed1111777fe9269521d760296445929a66009b9b0d9e42ddc1f4135d8d
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 10007bf1840bd973b01008b182fcbd4ec6d0f8145b6e337ed4b07e0c81ca7bae5748
    BACKEND_FIRST_PROJECT_GIT_URL: 10004dca9bb4b280e54c091832d0f7417611697d0415462a8f5a8c9f7fa8ae99ded14cae338e23426d1116151b6441ae752406befbcffbb42537b8054625640bf0ba
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 100055a17d216ad25153469cf86ed7b92c07a92f70b89c4c44d31be09c75223085bc3168129479905f9b4fde49b125c337000e66d431940f87a6f4360b575cc1d96b
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 1000eb100fc12f2df4efd32f2e839954d68d7efa1856494cabb7d7a56ca979f6e7e8e6cc97f5717055ed4c39b2fa2f15622e2a94bbce27f5c9d9c39f2f8ed4b3bf96
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 100043f16594a6451533a23d1595e1f4fbba2c84a859e96b58fb0601b0f705c2afe8
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 10006ad896b2e9a3b42c4b368963cb7e5b845330c278e686e9ede13fbf612f7fb10da3240b04a4e506b1032ec0ccfea111058f27bd95411aab7627ea1164e141aee7
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 10004f59bb111afa04af46e82a4279158b904691a41d449cd570a8e94782d9ddd286a8b96f06938b829a9f8103ebd898c54fe9b5091fd6287eb44ae0c67af67345a8
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 1000029ef27d01daea198d686e9be4d0112bdb5f52a0ce8d957158f86e495e48dab70087936dee70744815c43cda4a42dcd610f246e43837e176ef1f9b93ce257f10
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 10003c842e709a3d71304e8409e027bb7ff472a512bcbd9a62cad1ec93b8b88e31c5e2f00da393b2286c91981e581ed8fbf9
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 1000ca6f400ff2b7de5e08c12e8dab6e8fcdbe9ab34e5ac87a53139c30d00e091681
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 10007d12f7789ba78166bb294718a81f4ecd0d7c6dd44f25a2ca9ab34ad75be6d237
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 10006b8018a3260f8d99ed25afd870fae30e735dff2eb30b9259b95a545ee6a3de224fa5717658f1ccd150d8b0dea8f6a88f
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 1000399cfcce3bdf56fc5d9c3542613934989ff7d3e382542a6a84716d5531171a64
    BACKEND_REGISTER_ONLY_INVITED_USERS: 1000c46131a1f74403c96fd3dc0190f6c918e7844daf91f78c4e008132c0108c7bc9
    BACKEND_HOST_URL: 1000fb6e2812f128a9d39366d89da79970537a35a9aba826b2322e85c3bf60752e525d10f75281f1202bbbb818d22f6e2b5e
    BACKEND_SEND_EMAIL_FROM_NAME: 1000f595675a0d4accd4c3b58367d762aff374bbc2e29c16ef522423d8de1414c205
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 1000020fdcfae3b61244fcb8820fb0e48b139edffd5de6000a7395c3ae017244c163ae2f3a845e846c2618561f5a24efd8ea
    BACKEND_EMAIL_TRANSPORT: 10008b473608a055fa392d44a4cad44b72883b648b2d3c918cbaf9da6cf2ecbe0999
    BACKEND_MAILGUN_ACTIVE_API_KEY: 10004f9a3a0bae76e4f407cb5a9447bec347e7205280a0385392a683d2c1a5a55607266c6708a3eb9a5a5dd9bbba09a5f80218e82943d0e813066527b85aa0caca59
    BACKEND_MAILGUN_DOMAIN: 1000901e5c6c056c800bf1bc935888076e8d278941bcf188ab853bccfde7c17d1043
    BACKEND_SMTP_HOST: 100018a2a3a3dab1d9d00bc91be6b134df66ec3f4dca1771f95d65505199550e540615a2679dcb449ebfce18578cec1e37bb8ab54edb1bc811318747acb49b559d5f
    BACKEND_SMTP_PORT: 100001357578d9cc1d128765539d733b7018ff6844b3ce83744f4b03ab9ea1b978c4
    BACKEND_SMTP_SECURE: 1000bf6925207c47062b208b688b7b726e014a978d20c6730bee1d69ceb35e61d7ae
    BACKEND_SMTP_AUTH_USER: 1000677a2c231583e7ebf5dc3ba424d9370834d11606ffda124d188e66bbe9facaec32f9094d07c3858e880cc66927ccb41d
    BACKEND_SMTP_AUTH_PASSWORD: 10007add7825d4a4522e21f3a2e6a0f270aebe4177ae81f8403584c1dfbdb0c96b887167160a666d4f5400f3c7f75a2fbf4c4823c1b06365bc38bcfb084ea514a6b5
    BACKEND_LOG_IS_JSON: 10000519d350b23978a136fd960af879288bc4ff1f1b4b75eeccfd36d072f7430a2e
    BACKEND_LOG_RESPONSE_ERROR: 1000aa63f13ef5f9dbf3f65ce0ba69d4603d7dca3d85dd7aa708dbb9f7af5d440a18
    BACKEND_LOG_RESPONSE_OK: 1000e9ec641b1b5c7cf27b12616dadac5c9cf76159cc4ce5b8c7db60fdef7a61c8c3
