ingress:
  host: 1000082116035c2e4b51c03327c4ca2536f9b791401acc5d93f6177eb78b489024d31b9c27de2de98ac15d39e2222996cd34
  certProdSecretName: 100016b38aeb3081373c2d2fa00c26712be618f6d4a69f40b1f409c20c164b1a5382679d2d787a0b5187543ead792dc959cb
  certStagingSecretName: 10004c6420eaa0d51eba3919a6a3ef989c602f62519f782be8157937015de0f18e568e9730adf4e6e13580739d583d8bcb19
  acmeEmail: 1000ab4459b17797dacf889fb4176eb30db922dd9bc2211039c225fe428204072af55de6e89237551594e2d41e509bf6e033
  routeGrafana:
    enabled: 1000b3982781895684d6405fe450b7c423a517484771894a5b2e23016f9a9198a17e
    host: 10005938d4f947e748fc7f4e989dd0cf5d3b08a23cffef81983a125c288e61af02504b103859ddc022a34a71378583f75abc
    destination: 1000ad67a38f56bf09c7c1a17297e8466623afaf4aff105fdbd25bd04338f5b12a9e7a4410bddfde82afc961cdbb6602cf194a26872e757bb22cc1148cc78066d8f3e4e975cdef11b1caab93bdbddc5cfa79
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 10007a567f7340a3edddac44684aa1873cec8be52a91b5fb493dc3492de21f9825ce4b4c0cfa23080d3b05776d7b7d29a151b81862aba16c129058d8e768418d24cb
    MYSQL_DATABASE: 1000ff7e9589e775b28e27defb5469dd15aa03062ad2890ec4d624b2c8199ef5fd9b
    MYSQL_USERNAME: 1000df049370cbed3c4967a0f2e4e6ab20c36a20a007d6523cb365e4f16e41270332
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 1000f92c00eb56ad10dc619bc3c97c33765d87c1dc54cd62506b8b5a23f676d0752c
    RABBITMQ_DEFAULT_PASS: 100047c69bd3179ad859a8e8e0c0acc3beca92d388ec11c7ff19ddf962019f1ef08d86072b26c77fe8e4bdc8065b6b23604995a7e50d247c8cc1b9319e75dde1d5df
    RABBITMQ_ERLANG_COOKIE: 100003bb7ada3d4e2afb31592229859286ef80b97b901a940a7bdc01a98212b7fc723195e6611e61b8b90b8ecfde657d9e6f76929afaeeefc94258e2bfa66d48d091
dwhPostgres:
  secretEnvs:
    PGDATA: 1000b08690e3b883ccc10857b4514ba88ea21c198c81ace4af2ef2de90aac496a8f7f665ffc4dbf181b9b4f434e373ede8da
    POSTGRES_PASSWORD: 100093e537da3f4f741a08c1e02080b86d939f9a94db5c36647ba537e2b6f55f88d0aa661f574d199671d2448513c081ba7c47ecf72f3e14d8b503b17c1676e37b28
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 1000df8c224a8e1e98ae759fa8eacdbc9db118c7baa02ffc59cbc2b11c8269a644e5
    CLICKHOUSE_USER: 100005de04c1dca31caf11b9280e1cf721f1ce3690a4bcddc743799b8ed2a286c836
    CLICKHOUSE_PASSWORD: 1000d85b16daba40dbebb27470e12f1501b84c900af195cd0248e00347e204ea797b0aa2d4ecb6918ec3c0eb1951cc94062a02d23515e74b18d4c530291135817f0b
mcli:
  secretEnvs:
    NODE_ENV: 10001e4fe32941984ed3525ee0382b9c5d5acb70a359c7891032a2ef0eccc03bf4e5
    MPROVE_CLI_HOST: 10000043c71b7d7f78ff67d2cb4723cd5869689a4e0ebcc4d4acc126c1a7e78c4c272190ca32bd76dd165577aedbd4fe95eb
    MPROVE_CLI_EMAIL: 10001b64a53b4e3707c77e5ea60567c43d506b7ed7724786319712dbd438481dba093e72210903f3510247f209dc4b395389
    MPROVE_CLI_PASSWORD: 100011b03b889a7c6e603a6489798461059f8bffd64b4e6ee81d0f0fd625d5c09698
    MPROVE_CLI_PROJECT_ID: 1000976cd8563844d6016d9e3505e13e244b79bd35582037b007744ebead8a19d9dff1bd6ee3159a42426c51f2c150acf330
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 100069777edbfce56ff9647caec275e76bfbe01ceaf5ade37aa2b99a2990fac82afef60394f122806a2d19f4ca249f88d95d8e951c3f02acb08c4f4b07f4888314ed
    MPROVE_CLI_TEST_DESTINATION_URL: 1000e6a284750981924cf68e0ba68c464a41081bed5eac705254bd9c7bb400a57482b8fe8f18d4472d048ac0004f61fbec9263420beece5a4e934e65d7202c0c2900
    MPROVE_CLI_TEST_REPOS_PATH: 1000434b91376a19fb001e5e487a2a17b0e0f49618b45d5a216e4c3f01b37cc933cf9917d2e5c15cd2e935cad67373c24a42
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 100041a761a7aeb9c2d192303860a8f6723cbf1742b8685548ab09cd09ba1b118cb7a1d644ae6ce15811154407d5e9e708261d4290224664e9b491534696c46794ae
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 1000f8df507283176a43b53fee1382532ef279a6414c81f7ebe5236629ae6fda7b696e3ddfaba06d9491858d478d1649885ae4bc80e5a5c6898b3189335b679a42c6dcd6d3ce0139c93a28cbcc2817ebdb0eb17c04eedd3fbc0fc46b1838aa9eacee6bed520739e997c2911952f29bd15d14
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 10001a27d82487a2c23b2a3e72afa223747ac451f5e115fb0551dc811b166d2141b6d09c3210b98b1756099aa8599f25e54b15859ee3b84b5d4b26bdce41e6076804
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 10004aff26d5f0d2c5353293322df315940ff2209d9525be9c77a1e7ed5470803faf189f0e70214ae565a8613f76d0ed312a80a36386c7ae79d66bf8cbbf2ec05487
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 10009ab7a4139b1ed0084daafb0a96b4a2e278b53559c2c1e3d5a5e2dc0bffa65c6fc0d939b175e4793ef36cb49739a52eb764beb312642ebc095f99e55131b2d163
disk:
  secretEnvs:
    NODE_ENV: 1000a25596dba7619378d9e42362bbc6446e218b0a6df0e21447e6aafacbdbf03733
    DISK_ENV: 1000e5fbb9c53db8b0c368aa2aa0db0b130e3ff1b4cb15a9ba8b55b4af04f581f663
    DISK_ORGANIZATIONS_PATH: 1000c30e34e9dbbb44eeef1b523f418d2f3a53a9733141c3f0791f76264009a88277949f4607cad30ae8db3967160d2173ad
    DISK_RABBIT_PROTOCOL: 1000cbcbf42ead19c319abf83400657dbf8f71c7bb950befc54e9d01955a70b3d8e7
    DISK_RABBIT_USER: 1000a69a1ef04f8c2b8e200b57473c4313f7631d298acfc84cc71991ad638d2a2912
    DISK_RABBIT_PASS: 1000a8913392226790a56e2832777161c04f4f4b933cc9dba93492517afb6c419f1b953d07d7ce94d9be2dbfba67893bd2b51d716977202ce1064ed13a3a4f74c2b9
    DISK_RABBIT_HOST: 1000100e17f0e3932ed1bbc31068d4cb004ca841c01a286c46bf7b2f0c6299af0ff1
    DISK_RABBIT_PORT: 1000a832762c11ae1f3c612c648205e34e9c10995e4a257667f254f5c3c0ca218215
    DISK_LOG_IS_JSON: 1000b2112ed124665e824cf44fe352345fe945b588b1a9793b1e053e9026538550c8
    DISK_LOG_RESPONSE_ERROR: 1000d5b94b90b7efb3f3d2712d2a7e1319ad58e20a813ebb3dc5c48f5c364041c700
    DISK_LOG_RESPONSE_OK: 100054c92b86176bd4c0a298244adb0b65f302fcd87ecdbbf9c4666f56116241b3fd
blockmlCommon:
  secretEnvs:
    NODE_ENV: 1000000730d8f60cd70f1088447ea769cfafbb85726067cc1d1ca18e3e5e499358b6
    BLOCKML_ENV: 100066e81651a499238ebe67a70784da0b01aeee3b6b979499527603e3b679cbb508
    BLOCKML_RABBIT_PROTOCOL: 1000c0cf91dcfb605d90f7102274717a7ed0ec6f39152d77d23833a156d48f0bb8f8
    BLOCKML_RABBIT_USER: 1000724e00cfd5752ff681579ab09e327df72c27adaa15a095cea586045d578a0a2a
    BLOCKML_RABBIT_PASS: 10002a723b05d4e25df176f699c15bfdb0e7ae4c362e39e10dd9166368aac99353ab6568ebdcae2ba2fd2b44e8fff298c10687b55bab1b964c58913db080630113e2
    BLOCKML_RABBIT_HOST: 1000ed0ea1df834883ceeef761749537a5ae5367f05331c073c972c765a05e2534db
    BLOCKML_RABBIT_PORT: 1000d406da873c1b5e3bb275bf8ef7ef53f4756fdafc71c8591741165026bcf0afcd
    BLOCKML_LOG_IO: 1000bc62bedcc2ee2cca1a47709ffbeac110491f988b1b649bd2497fad9d185f7d2c
    BLOCKML_LOG_FUNC: 1000503334f412e2cf30dea49fb40264bac748deca71b212af4a59b2a4cd182634be
    BLOCKML_COPY_LOGS_TO_MODELS: 100091ee0b7660c4234db7284f87d4de8eaf214485c2156bceae293cd61a3175d60f
    BLOCKML_LOGS_PATH: 10006e01a59cc22241658e8e367cb6e4c1ee15b37e7858cbd0f33718c747ccf552f8cb5ccd395cc3576d0175bee7378accb5
    BLOCKML_IS_SINGLE: 1000f10159d72ee70c6efada9979a18e1c859f5d1fabcbceb4a1b461a447e0d85cfa
    BLOCKML_IS_MAIN: 100014558923d5cfa54a822185b80d9d1ec0e8b5317a16b5f516e20fd39b59ccb981
    BLOCKML_IS_WORKER: 1000d84e1ecf4c5dcd1ca77109f94415d65a4448c5a9713867b7dc8d3211e5e11c07
    BLOCKML_CONCURRENCY_LIMIT: 1000f34296c478e9be44ee9ac8a513edc8ea9c679af1971609d87026aaac1410f288
    BLOCKML_LOG_IS_JSON: 1000223a7edc3f876fb77e9c8621e0ad4a14f8cc97deac8f406130881d007ba8d5e6
    BLOCKML_LOG_RESPONSE_ERROR: 10005885038abf8c721fe21a5ae635a34b91d3e215615e691b55689a33f1e3828a6b
    BLOCKML_LOG_RESPONSE_OK: 1000935c54f7e9c882930a39e20b2672282aea835c48f45c9fb56d2f51030d9dd543
backendCommon:
  secretEnvs:
    NODE_ENV: 1000c6d8b14bac74cdad3c4b263a2120ba350783f49d7359e6300aebcd46358fdcbd
    BACKEND_ENV: 1000f805bc93a175bc7e9c485fc450eb27e97f0224b962084636882110890c2015af
    BACKEND_MYSQL_DATABASE: 100067c3317f84c40d91060f8207689f331f5a5ed74464161941a8e5c8dde8a430a5
    BACKEND_MYSQL_PASSWORD: 10001c140e3dda8258fff2357b99a2e0fbd2b6973e05b6d29425d586450e18c9d72fdee19db012f59a83f043dde9ff5a309181f76c140dc87476e88bd4bd1d29d204
    BACKEND_MYSQL_HOST: 1000f223dcf7bf49ca90c2524255e2ccce1feda5db35b0af47cbe711db16d72f29c7
    BACKEND_MYSQL_PORT: 1000eb43e73636bc455b8f9f2d786c96e5faa0a0edd5c382c9d820493f72e26980ef
    BACKEND_MYSQL_USERNAME: 1000ea46ec7b652e5699a1ed85cd1a4f21ba6b8b2ce15b20469bc15cbf6a8b7288b2
    BACKEND_RABBIT_PROTOCOL: 10000d11b80d596508dbe902d0f2beaaa34950fd568938f561e2119358104a6699a1
    BACKEND_RABBIT_USER: 1000bb5ca1332689241e364005c6ee9549389de826dabf66a4b22f085ab0cec55320
    BACKEND_RABBIT_PASS: 1000081902866ad6650e5aad0b98cd8e4e863d7d3506cc453815f95f85565d6a03b2599eb5233b4ba7fa46467b27e065421b73177e1a4c9173d5beb0191b60c12d93
    BACKEND_RABBIT_HOST: 1000f8f473e97581e8ecf0d750a75745bee72f01b4f6913d57c9db0567dd44d36266
    BACKEND_RABBIT_PORT: 10004eac003722b162a509845b3fd75c440f9743d9f5acf4214076f014a05a962d38
    BACKEND_IS_SCHEDULER: 100046b060626d56a7f5d6eab3d0fa839959da25fdaece3ddc744cc4317b556fd0b1
    BACKEND_JWT_SECRET: 10001c001f99d9ef47d16d34b71e35ddb879cd5f14a2341a411335ca66277be36cff75559283d3464c92455863c09b9f10a21b3523e4f2d9498fe56d5e59ada1e2a7
    BACKEND_SPECIAL_KEY: 1000c20c5cc73702689bd6474b882d0f1ca9ea5a5a54de05a83378a91f0fe826cd5b6c68525d33e9d847c7dbdb215c03dbcac251e65fd95bdbb327ba05c1a7366915
    BACKEND_ALLOW_TEST_ROUTES: 1000a032de1a0534fdeb5820a4a137d4410a3e4d392921467393fa7e244f7e3e51a5
    BACKEND_FIRST_USER_EMAIL: 1000f21e51a40db2b0e8184222089fbe44f4a9938a547e0a479892f7a22b2e6f3526c88edd53443a925fac527444676b0e6f
    BACKEND_FIRST_USER_PASSWORD: 10001c353a318837bb3fafa61941cb75f20391fb46fbcaacb78ec03945de67014f81
    BACKEND_FIRST_ORG_ID: 1000c335c3e3a5402640f397713acb38c2cd5d1febf4b8922b76c0973e5d1b9417a87491b4bf3518bc1fe05e16d6b73988b7
    BACKEND_FIRST_PROJECT_ID: 1000a4059d77ec7f4dadb489bb9ea8cabf8857285ab48b9e214431b5fbd1c9c58a93e9165df8550843b73641191b3ae75f9b
    BACKEND_FIRST_PROJECT_NAME: 1000cc37a10d97f1ddc18243b5fd856ce8237bb9535ae7cee937afdfee3819f84ae0
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 1000cea962509a4fe654880a8926905c5ca81625bc25cd6c58d7fda8c7ce1756edeb
    BACKEND_FIRST_PROJECT_GIT_URL: 1000b8f3528eef7a407b2eabdd4a0d527ffcdd9f1d54b24e76439c052c940ede61745dac22fa4be896aba34b555aa6ebb8421c0915517b06639a58f4689b3111b930
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 10009b99a3a327318fb858148ca02b39e146013f5d8f6b7db9e14ba6ed987fcf676c4c22b80c0154982bc238a8fe1003e8904090372173e23366ca6e8525c5914e13
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 10006fdf3f080fef8fde546ff8a7c4509c836426677e2a6bb1e59302ac8679e24602fb3f4ab844556c7d9d6cb37a64c8c3c5ecf67c9f273d822107d4941d34e04a68
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 10004c6e25ea97118faf2f292fc5f24ebc2b85d407a5e6b4ec361f27f14905a9d1b1
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 1000f731dbd0855adb37178f30e82c3b03253738f3fd17f204d27438b273f00ee0a93d92edb106b348d9e43b9e256f598f7fc32f7af6b8bafe63cb42b9342a0c8f93
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 1000608238bd3bacfe6785c5fe363d1632a2af426464cc3140cc77c0897713b8412c00e8b5fd1d13f406d2bd4b35d47635399d7cc84ea2fde7bbf28e59e0d37536b1
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 10004dc5944262108511e7a82a316d5f00e8bc0479a900a33cd6b1c3384be518becfcda5ee059d94469ed7a7201b5e9ed38ed27a4c7c4190ec28565b21af174e7ac5
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 100023facbf7dc405e627fccdefd1c05f8bd6793f8927dfa8b711816bf35d6a720247b958be8ca899b847f83b65e9048e2eb
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 1000efcd8290f808fad070420447370f3cd7fde68c3a2397dfb81dead409a90b5cd0
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 100078b9823461221f7ea923a2bc0012aaf5f53b682da1a5b28f54735227bcbebc02
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 10004cdd8ee56e1b0ac4d109a902491e6caa858712bfd5c59fce022d1cff900b1401f08157f1578294d3731bd8436653a33c
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 1000e68204b1dedaa48c2d722fa84d62e9620825939a3f65018ad4debdb725ef2db3
    BACKEND_REGISTER_ONLY_INVITED_USERS: 100015cf8e878481739d71429980be192f1b4ab303d66ca9d4bb3c0fe61c63c3eab1
    BACKEND_HOST_URL: 10009c224879d064bd32e4c1f80246d171ae9fff8b1fea00b5567629d7a975162f04b4c8a9a6cba2aa420f2cbac8343a1ca6
    BACKEND_SEND_EMAIL_FROM_NAME: 1000805c2d0e09f2de4adb67868cc962bf9b4e352ffef8a32db143d385a70000c767
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 1000fe79658b7d8e2e995dac47cde468d95af3642c8bb81d01841ab2c868a73576388041e22590cd50030850ac71b10121e6
    BACKEND_EMAIL_TRANSPORT: 1000401502dbe3ae0fb053af43593221ab1b63c923daa5518abeea1327998c9ea628
    BACKEND_MAILGUN_ACTIVE_API_KEY: 1000193e30869c1a190c44afa49bdd1ca509f3c47db9176c3274d207f8b61f259a87196b2b12cd4cece42b7955016f816d15a577f8b76b1ec48aabc445b005e8b845
    BACKEND_MAILGUN_DOMAIN: 1000e3c1c70cd65be37e36108e314b4797947b51a7cb62296d09573c619c2765f50a
    BACKEND_SMTP_HOST: 100017c88f87822461ac20b922ff8852a5d53bc5dc089d6b54314d1319ee90683b31db9a0f8976ef9b8c24f327c21f3a47b224e2c7e68855c8a935117d27a0cb7464
    BACKEND_SMTP_PORT: 10008409b3643ddbc63a4415c7d006f2a4bbf31081c9a4ade6a52282583f94785903
    BACKEND_SMTP_SECURE: 1000575fcdbf283e8e4ac18755af7236653ee39c5d732f5ad8f31df581b84dbc21b0
    BACKEND_SMTP_AUTH_USER: 1000d96bdb495ad44a487ae3de6d7fbe6d254b70afd51bcffdc6cb706d898a4734557220d08165a7fd0f24ebed6e2c939a61
    BACKEND_SMTP_AUTH_PASSWORD: 100065b0da3ecc376249f182811b5c83efd842a46db98f83cc4ed85a2a1dcd5571d974c3b89dc50622e069922cf5c362747880fb9cd7c5b5c84227ab9f0286924968
    BACKEND_LOG_IS_JSON: 10000b4fe05859de1a49333b40b1313473805da4e16ad562a82e9f6fb6c7d822cd54
    BACKEND_LOG_RESPONSE_ERROR: 1000b00788288d2c878357e8046494a9adcef981158b349e351d7776be0b908aca4e
    BACKEND_LOG_RESPONSE_OK: 10002c8ebccb447354f4fd2e298a3826dcdc8f2fd2b4f6168496595238055b8028b8
