ingress:
  host: 1000b77f48f11b679963e6a13fee7d53f334b986739f893c148de15468e0c594687aabecb00fa85b5e1dd0bbffb31253a23a
  certProdSecretName: 10004287aa044715ef9dddde8b884ff116f5e0c2bac452ef109323271791a8af94087ae93f3a6df4f9088abd3cb08676bd8b
  certStagingSecretName: 1000765885ff218fd6f7c729ce0c5d6fc5fe1ae80e843da5c64786f25fdfef3ae8412b3bde9e566f43863b5f15d7915996db
  acmeEmail: 1000238aaf9d1e55ac60c3c0116e75bcc55e11c6e7586599d3ae72c96c36c7a29930a7ce049f8d847e077ca6f8fae62b6e38
  routeGrafana:
    enabled: 1000f197901352d79a36ffce61ff4d44400ae9bfa436477ae32b509e1b05a230a436
    host: 10002c6b1a92a1a7308135fad7891c326b293364c0a3225d832838e95074446978c1a79a8b3da47563bdc51add740474866b
    destination: 1000f027f1e72c7d7dd526376e14ea73702b553c57b0591a74c73a663351c14da594431518c7d6f0678d86388f8e13c322599dd8cc0a5171e05b9d8b863b8a2df7551e9b27e47e828303fc4b6909ed54bc75
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 10008ea5c7cccc57712b17535decad341fb0b5eff2ad6096943f8c7d19ef832893fed9d2bcb12346f66b10cfe9ca030bd1f36bbefdaf39aa2c648c1641491d79d98d
    MYSQL_DATABASE: 1000febe41c6c3c8a663a535b7625ed82b146448f017b6d421a51ee8ad595c596f9e
    MYSQL_USERNAME: 1000816aeeef1da06e6fb5e1c36b795a34b341c2cfea0fd56c3313e7ad2971508a55
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 1000d262a2f8ef2beb36622738f6aceb4eb6132c9430bde502dd6ca80a26c4100000
    RABBITMQ_DEFAULT_PASS: 1000daa6bcdf1793d966240752d279bd7e14a0cf99a22bb586d7d9e67cb0249cfdfed02f769fc616122b9052be74631aa63a128dd4013c8131310a4d278a980d2842
    RABBITMQ_ERLANG_COOKIE: 1000330c4dcf44031ebbbf17b2e459b6cbc832cd313bdefde942e18e242d06355c52b9eb84d98820afedf0290f95041f635b615cb4e867d1d3498ed4282e44d5eb4b
grist:
  secretEnvs:
    GRIST_SANDBOX_FLAVOR: 1000c81c191acd15920cea23cd7dc6013df15850ced2ecd6be910238f559ea7d7ef6
    GRIST_SESSION_SECRET: 10007b074429d3679aa011ca98465d8ac3d585c77f186ec1138ddaa70b9baa60951e4b2af640108fe44302f22d21c4d38254d4d0f9ca10ab77b16054d9b721f19439
    COOKIE_MAX_AGE: 100009aba926bb07d53c95c7b6049e84368ce61a485981f54083327e5792481b1a6b
    MPROVE_GRIST_API_KEY: 100002d5588b08da80d728509732f8a872c43cdf02e9bed2c76fd85eca297346f4c085fc450ca96ca35c2d3b803d9d8c578bb1846f41eeb7543ee3fd32befaa717b1
dwhPostgres:
  secretEnvs:
    PGDATA: 1000dbccce1e4afa8bb647158b1a9d00912e8a897678d53693dbdc1d55ab071caf596798fd3d542052377cee5dd00ff18396
    POSTGRES_PASSWORD: 100098a398afb3cce421670bcf9b1a38cdee532b13418fa1e6b9a976c3ca8281f27dc15d164dd5b84f919f1efee7cc5e638d50b2d470c7e02f08124c8af8d7b93c7c
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 10008f6814b826467d6a439b430bc513cd450d0d25215e1401c4b86a4b74e1b6af2a
    CLICKHOUSE_USER: 100057ea995eb4ff7da6a0f6ac7e50220980d75e25f379d1c492937b151d0a000560
    CLICKHOUSE_PASSWORD: 10008b11e416ead7a3f79772f7888b1d541847da2dfa33155fca19ba40cf7521f6af26f8a350b17d9164acbd911f088eeb2ac69f3949b7d35161a68fda8f45aa5b35
mcli:
  secretEnvs:
    NODE_ENV: 1000e81cc62caeb196242c6fb10ee509b0ab1a467eae90e7cba40b3e424ce63e8766
    MPROVE_CLI_HOST: 1000b8c4a0e9e3697f21648ad4f6ffd298f3cc24277a4889a4c7dec5f96cc5d4f6a96b654420bdfd43b214aa7ae6632e438d
    MPROVE_CLI_EMAIL: 10000f443e893e3a2a0c257a5cb9c2f1a6c6d7c2b93880d53eea3c5d3db27676eb094ebc4eafa6b650b9613b2ff39a3518bc
    MPROVE_CLI_PASSWORD: 1000be13db08aa45b567bec778e069e7dc3bf21ccf9894ac7db3eb7151dc1d1745fb
    MPROVE_CLI_PROJECT_ID: 1000cadce686bb55c85fe3d6f22bca559b82d1f0b482193a8e5ea40b5e96ee584bc8501be238d6800884e8748479c1d31d9c
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 1000613627c23be4e715c11c0e4f3f766fe71428ba38fd0396f4fb728e375930f40210df679d31f06b52d8b196369fbd6917ca7d90cdefd49f0ee0e7ee8ff78869b8
    MPROVE_CLI_TEST_DESTINATION_URL: 1000b0ad6d2fc9c77d70021c384c7a9845553df1eb7843a9f4078cdb7707aae5501de7fcee1e25d41f50da510d388d5927cc0df03c4920747914b72570d32eccb617
    MPROVE_CLI_TEST_REPOS_PATH: 1000ad4fd780a963104f1125fe3fbddfbc610d04ffd000bb65c13834376e02499326d5e04bd51ecd758f2b6d82a1073d1f81
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 100080b71e1ff412a62534bb4865b28af8e4539971602c92d52e578941c42d09ddfd3153641f578aba553c1bd954991c0517cf5315cda2aa6290c7d89900f7c6c154eff24df6edcbe3765a3a72ac5205af54
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 1000ea46e1ff72eb6e68e3013670616e52a1bef602e458f2b0f7efc84f29b09e8d042922eca5449195bb6048114feafcfcb154c3708fdb6d19b2785284f70219d573d2054b0f111c4914883810f22a6977be51bd9043293e3911b01de10dd693f98991dd5c51c347141e5ad1d2089e5b3d86
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 1000b14c109cb162f623c8aae857964038fabf0e9c3ae24f70ff0096b3d530d4c96dd0ea15d075a92e67aa75688bfaf7a0a639731eb383f9d525d1a4d99c6c8f6bc8
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 1000d6b2e04dfe35d16ff9a8cefbdd0b3191b204cdeec5bfab17179b5efa1fd1261e28570130a10305a49c08f89336a5f0e0ebd3551316618841864d189f97b26142
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 10005f3e80f2e61e6259dd4bafc292223d2692bb5c6b5d8071d6a4d5bde00e6df319b872f2ee4a535dae85b899f7228d1a1cbe2d0ceffa94a89a9b60166e0fddab87
disk:
  secretEnvs:
    NODE_ENV: 100037e015939aadc11646c3ec4bb064a672bacf53e045c3d61f9ff635b47403e5af
    DISK_ENV: 1000b3edd34d19d24980c856a85cad5e38fc6fafa2dc473cd3851ecb9766c11dd103
    DISK_ORGANIZATIONS_PATH: 10000cbfc8ad4687787295ac40ec5906ebb24857b13cba150e5fe7c141f70bb2c64e3271f275483ba8fbc23f26233e773ba0
    DISK_RABBIT_PROTOCOL: 100012e4640577690722dde2250ef2c24eb668482b187e748342efca5b559f75c4ae
    DISK_RABBIT_USER: 10002c833ba425c44454f42cde268fc51983c13232f501f7eaefb3c9a91bdf95f86d
    DISK_RABBIT_PASS: 100096abd4c74dc3590f170eabe0e0d14cdaa3316b09079b5df4afbe5b012593c524ca279fcefae6be770eaea7fbcfa2f4c07e6c72968a3781f476e0c49f739cd495
    DISK_RABBIT_HOST: 100098aa17f7c31d2c45b52360b963bcd1ad1718c89815caddc052c8a9ffed936375
    DISK_RABBIT_PORT: 1000e86df1b9fe21e0d2394f1a520512e9c0c6c5b8859ec08c96f4af4177667e454d
    DISK_LOG_IS_JSON: 100031a2e695c3a87549c6dbbd755f0881aec18bc8459d104f65f020de83e12f6823
    DISK_LOG_RESPONSE_ERROR: 1000f969c6c4c7c61742df1d1cb1140e917127f1da7fdaead67ab1225dee8089491c
    DISK_LOG_RESPONSE_OK: 1000572a7586cfd72bc22b6259f2967daab9146fd8556eaed03d9ba502531f72ab04
blockmlCommon:
  secretEnvs:
    NODE_ENV: 10005a86b312e8009e7fd157c489ff7c6a1281f7d705b5cc67a86b9278ef95201bdd
    BLOCKML_ENV: 1000a456191c227aed37e0bad50a12a53b58059b1eaaedce039f75ec8824bc99428f
    BLOCKML_RABBIT_PROTOCOL: 1000c65543e0cde5abc392464df6d09466014aabbb99a2e8c2aaae1cc97c1abe41a4
    BLOCKML_RABBIT_USER: 1000360f4fbbfb842c6cb0e8d8eb0438afc8a1cc0a8f389af2aa297c8a65275d806b
    BLOCKML_RABBIT_PASS: 100088f453ff2ea5087a70db9c8fe223e2e968f775948b3c223e229bd1f634775e7b1cc41d8a23fef632047154d083a097f67947b4ed729a135f2288e899dfeb8cdd
    BLOCKML_RABBIT_HOST: 10006c822e989e3cec4fb53b0b15e821aa44a437de1f0971b932751b8c296aee80d4
    BLOCKML_RABBIT_PORT: 100039cfc6b75ab882ab1e564ce87823a7f156208760adc68de91448d5778427b205
    BLOCKML_LOG_IO: 1000b1ad4ee3221452429f35c3c2d86ad38bbae89040c4515c74b708efb9b43e75eb
    BLOCKML_LOG_FUNC: 1000e0dc1ba9a4a729d81b877bd5f1422d7e633ebac0281b17593d011eac9f3debc7
    BLOCKML_COPY_LOGS_TO_MODELS: 10005f8ebe84146f5ad008738230b0d25b2c7696eb3d8736f7e30da9c8e2474eb19a
    BLOCKML_LOGS_PATH: 1000c50989ef8fb5bb97223f6c542883bf574357b4fe680b6bd7713e195baa6a1e6adcbb1151cdaa77bf5e332a80bb83e602
    BLOCKML_IS_SINGLE: 1000cfe133f5b50912a725b324c6f2827d2120de0c815f464d58609162465aaa1d66
    BLOCKML_IS_MAIN: 1000c2ee3d96f00edb9fd4b19ad1c7f24037479b8eb4534a3ff93aa9c30e23cf199d
    BLOCKML_IS_WORKER: 10005ffca2342d81d5b97faf789e4556e303eb92f029073d4fbd62c7e8d9317d5561
    BLOCKML_CONCURRENCY_LIMIT: 10003031334aaa31401c72539456930c5b06acb30a8f4f7631df4d5f81a88b2de5d0
    BLOCKML_LOG_IS_JSON: 10000e1ba066b6040c4dd9207af81ee290505f654498bd0f2d889e0d830022badf4c
    BLOCKML_LOG_RESPONSE_ERROR: 1000fb705fd56d62429bd2f5e1b60abc956ae62530a3bf2e148e36dbf5b4ccbf2cbc
    BLOCKML_LOG_RESPONSE_OK: 100094a57202f319be74471570ec2e92a3bb2cf34881210248116d34c404e665ef27
backendCommon:
  secretEnvs:
    NODE_ENV: 10002410c3f6e81f2d21f1b50a40a94a443166d05a5732df7a254f1f198342876a63
    BACKEND_ENV: 100074515e714aac784b333752223ca8eea638feff43e9b97808aba961e048b161a5
    BACKEND_GRIST_API_KEY: 1000a6c03790cff2d106ab217eaf4123636c5ed09a35b8c8282c4dba13e806fd55669505e491b08b736c34cd705a32c1718cdc1b90da036ca2d4bf90059432669e49
    BACKEND_MYSQL_DATABASE: 1000b07d33a8c3e858eacf84a92e92d818a77c5841b3cdcba5d464c550804aafca4e
    BACKEND_MYSQL_PASSWORD: 10006043d1c23f26450ae12f5875430a501823079d8f311fca4e3390cf8bb0b6b132ed01d72ec7a0d148d49bfa5f092c8fd6a9bf11cd8b440c750b2f43d678ca9fcc
    BACKEND_MYSQL_HOST: 1000c42f09943bdc34500647f40aa20fa99491da0bf23cf2e6bda2036f86295765e0
    BACKEND_MYSQL_PORT: 100010236571927b507533866d601025ca6e7ca74c92b1571be67312ac936634aa97
    BACKEND_MYSQL_USERNAME: 10000e4a9f9149790ecdd31515a050ce43419946385403ac59050def063d66497cca
    BACKEND_RABBIT_PROTOCOL: 10005f9b78fee10e9eb53657500c4df9ae271cdf970caf1f2ba36393af625cbdac85
    BACKEND_RABBIT_USER: 1000233be8a3cd047418444fc49e0c4814502be461f881c83edd8124f9668f879625
    BACKEND_RABBIT_PASS: 1000b5c06b698b1b775e647e97dab377479a0d16bbbf5ed4c262f41b64d1216f76428d2b378cebd9a40a8c21548543c30215a2453ff5872bcec206beccf0b30a70d1
    BACKEND_RABBIT_HOST: 1000a12d6b6af8e4b134f83484becf56f88cad84fcf6997b782692e4261796653594
    BACKEND_RABBIT_PORT: 10007197d7369520d5a43411fe4874e7ce67af8d6f70f5cd37b90975c52e844f745f
    BACKEND_IS_SCHEDULER: 10008806d1972fb915c1579a4eca503484367bec1091d41a0feebb6f1110f42e176e
    BACKEND_JWT_SECRET: 1000a4174a44d5680bc6a2e5338c180ef5c4e9f3ea96ffc19e26931f75521f07ee9a39d73e88bdc1e4c65cd9a0e649b68c844a13b0b20e14b5a1ea828a715387cd13
    BACKEND_SPECIAL_KEY: 1000f55a949460a2bec7f5dbd9c5ad06a0ed04e23ccdfd93eabe02c7cca8065d1f3e64e075baede0c28868679e5e43dd4d299458e38e174379b38fbd406692a77c7a
    BACKEND_ALLOW_TEST_ROUTES: 1000e5547ac03f9f1a0fe46f78f650dbe2ccbc3edfa3ef30ba426cb038c674ea766a
    BACKEND_FIRST_USER_EMAIL: 1000227c56d7fe0ccc0b74678ef854f5d33f32f14b55ed3360661650e09c10a1c68c27138a0ac7ee6a329f5659c5d83b6030
    BACKEND_FIRST_USER_PASSWORD: 1000329aa00328434704caf66b92f2c197d476987fe19def662b77c7385d4250f68e
    BACKEND_FIRST_ORG_ID: 10004d8126144957575e6500d939732c5d5490d2011ba479b08a93b04f7b4f96fe51f6fc02ab6287e6cdf766e4474814f9d0
    BACKEND_FIRST_PROJECT_ID: 1000aa767f6a75031cde3ee7707e14986f6d7354e516837f287cddd8aecbca631d2bb3be11fdd443f90be03bcb4e788ca955
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 10009d57ecb092e6ae141a3828b2df246b4fb4c80aa690c73a083e32df57aeccfc43
    BACKEND_FIRST_PROJECT_GIT_URL: 10000513b59ed24fd7e0d99a3e4e7a07ea73b0c9c14e477a42cfba914dd399466a7d2928231bf3ce54084fbd0fbb1acd14b1d2a0fe6e55b6d210cbbc7a59c6a54427
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 10000af90617d0266137c327f7fc270f6e2a71d07c4360a2916a9cf9d05696c87bd4316cfb6407a8edecf61c450999ccceaab71fb01dcdbec687b756f5dd8f7315fc
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 1000174631fa3fc71d864585a83dc5167575f07ae6e4a23aff53da712d6be1f1288e7bb4db7e0efda13a6c5c35c4f54f8d022cf4706a97dd9136602402debbf762ce
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 100041432f521bf5143311e2c8cfb1c21ce22256d4b896434e457b6c8093fd33b8d6
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 1000ee82cd2d23dab40c05ad2dcfa875d629c05a7cd760f3c162533d45ad86b33cb2b58caa8d03f62b0cd1e364a2b5c8f1484b721ba63d516a5060afe02afedfafc1
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 100019bcb7e18a0577147ca4ca469ff8bfc83319e9cc81d79c6c3eb996b3a6543562481597b84fffd0a3e0064b47a07da364ef7f68df59878badd358ea531ef00620
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 10009108a92bae0f1f4f8ce603b86e87ad362ebee2510138db2f6ad72a43eeed1f118012b184fc1d552e9dffeb38240ebb4207c6c2383501a198968290e2c663499a
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 10009d880b82c3f79847bf6adb14ccbf6ad5ee8b780a3961286a9997e94b18435f7b8a5acd414a82dd69828597f1f03e2664
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 100035c301e962583317f417e00a0d21664ad22165d15b8903adb524113694f621cd
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 1000559915b1c4b149603803cceae8ff5dfbe87fd66fd686676c9b6c6692c86a61b5
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 1000a3956701ee7158c06189f331b25a54b20520b10ad853d0c11fbd865f138c07d4f84c9372c34b07e34f971984c1585710
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 1000366c79b885d1df9cbbd5f379e0676fe4b8f657c1093836a6b9cd277a11c14e53
    BACKEND_REGISTER_ONLY_INVITED_USERS: 10006c9c1b25c07b7fa023b77257d5124673cfbcbe23232094d841e456586a2e8611
    BACKEND_HOST_URL: 100046703e9f30cd075b42f33a5f4b918d3a14585c63311a1f51788e0d435c1696d4bcf4f5269e4b7344e8c0317f5574f2b9
    BACKEND_SEND_EMAIL_FROM_NAME: 10001716d1c2ec4b4f1c70be602d3fa266c32b070fd28c5c6466eed7d6b638310060
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 10008125236c3b57b053e723acdba767d5b8e23d978945ffe562fd5eeb7c9803b8760b123d859f07b38b0971574abeafb28a
    BACKEND_EMAIL_TRANSPORT: 1000b38c3bbd513fd93925f2dbb3776d8026b2e6628e8a46f8ab7447baa7a5fc7642
    BACKEND_MAILGUN_ACTIVE_API_KEY: 1000f6eee2c3826b1061eb2b69102b622053e3e516223f264713fac78d0755d222e2c69f0c97a479a5f2f00ae11bae2e40a3efc15940622465407ab25a32ebc3231d
    BACKEND_MAILGUN_DOMAIN: 10007c824eefbacc737695c276b835f2575bc205b7f8e768a96f65a3c65a73937e21
    BACKEND_SMTP_HOST: 1000ef125cbb5af95f1fea2e1168d281b9b926a1caafc59ee61505dd1c0761292462013fa1385571f83af36f3a7b34da227305cb2aa620566ef147f308bdcd31f72b
    BACKEND_SMTP_PORT: 10008d9b661d587bb7e376e76331add62c45a5ecfb981f57b3d60543336c562aee91
    BACKEND_SMTP_SECURE: 100005315bd5a720d8beebc50a5e1aaf0cb91495a3d25132a3e11b1274101a493097
    BACKEND_SMTP_AUTH_USER: 10003eaa9cd6965e628c058f1a80224fad9dfc5452efd3a3d45c6a87b3828ebd0448578329e14af0fb1ab5cb49519dcb9fe0
    BACKEND_SMTP_AUTH_PASSWORD: 100030bc29441507c819c5b699cf244ffda195b3dde203cc3e0cf0a68bc876c41594fa3cfc8feefa2769f1444a287328e2ae8de0e039608901ab8cfb82099c676387
    BACKEND_LOG_IS_JSON: 100042262c99363e4869b5203e0b3cb89960003b2fdba70972a4fca221197310ac92
    BACKEND_LOG_RESPONSE_ERROR: 100073fa2c01884794d475b9f68769680666202f261c04334a0314537df7e9cfe186
    BACKEND_LOG_RESPONSE_OK: 10000f940736fdb1351a694359adaabcf45fc088ee5ddcc23d70ed2e662b6723863b
