ingress:
  host: 10001c05aba7794e09e14d5579420abdc68aaeb96b0c6ad5e3870d959a8ca470894f6ad3e37624b94b8abd4ccf099233fa85
  certProdSecretName: 1000f2af3bb54c7de7f81a1a3b2c6edac8737facd0a29fab90bdf4660e8ae4fd24359d13c30cb43d77d8fc124a122516b8f1
  certStagingSecretName: 10001dea22caf77e905448b8063385b3ea1795b4443deb8e68b1f0def3c9a1de24e51bcd9a4fcde4c9ae71614b9cc808d6f3
  acmeEmail: 1000f04ec49048011f68edc35d115b48a7a012e71ab24849dc15bed2e2e25021fef344c158849201fb96d19186864e2b12fe
  routeGrafana:
    enabled: 1000ad28e93ae422231c553ca1b5d8eb086aa8c5823b269ac687ae9e12b1bcd16262
    host: 100082c6496bc41f0597c730657861606f7510ec9ecca65c78e4e8ea2acd9887c11505f0bc958c686d80f3b3cd4ccfb2cf9f
    destination: 100018c3edaa88c0ec24c8c750d6be3cc4543d91083f3bbf90ccea4e75a403ee0919ad72b7015bc709df587f8d014e491aeb15c0ec378a731adf9a64b866595ca65499239503554ec3b2d10f4c86653be706
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 10007fb92fd94b08a4e2f4e4503c9f96909c79aa67c1c65de8a418bec0917fe2c1aaac9fc521120c6aafff4a5e998e58b240d502690a7394ebda2550dadece644a7b
    MYSQL_DATABASE: 1000bae43978e383fbde86e95387a3da86eb6eacd592c3070559ad3ed3e298b2aa01
    MYSQL_USERNAME: 100068aed4d098cac5433e2aa5017d008f4d4c36d15a69e95cca7bce61633df28090
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 10009f8ebc679b0f8210bd2d36d1b0431aef0db48f413421ced316de86e4962fdf5c
    RABBITMQ_DEFAULT_PASS: 10001335d65c1237a0d43de33ed5a47c1613522ee26731820702313228f56dba92f258f7406271772af2d3ff65bc7cf60a5b5c6b8e3441f449ddae46d8e0e101c6eb
    RABBITMQ_ERLANG_COOKIE: 100031fc412008f5557d30572ea907ce6b6eff834b79239c95defcdf9a1a94ac570de8b57c589ede944697d83f5e8b07bdfd0619ca88047adaf89ed58f99c9024fe3
grist:
  secretEnvs:
    GRIST_SANDBOX_FLAVOR: 1000fca4b6224b64895e23a174cbe45f89da838fef303ddc61fe92ff080e8de268a3
    GRIST_SESSION_SECRET: 10000ce9020a55adf51b9f66d41d9cd5e3fc1fa6aac6a081086dffd123922b4e53944cd540f8d6039d51e79825d0cc2ffe65f8abba379f62ffea8de7a5c8906b6753
    COOKIE_MAX_AGE: 100030d49bd0c0b2248a9c641f899428ccc82ff26824746235979c4d85091eab3790
    MPROVE_GRIST_API_KEY: 10000713746a75b5691e3a1fa6fb6449a0535aca95c31b1fbc244c55d0fe01b31b78adec4bb94f5ef3963e68e70944a3db570bb75fab6b880612bb1676ce219f0a1f
dwhPostgres:
  secretEnvs:
    PGDATA: 1000938ad74b0e21968dcf62e948eb3339812c15666d4e4eb9fcc309e84b8a8fb4d42a5d2cdfe21b54478aef26320cf62028
    POSTGRES_PASSWORD: 1000fd6cd881741877fb8bc5687bf358e89014aa8aa5947f4109ba601c077a29b10f40d68b24ea05cae034e0e5f88014db9ccd76eca333893ee8d95653e10bd3a7db
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 1000ab28d37e28075a9661bde0b50c28822a7bd9000a87f923c4ad1253309560abea
    CLICKHOUSE_USER: 1000fe26043e5c6cd86b29d70eb61383388c354765ba34bcc58098117c45352c0315
    CLICKHOUSE_PASSWORD: 1000794e7648232096e365cf2f84e42e4e9f1032225aa4ff04b93c89ccae41b899c730fbbdfad129e44ce65dd2cc568fb77a66787f57ea5a7f57fa266fb70b23cff0
mcli:
  secretEnvs:
    NODE_ENV: 100046fc717bd327368c1f043ed421b33a1a5a32073e3a379253bad30bbd765fc766
    MPROVE_CLI_HOST: 10003a206e14375d0cde3eecbff7f746a8d896239bd680bd5d26f61e58bf684cbbd7baacd0d2c18d6f656c215f4ec09c0f69
    MPROVE_CLI_EMAIL: 100036d9a4bff88ed5dd9b3db279a0caadaedae786c30518a8ab8b1551e6b03f9bde700c156735edf46c51d8a521682c49a4
    MPROVE_CLI_PASSWORD: 1000afa3da605d0d64c7996aca6b4090d8e4360616f2ac2a2457519b7325d2175cab
    MPROVE_CLI_PROJECT_ID: 1000660450444451fa66f2fbb740cb79500e9c56d2f0a22c936b9e0888c68cc04bee34f9c93b51d69ef7588a35cbb76f9f7d
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 1000b54f059f0559eb7ba5e31050f207a14d299978028fecd68ff437d5af409ca65f5b1575df7603a5293569b9c9c509620ca5b655aac0af66e0e0e6b52ba5f05153
    MPROVE_CLI_TEST_DESTINATION_URL: 1000b6e193d70f9d6c80e7f57f499165b4feae7c7426c9053d089a6d23dee49387adc1d2e74e66d8ad933cd1fa7b6820a8f3d1d59d5a7b817dc958aeb9669b2fc2a6
    MPROVE_CLI_TEST_REPOS_PATH: 10009671b2344aed2fd36405c095c99257f8e321cf770c919ebbb0ad21ff90d0e4d6c330e95c76889e50a81aa02fe3861cf2
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 10006fc2b90b6b2c912cd8ee0dc568dad25676e3c0c6302ca45f55742d8eab67f93eb6f9575c1e9eb0e74b7199232bd7c48f1c99fcdd7ac97fe1a95577701daca42ef63ef1d6e1d43108bbaa992f2f345d07
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 1000e908d99a5190a2e89289958badf4054459082d8d26e85cb20bfc9556e6a1d6f0d5cfd63cc8454a369a96aa245ea5e51382dac41f70b41a203d583968b0e26d2fbc3b369dc0390cea890c37a072f97f899de073cb0b95f233dc282d27319706741495de3d5758c79c56e7997ef32f62e7
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 1000a60a3232771bdc0751dd0c97c246e37b6b734355ad03702f758c7d65ff893dd0bf9fd8b13690392e032d27022937f5d2bb5d52188cc204459cd4ba3c46fea3ce
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 100010fa94f1a529f3ca347c0280666e15d920761f66b0144bc655bc018240c56ae9f8be3d9835e476adcc078ceb297e21d1d9010558d0843da27ce320557d2f0eaf
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 10006dcc5997034bf01f6459415c37d4c1501387136220bb7da9b69a8bd64a9b56c6969323288b27d4a71dada2a9df3ea6d80f6868377be74b8e786bdb0a06c82c77
disk:
  secretEnvs:
    NODE_ENV: 1000445b8c4652cdb789b23bff0938cf9562bb6f74ceb0f563563f0e3646f532a3da
    DISK_ENV: 1000da1b1be40e590202b9a77a3a50b286edfd4ea48a7159c3492d67602277f3c7a8
    DISK_ORGANIZATIONS_PATH: 1000f93d148008a0a488752dcdd2f3dcfe4579d53cf5c659961ff1829a40ce94d8ce1f1a37604970d6fb2543f3a9fa4976ee
    DISK_RABBIT_PROTOCOL: 100025c82c6fa52137bf88c1df4238747b45056c9969cd98425bed054bcfe5d75775
    DISK_RABBIT_USER: 1000fe8db0b6f5976e00c92af7a5115272bae8d0fb0b5866b5e24134f7e01dfd5248
    DISK_RABBIT_PASS: 10004ae9f64ab3ad75a6842f5fc7d793216511746aa8bd3c0dcc625a1f3980f08a77f922aedda7ab54ac1ef60dd12bba54b6745ccd87f82599c4cad3cf48b3f53d44
    DISK_RABBIT_HOST: 1000d8eaded0711dfa922da1b57fd7de204aa763afc8cb559db5bae508441b77639c
    DISK_RABBIT_PORT: 1000627ef0391ca07b81025d3f41e770e3b9d15966f396dc0f7d887c0fe7514605cd
    DISK_LOG_IS_JSON: 100062144040a441a707c18261dd444a544ea9756506265d00ca5006e68189daa830
    DISK_LOG_RESPONSE_ERROR: 10001a190c01432bf98621030a6e6e522da5d2d8679db3904d2cfafcb28b2255846a
    DISK_LOG_RESPONSE_OK: 1000e0a04ce3e3a5cff2e5d5f6c8d9d256b3080da0e761e51b65178156f04e5ec7ea
blockmlCommon:
  secretEnvs:
    NODE_ENV: 10006002bd26dc864922037f757df4bc0aa4b623ddc49c58e55168d2b06e200d44c1
    BLOCKML_ENV: 1000e2b15c78ba3322538dc519e3ddbf7d77a1dfe2c16acf510f421f8d6c91d654f2
    BLOCKML_RABBIT_PROTOCOL: 100000cfbea33051fae9e552faa73acd2ee0acb2ec6bfffdfcd53be4ee0994dd93d0
    BLOCKML_RABBIT_USER: 10006b517fa836ff6185eb6622ee4e426858fe5739fbe62751df8ebba84f36107fe7
    BLOCKML_RABBIT_PASS: 10003d80d5a5fd27edd26ae8a1d85a8a78ff598a2254c75066be21fdba70f7035497baeb9dd2366a6f65608fe0b8bb85483c1506bee57b9ba2f871e43dcb00849264
    BLOCKML_RABBIT_HOST: 10002fb61ce0be0a2e61dadc41e17a71f7ca0a834b8bb5ddbb42e10ed14f9a357e22
    BLOCKML_RABBIT_PORT: 1000f5bc371a0aeb9ee872883350e4dc84e19bb66d9ead6a73c993a7f7cad9885f1d
    BLOCKML_LOG_IO: 10002bc0cb56e97a0c7ae87d12e1381170bac7d1420e12d6cd918b92bab2c840d4a6
    BLOCKML_LOG_FUNC: 100066221955b853aedcdf7e96e425f9a95376ad504ad2ae5f4d1ff47c63854c6693
    BLOCKML_COPY_LOGS_TO_MODELS: 1000ab0db8f375523ed45dd17336cd1fa38072596cfb42240af799c3c161432a3c31
    BLOCKML_LOGS_PATH: 10003e0962e744ece2b84a66d78493c272e246a4e1962592c355c63b9377d433b9ee8ab2d88dcea1db544c9d37a40875741b
    BLOCKML_IS_SINGLE: 1000a3f599b2e55b36355a8c2a12e9466341f6e2cfea10b18cecf9dd309a0e14cf52
    BLOCKML_IS_MAIN: 1000c6caf37b1525e1bdbc5238433727d6f375c7085ee96cd4a1fe0de33b906d2e6c
    BLOCKML_IS_WORKER: 10007dc9320093cd1db65a3b48c9a6a01422d1b940d9ebc67e03a92ad4d2d1ef7642
    BLOCKML_CONCURRENCY_LIMIT: 1000af8b625b182e9ee3234a8678ac4b4df2bbfae9f4af967b475828da2f4f60bf03
    BLOCKML_LOG_IS_JSON: 10003e533a788b4c321908c4910b1a462537f50ce08c5f9b4017cb5bf6ff206e7b8f
    BLOCKML_LOG_RESPONSE_ERROR: 10000439cca143bbf2a15d9a7294971a5ad8b45eb82d4f54290cbc69a47c98d6a746
    BLOCKML_LOG_RESPONSE_OK: 10006845aecd6a2ce7cb4acd4cae8392ae05eb5fc02c8e09dadabe8f6029c44880c7
backendCommon:
  secretEnvs:
    NODE_ENV: 1000c68a233ccfb16b05f4e83d5f82f83fbd23541ad03c4b90e33d466a0f94939878
    BACKEND_ENV: 10001d82242783dfabd77c89dd91c1e2b3036f270134b4fd7c3af31a4b48cd6ae8b4
    BACKEND_GRIST_API_KEY: 1000686fc08cddc236823ecbae59d1a75a54dd93c568c686a3e3f18f4b657f63fe6070b3a39ed5bb6da55fc56d39342ecdecc32e0618413995b14fc1d298d348aa15
    BACKEND_MYSQL_DATABASE: 1000f1ce44062b463000eaffc14b2f3d16028808916b6729fc4eb6da6d69898f77c5
    BACKEND_MYSQL_PASSWORD: 1000744a4df57bf30dc5e6c050b18a3df6a751e5050b024638cd67723c62a9ef24d672223e10f2839b1e27e3916b2b73ae4fd2a1f8915dc2eecd6a9761eb4f86d1f6
    BACKEND_MYSQL_HOST: 10005d3a16b0a09e3281997e8f3f7fc096a1f6b1fe793b4f2e1ac0919e5868bd5976
    BACKEND_MYSQL_PORT: 1000e32497c9daf11911663a48bf9ce04432b67eb621cd928c63d3f62b4339f38016
    BACKEND_MYSQL_USERNAME: 100080ef4e3c0d076e43b8235ce202a25d2235b9cb4feaddf8cbe0e512cd3bb20bc0
    BACKEND_RABBIT_PROTOCOL: 1000648231f7dc59adfdcf2f4cc5a77b78a234786d1dcc566b392d22f86fd1fa1a36
    BACKEND_RABBIT_USER: 1000067f533c369959b9434f8c60c0ee789635d937af6b599d3ade3850b2d1968e4e
    BACKEND_RABBIT_PASS: 10008cd9009b7c0cf1474ea5f10a32944c456f0910d9ffdd0715a17eb35e4736145279ec421ee0d30862598b76d7bda403f6aaa59ef6575895e7dc8a9a59938e7beb
    BACKEND_RABBIT_HOST: 1000defdffda8ce177fad765bf5b28849ce7eda0a2c4b635a41200ab30dc4df97d9b
    BACKEND_RABBIT_PORT: 100013cd0579f1ffab2bbb8de48855a048afc8e5fc4a7898f4aa40065c276cff472b
    BACKEND_IS_SCHEDULER: 1000f2386983323a7c87fa074cee35db8aeab38936ccdaa4905b015d64965b1f3c55
    BACKEND_JWT_SECRET: 1000b750ad62a8edfa59b45c7a82ee6355cd18e8063e7cca1b00284126f9a46d65653877e72763dade9e0dc717f0471701ef2ff6705e3b481001ed7fb31a40c811eb
    BACKEND_SPECIAL_KEY: 1000a71d554f52e0a77d0c529ad8997b032ab97da160adf58b164742df691fa9f1fdeebd170b36694a18ba6910e8956dfa990ed75cdc866f2407d3a2da2c342677f3
    BACKEND_ALLOW_TEST_ROUTES: 10001e89d21377525607854dd640bfebef057a01bbbd6ea96fc50275d108b61ddde8
    BACKEND_FIRST_USER_EMAIL: 1000f73e69c40b24175c72860032e148959a7438d46a5f17cee6e8a19bb1a2243541d86480e6d6afae6b90bda2291471e0c1
    BACKEND_FIRST_USER_PASSWORD: 1000368653e10c26bcd4f437596dc34ccafc2a478cb23a22bca79c79c5d8a50f9edd
    BACKEND_FIRST_ORG_ID: 10001ef6a0cc894adfa2a5cbf2902c1759fa642500ca4b26c1a955e2445b1a75372217bbbdbd08b57fbe1c32f5de12decd65
    BACKEND_FIRST_PROJECT_ID: 100008ae354e059cb9b7d4364bd96b26f42cba74a5c571de9c3108f566d2f9b9c0a2ce5b67ececcdc3bdfc44333b2eece32d
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 1000262f5c4662be2a1b4114510422aa6bdcbd446fbf881a95afef60c908047ee585
    BACKEND_FIRST_PROJECT_GIT_URL: 100041e98c76bac9d94a9000f7147e6cf9463c4850c271c3ba492fc770c1b89d71856ae7fbf90aae95d5f9d313834739a202d899836420ff697c5650d9aceb6254ca
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 10008fda7b93c8bda9554125b867b7f4762dd2dae279ff6dd1fe42b1c33ddd3e40b25968b64eb0a49b9e372e2c689c4748fdb2717675583dee490d5b29bb503b42f4
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 10007ff78c938c68c62297041b64625615d2378f9fe2eff7441a6b297dee611b68907ec171e8c4ee698c570f46b9cf1b59a23217ef4db7ec4eb2d4484eb7028fada3
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 1000df1897b90d1e018442c9f104a82225531182df2bb943eb868fdc3612ee767621
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 100019df82f65c5768d91539d630748ac216b2b7c084797e8d714c31a6740b249a63f992e03e626eb05ff552598c7df49d1f1dd976f6b135d43c319710eb407b3696
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 1000b9757e5f8f5bdc40c8eae95937edd0070393344e60992ddce7bea35fbfa919f411ff87d9b513126443a587eb7f6b2dabdcd21453b628f45c48f6342ae5f485f9
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 10008f71a02b2e1a9ef1a7d3c2efd378897736c6c57fc4aa3d96c1ccea34250e3ac051f201bb7972699497a30fe7bb10f782b7f356900914301a66b279f0a56f10ac
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 1000bc7cd24d652ddb3d0e777c1c1a2d5d328df5c9d12d757dbc3c640f33c45e226ba9cd249993f9cb2114949791911413f9
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 10000b95271e5942f14d3f840b6740c80356a3cc9c513cfbb94bac01161825cd83da
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 1000bcd324e23d994e06c6d7cece9008da1b0cd38c450fc3b6976302c22db9d5d25d
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 1000091e265ca3c815af28ef3781b65702d397bb6c8186513d473d9388c66bd6f916a2744dd3cc0178cddb82baa939c85d37
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 1000652f1d9cb45aa085535040f8d246eaf0a37cc569bea2dbcd3df81d4fd501aa1a
    BACKEND_REGISTER_ONLY_INVITED_USERS: 1000d0670142968a488ea9c27238c0d925d2ee40c6e603dc329871139c934ce97cda
    BACKEND_HOST_URL: 1000090c4f3e770b738fce2e9f34d85cbec50c9b918c465760a02507594c3044daf875948f41b52a2515fa9efb07e44be837
    BACKEND_SEND_EMAIL_FROM_NAME: 1000fba85d587cd9471ff221fd7957717228d151d6994a5387b2500b01e94ffd6776
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 10006de1db25ad089f0efe7f9a6a2a2f8a8ddc5069ddf8a099888fb3c052443a68500ce09e69c4e65ccb9348f7d20cb059b3
    BACKEND_EMAIL_TRANSPORT: 100039ab57c76a66cdf8c69bfcbbb7585046c64da563cfad0f0ec5eea6b4ec1cb9d6
    BACKEND_MAILGUN_ACTIVE_API_KEY: 1000054e08dc86c3d236c673aed0a2f9491e154abc7427fe53299fe75e79035112b37e93e70787c869011e2625d542f379871135d0200d2db102e2e2e83e19399cf1
    BACKEND_MAILGUN_DOMAIN: 1000ba44bb58e8f4eda3cd2f500b65fcaf899244d409e9e69c74e7d4abc24f4f25a4
    BACKEND_SMTP_HOST: 1000eb8e3ae5564c6d7de12568dbdc917e98a1cea1492309384135bc29339c9896d61de318ea82b7569232c40e09d390062e855a16943c9a6e47d50aadf76d50c3a1
    BACKEND_SMTP_PORT: 1000936897ba5a8aff730df60d8fc543fb77758da551e6e394ef68056f796d674968
    BACKEND_SMTP_SECURE: 10005b7295ab4be4aaaa3755526b55e0cfef5b84212c3964eabb73e691a564525dc6
    BACKEND_SMTP_AUTH_USER: 10003dc943fdaefac8709e268f22f5ec8069f6d3bb78a51f8a7007ff778aa0b96b8bc2ee9df116eaae1e63ff38c99bcb1a6b
    BACKEND_SMTP_AUTH_PASSWORD: 10002f31cd697f185b89428afcdc3728d78d65d9247c0fb26133fdb4c1401ab83864ce806c4a6143218634968a8c25871002a2258c5d8a8cd48e169260fdbdd871e9
    BACKEND_LOG_IS_JSON: 10004ae3e6f472fab8a9e9207d73d82f6cfb267624a8b383486d5b9377d8b318f970
    BACKEND_LOG_RESPONSE_ERROR: 100025bcdeee394f2c9d46a851aba3a521f09111f84650da723132c310bb4dd2eb29
    BACKEND_LOG_RESPONSE_OK: 10007d5d971e94a840a9cffd95a4a0330a04093259e0b935da66350561055aa8da53
