ingress:
  host: 100032cbb25a202ba23fd91abea353f7ca365e021f3d4b17b81e617531a740cb78daf6e922153f205cf5b35e8d749071c1fe
  certProdSecretName: 1000efd941b3a69d2dcb978cbfc6eefea7fa27e8110e687615116278af6dad90e49175dc7d44ff49bad075e5fafb46c91bfe
  certStagingSecretName: 1000fe22d140b58200e6ae664fc31299ec7480a034e19ac1294a5d49051b2d5100485d57c1f13e4eef2b72e364cce3823c79
  acmeEmail: 10002c2ae548ed11f897c4a4cece211bbc5d22c46238ea3311d0f999450c785e197c1bb006e0567772a264db71d119a58ec4
  routeGrafana:
    enabled: 10003dc8e89504404cb4cb7a71f6b93b8f59520c3e2120339d7fb4ded9c1467e4686
    host: 1000e3bdd8df55484c6d8d710674ac591cc0bc7e952058185d9eb5afab0ec306979ee1d152d5a864dba942b7e7da67d3e74b
    destination: 1000a4344167df96e8eecd06e780790078d5bb963d9e1069dd77421153a17c873594a6bc8eff6829f8f69df02e6d7725f1e2ec6dfa760701a1055e3e81324a7a2de144e66cf199182bd34cc5cabcd4554b93
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 1000f94ac8670efbe524b088574bb2d09f764c28625ab3357e04d4bc7f4574821ceedd992cbb250c9aef6190961d5527c7c21d6b4f93246d880638076c9f4d753ef2
    MYSQL_DATABASE: 1000fbc29da92ac2a6a78b8a01a5eab0425ae6052b1840a55fbab6dd28da093e967c
    MYSQL_USERNAME: 1000070f8fbd6adee0478d08b60eecef53d3c6a40543f1c1dba8d52d34d4f244dba9
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 1000eb28f7b05329b31d9e9077ce82a6c9d6216c40c0ec8a5e8e8e7e62e5cb23f6fd
    RABBITMQ_DEFAULT_PASS: 1000794f3ebfbc8570fa839a07db5d782bf60f1c16123f0bd951178accb6db280d3c21d731168bd0876ae8a170ffb009577edebe4abc78867c525441ba972db8164a
    RABBITMQ_ERLANG_COOKIE: 100038b5882fc7a709e7c12d6becc6e01ffca6ad2aa8a6c4bfb25eb091000d7eecbfffd93d479e357880cf3693c65915338edae6b0cb759872dc1630fa836cbecec0
grist:
  secretEnvs:
    GRIST_SESSION_SECRET: 1000f9770cc9421f3194df32853cb7dbfaaef70f4adaa403719b4329bb717c4727dbc297be91fe502bf565f522878e65e9dc454a9125928a16ffed608d976430386f
    GRIST_SANDBOX_FLAVOR: 1000ed5e7176a80ecd1f85165c47fc0685871d89700b0644fcf8edaaf41291d963a9
dwhPostgres:
  secretEnvs:
    PGDATA: 1000b4b9358cff81369955bafb38864e9db59f2042dc0cd57d3dc8f953b16cc6a11a1bba8328dab86cd73e9aa8637316a4ac
    POSTGRES_PASSWORD: 10006a02bb48365c85b3013fb4edb566891f5b1e2a9a47caf8bd72b266f8beb78e82e8b57e0de759957f5f7d3c5af5fac1fd5f8578d50875495129203bf21db7735f
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 1000d1344d808ba56bc460537270fdaf6871030f436b69638d5127fcc621c139c03d
    CLICKHOUSE_USER: 100095a60e8fd7d1978971c4f117038b21826654dff73a94d746b28fd695407e4a3f
    CLICKHOUSE_PASSWORD: 1000f6c42548985dd1059bba3dd1925ad61567be0ca992fd1be680dca059fb82c604c72398cc9821570403a70280816b2eacba26bf3868ea97cfc2f2291739d5a685
mcli:
  secretEnvs:
    NODE_ENV: 10009344230f2ce16e8715ea9976c5fba92266f261ce52e00961329fa1d9db09380e
    MPROVE_CLI_HOST: 10008c09035ac480fdddc8f434f36cb5aac03870dcefbb4c82e4abbeba3b00674ee0bd82d98597915c25a5fd990dbf1a9ef3
    MPROVE_CLI_EMAIL: 1000107b79309e8b71cb96bd31a76caa5a055d0fbea68915abe78afc7f82643895a971ddd7971389f46d52446fd99539e0b7
    MPROVE_CLI_PASSWORD: 1000811cacfbdeb3e0958a5d26cc9bfa620d2ca554a72d33fa6b274ea4961525e276
    MPROVE_CLI_PROJECT_ID: 1000e27725bd2eb29aa41b555ebbb5491040bcae87707f30159ea042f14db0fe68ee508c11995306dae488d9654cc412674a
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 1000ab1cf3d7591071e429feef4bcc2cd141d38799d9c27d4a6081a87f351839e9e9401a8f8bd15b56cbe909e7547f633b1aeb07a26a2381a9164bac239235bf8b31
    MPROVE_CLI_TEST_DESTINATION_URL: 10001ca684a134de0e0e62b4346a3c0ffdfa6d6d7a419a1bca2d59ff4bc9b23ecd71c3676663dc335355f7cbb1290c1b1d40dfcb02c0035c547ffdd31d71197b9234
    MPROVE_CLI_TEST_REPOS_PATH: 100041b8ea84b25d461f80e9cf1f621605916669d6d2462bb28e67d7d4d6912529c13c0a1f2060c761d9b516ff93e1db21c8
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 100013761495e51b2738488586a586308c74fb4fc8cc80ee9de047220e9073aebb6bd87ae290de1c153abe61349d576f170a84a060db012985ede01e3788539c3d896e616a0aa788560fb9ba7942bda51027
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 100043f42a1fdb55621b9f3a1ca6c3e54b12dee368ac8bca285e24d1a76281dec413b7d62ee33f3e3f365125b8cad5c5896505f2c043843eaab60ed2de180eb7f3a958a88976984eb420c7ea430445566b92264ea05f79d6d5da3cbe95618f6a3615a20e5505971bf6550395b9610fb0a263
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 100006e183a3958db81313e75f02dad8fb2e5b695c35754862ee83d602fde34949603c66362e06b873ff8bc7467795a6e414c5010978108982bceee2bb122b3b1c8b
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 10003fe7461f037bb376b6b5ddda284dbb25458869715375b50b7ddc62346efe94c5c28fc6c79062ff0e23aa67bfeb6039a203aa92b2673ec4e7cdcb07b33795ccfa
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 100009ba01a356e8b8edc6f00a62dd4514953e1ed25151432684e0068435cfb012ca8fd775d6ff7aae793f288b4a27bc427fe4f485b578a9ea66018917974d3a90ae
disk:
  secretEnvs:
    NODE_ENV: 1000cc0f019c3f5cc25d3ba55309f61ac5966772a2bb774a47237c8e691534f0719e
    DISK_ENV: 1000b3cee1390d9cf6fd6f3fe9ef5f988f6a9ab9b862931d97a6cc13fcc7e3ef3a53
    DISK_ORGANIZATIONS_PATH: 1000f68657082609f671c0e6b3d30b8660c3fb033f84762d8602da1b9d4e31cb8c71f6607421828a63ade175436ff9da82d5
    DISK_RABBIT_PROTOCOL: 1000892eb39ce71d58f5f51d232c8df6871c6a36bdcef3fb683fd18cb51671a849bd
    DISK_RABBIT_USER: 1000662fb56b47ac3ec5f816c80b96532c7efd88dd3937ff214076488624c7bb1c78
    DISK_RABBIT_PASS: 1000ea9cb1bb6bbef270ec3e11999b41d75a21bd48ca0c2fdadbcb8de6ed95ba570927905ba969b126753d6efe62ca53f9e933f38ec231f23601cbfce24d013d5fc5
    DISK_RABBIT_HOST: 10000098044126e4d9f0364bb22b0866a63991bd287627a1f91ecafc2652e93e656e
    DISK_RABBIT_PORT: 1000855bcaf1403f7e46d59a56e89586a3075b1e6fe45d25648a6acb494863a977df
    DISK_LOG_IS_JSON: 100095a15ad61281639d27e248368dd757378517fcc84ada9abdab5899f0d6c6bfcd
    DISK_LOG_RESPONSE_ERROR: 10005ddfaebb5be6d81e8239e58fa792f54994c7a498b6442e9e0e4ecf3e6282b594
    DISK_LOG_RESPONSE_OK: 100047be0f115be3aecbaa5723a63e5b02618b66101ce8f6febb1c5956fb2a71b5b5
blockmlCommon:
  secretEnvs:
    NODE_ENV: 100060b427cc0f5fdf9da6dd5b9b23c21f3d5a9cf3ab66be06916c3d0bd5d962c7e8
    BLOCKML_ENV: 1000facd124d548c065ffc19b0139c0c57d48fb976754f2044f1e40c95538637ded2
    BLOCKML_RABBIT_PROTOCOL: 100073fa8cb142c4f2f5dee154a73a7de789b3dcb3e4c4452503b394574d7bbcbcb6
    BLOCKML_RABBIT_USER: 100080fdc6eb17272e1a4e45879b40028bba16265747c980d31c8302aa8b564659c2
    BLOCKML_RABBIT_PASS: 10001159a4b24ed01b6b2383695ca87b2f5fac413ca2e6693f45e5d6b21b70f6764c463387e45d6aa119498780b9d82cc816f6a33a377d2741a503a300a2b1a93120
    BLOCKML_RABBIT_HOST: 100096a5a3991a5583fb9235e8e96185f766b81ce63067bbe756cd0e497811408c3c
    BLOCKML_RABBIT_PORT: 100037704ac1f7fae091c4e06cddc2586deca4dcb30e794f014ab9e6de83f76c2a27
    BLOCKML_LOG_IO: 1000522eb5b61af4771047c3cfe8c287fa0a874673a2f2912f24e93ab44df9718ab3
    BLOCKML_LOG_FUNC: 1000d297ab469c0ac45723fcbc2b33aead9ec535a29fc73c02f62ed9c67222e903ca
    BLOCKML_COPY_LOGS_TO_MODELS: 1000be08bfb420901faaed7b63a41712ed83fce7a0150bc89cc81e279bd77ac1d392
    BLOCKML_LOGS_PATH: 10004ab302b68d64680d3bdf095fc2693b21eda6d22a2e1539519a5f07b1f6d2c06d932485c666329ead420fc782265665b9
    BLOCKML_IS_SINGLE: 10003f67050a122b9993ced220a15e56d029ed5bf951cd1a50205397adfca35d9bb6
    BLOCKML_IS_MAIN: 1000c938c83e2be0e0c04095d340a2a9df0290307f10843394193d8c501ba29e123a
    BLOCKML_IS_WORKER: 100077864bb19706697244174d1103d320fac8f86dd3d36d9c9fce58541a08785e38
    BLOCKML_CONCURRENCY_LIMIT: 100026278f372877721927745ba78796fef95bb128669a7b83330dfcac63501547df
    BLOCKML_LOG_IS_JSON: 1000409486be00debf61f489063370a8d93e138b642da762f29902fb919f5b0c8cc2
    BLOCKML_LOG_RESPONSE_ERROR: 10004c5aaa740c30362e7298db0010acd072206d2b57d22cf3cb026aeb242f7713c8
    BLOCKML_LOG_RESPONSE_OK: 1000c2d4e0a71b4d0794f806e3ccd6a4d2b260c42ccf2face1cff33c210b965bc1da
backendCommon:
  secretEnvs:
    NODE_ENV: 10006f7858b99042cacf9db76239016cb208f920f689dc2036acea46dda9532133b4
    BACKEND_ENV: 100070c36de58ce18db03d890b5b275a115b6de753be5c4eeac3de83efcae6ced143
    BACKEND_MYSQL_DATABASE: 1000c02e730802aec649ee40eb667b08e0118d48d26f5727d75d58a7db29eda7955a
    BACKEND_MYSQL_PASSWORD: 100095b5266933de853e471358393e0f78778f4dc36a565ff78a76f694288decf99e1ab432d8d67770a2626e6ac227f4ea611db9bf4b4b06aa5b7ab6464d1ee1aa4c
    BACKEND_MYSQL_HOST: 100013f4e2f95167584914b94be3735f20e97c17e80187dd72e8a0456337cd1be6d7
    BACKEND_MYSQL_PORT: 10005cd221a1c4ab9e3213bc22f3bfe91527ac9a3efa6c627477f12c2583fd6a126b
    BACKEND_MYSQL_USERNAME: 10001978f143285d52c64641bcfb9905325b8fe3e520f8ad54a7f27811b564c71d70
    BACKEND_RABBIT_PROTOCOL: 100098b70f5e16cbd2d3f3986a94c3560fc15840e37e39a2245368297b57d60f6554
    BACKEND_RABBIT_USER: 1000ed6cc0674a083d8f3617acf639bdcfcdd9deb8263a57ec591b764735f71424f6
    BACKEND_RABBIT_PASS: 1000d94cb124393dabe920e668c558ec918c42427a18973a3d0f9ddc42bc28feb1045fd7ef42192f05c19f8afcd4cec472866f90df5449c9bfb5647ddbcb8734e271
    BACKEND_RABBIT_HOST: 1000bb4b5161c6b623fe94d4fa3d3d6727206a272d022ab0a75c41ad9d278e3f206c
    BACKEND_RABBIT_PORT: 10007f88a4905edc4eeb09c7257eb5f627b097557beb66a1a8736184c72c63b52e30
    BACKEND_IS_SCHEDULER: 1000adce49412b572ba8a90a127f9d9ccf4412c61d9cd808d7143c2443054485a424
    BACKEND_JWT_SECRET: 1000842e84d7dcffec33b97021d6d9b21e692fa4393fb62834adbad08c7f731d15a790619e47f548860f6eacd6cf17a2ff6613cd7f4a31668019869d0e1f60e222dc
    BACKEND_SPECIAL_KEY: 1000d6af68a33e967bc769d7a63ef2569c851608fd0186bbc509efaaaebb64f716be18e8944dcd806c62b3b14641439b458514cc29b977422c6bae014623b3025ad0
    BACKEND_ALLOW_TEST_ROUTES: 1000ddb96481a02765e8483e2a02b95c79b7cfdbc225d88796e1d1ea867198f8a9e1
    BACKEND_FIRST_USER_EMAIL: 10009d10b7a6040bcd05bcf7c248908e9d3470ba06275f7d4b1ffb8b75deca432218d9356c81612078fa564c6a5a6f80649a
    BACKEND_FIRST_USER_PASSWORD: 1000654019806257b40499141222c60d7d9e05caae56a55626b8c2c0dd5ef2315fad
    BACKEND_FIRST_ORG_ID: 1000ab66ea0d8d88629831d79cd3171fe128d0c660400481c3950471ff3070aef4be49b1b4ff93c7781f8f3cceffe2ee3623
    BACKEND_FIRST_PROJECT_ID: 1000d6c2d13a5ed56f339facef935bf54156bb4ed67f986df3bee098385a8870fdedd4879555a2e864780b89d69074147a89
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 1000bdbb3bcc9fed5837818227b48e0066d4e66901da6aaaca26d20b7aeb30b28da7
    BACKEND_FIRST_PROJECT_GIT_URL: 10009f29d00a11d0fac5eaf63a0ec72deaaf63f93913bd8c33c0587c2d16bdf58bf7ff109642fe16af190c7e3aa9992159d41b324fe91da95bd18fbe5c0f2f83ce40
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 10007baef30648c7aacb96bc2bb319bdcce31d9a938144f8d001f36469e31187126480c51fe953a296e0488a66271131e5882608437ec3dae832ecdaf8ee8aadc957
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 100073cb1202f1e389355586abfb745d9a5539e3afc826b1df74119fa5a4f41fc286c0ab9c80425a6dc6df55379b95b144d45dd9b3bc6dfc53fd7cba2b46314b8ea3
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 1000b877ef27b756c7ae1ab96f644a549edbd372fa89b96845d5c3ca9c0ca7c504cd
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 1000768e2ace73fdff634d377a6cb7210e18ba137692e9be66b25c6042fbc83eff8725bd8c0c9f38a447422a498f4298a7a26d0a4683a989f9c11bfbbd3bdca3b440
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 1000d5f1e1d8eabc8fe4eb7e359ed674912a55cc53f66580e72865fb38ca278946c072e6d4524e57bd2eaedf1311990adfe871d42fa69971b85a0003b43b772385de
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 1000e2a8f936aee90e3cf9616aa06b2fd2dbb0ba7b5a62db7e3e5a5e1c9c5bc81e9f023f91b8bd4aca9fe6e5dae4260815ea2b38bf53cc2a80c430d27b53ed2bc24c
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 1000f7a1df2a25d00dfb6942492d99f595470b5dea38cbc869a893aa8b4db2c27307913be601c17fc2cac3048e087f189d9a
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 1000ff499434922959e3f5158bccc650d12c36fc09e85777c23076eb7143ad8b9f36
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 100055423a36c4c0b25cc7865c078ad3ebaebdd911664fdbc7de6b708e511ca4f25d
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 100022b14cd0757a18770f6a99043f20d10de3c17bf195563b33e57884307707105125ab203812dfc12d39029830505a9483
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 10000cdb5be5f3b601c7f744d5ab82203eb35b4a1527d4acd665dfd23300551bd94d
    BACKEND_REGISTER_ONLY_INVITED_USERS: 1000a39f57390d00e2a69a947b597d8603918c7f1db1973d4f78e665d39e211fd757
    BACKEND_HOST_URL: 10002a395a93c887bbbbc6157945a875b567eb463db760826315f0f04412121113a9a909102ad55dca6edce063e99f0b622c
    BACKEND_SEND_EMAIL_FROM_NAME: 1000a54427bcc323f5ce0484e13458722e542aa91285a96c983bfd9be6f9b78e1368
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 10002bde2fc3683313066072ea8d85236f4674ed5cf2558d57614db517f46696e1bd124964c09848154470f1b81f80dcc6fe
    BACKEND_EMAIL_TRANSPORT: 1000166e90a3e9ee4677b2f2a6101f058a5a58dd0b78575d073c61b8430d62b1652b
    BACKEND_MAILGUN_ACTIVE_API_KEY: 100037e2e8ec4e0bd7f13037bb91b50351e29f47c97bb6a5675ff223d693c5421da8fd410d31db908928e325c2c9e846ec6c6cb2b4b86be1cd747c0788604a4a370c
    BACKEND_MAILGUN_DOMAIN: 1000bf34dd17bb6b934b32396170205de9a573fce826a0076cdddd60a0e051400d26
    BACKEND_SMTP_HOST: 1000d61b6c06c898b6a90e95e162fdaa19efd851578fe036d0d1b4c7796ab62b789286b95b390164b9882fc3208d17e4e6d175fc75a57a0830372560678d49ae87b8
    BACKEND_SMTP_PORT: 10005266512029f568a13ab1aed556cb2daff0d9bfdf724a4fd384b16d01cf195534
    BACKEND_SMTP_SECURE: 100089c6fcb83a8b04f2edbd9796745d8facc5364d62575690e1f5ebe309bc4b3cff
    BACKEND_SMTP_AUTH_USER: 10008b4b7ee519415428c96a04a0310355495aa9c747f1b1cae650b15a5bc1223d2fa92ea01b1e674f0a80692feef9558112
    BACKEND_SMTP_AUTH_PASSWORD: 10005337655ddd502a213a1b2d4ebb3ce9a8d6eda3a680aa2469243b44b339cd25e1efe2b5a09df877d01bd34d823c42781a7c0ebd75689a66ecc1bb97a8cdaf25ca
    BACKEND_LOG_IS_JSON: 10007240aa42d4c70ca59333b3dfb60e39beb9ee4d3af83a0bbbcfdec313a87924f5
    BACKEND_LOG_RESPONSE_ERROR: 1000d54571724081ec108efa808e5be7d572e1515757a4ae78c2e2b7a71ee78ce01b
    BACKEND_LOG_RESPONSE_OK: 1000b12776c754c2417c613c6a21a1985853a4438081449cce037ae1a760e7c97900
