ingress:
  host: 100005506859452d352b213a6ff174122b5f2934bc99b42c1eb1115f97d487f709c21cbc8a55f510e08682bed2bf65c6ca12
  certProdSecretName: 10007902be778e93d37df66326e04627af1d521a63eaf6516cd0812f0cfb2dc64611be76c745fbc8a3a2437d4294d964476d
  certStagingSecretName: 10001c1ef70bae2684de0ec517453a8b1258eda773696c9c228c5780fc5577f8a2536e31d355a62a6585f598c2e3a40118d4
  acmeEmail: 100088779966172e819d5d7f8ac2c59d601f43e34909af7180c5f5380a283748f6f529afc11c22d03a5cb53042b3f2a76901
  routeGrafana:
    enabled: 1000e15473cf83847ac02680b93d041f50f2f84549e7e00dbe07313f2d30efe6f4d0
    host: 10002e9eb59473af7ebc927050677ba91d5872e8e959e059cbbe450265a75b60e2d7e284e0119ab76a1d997fd6ea619e0662
    destination: 1000726b67b10e97a7844e95cf4b2274f2ee3cd94511c6862c06e2f56e2687e82273bb1c0b47678dd795338fea0506ea58b7057ab34cacc688a034bae921aa42e4d47aa0a76817c3873dc7479e8d2c5a0d99
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 1000c34ddd2099326da6224e20717295f3638bbf089389d476721fcaff86296d721404c3ae8eb6366577ab77956b98127561fd45218a5e6f4ea802a8e63d3f6e8981
    MYSQL_DATABASE: 1000460a1546e8129799559cc04563a89cfdf5179ee34e7135295e01fd7afa4e26dc
    MYSQL_USERNAME: 1000b0efc2078e710c056fd8de9ba9049f2189dd69030f84ffad8965d231f636b953
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 10006fb289713d79ec2043b6b790bed589263d8bbfa2e78156d34b4f15d535ca95fb
    RABBITMQ_DEFAULT_PASS: 100052491c4d0486c4de0425ef5653966f5f6045e9f63485106685181289579c59afa6aeb1a86f55b629d7193640499200b30c6122bde53052df0edb6d27829d45ca
    RABBITMQ_ERLANG_COOKIE: 100032c78ac32637057d00e0d1d10835b8c2d85b08f09509329376046612c83d52a70fa6746356dd7644b8d3a3a21b0e5b0226c5106c1b727c6f938461d9ffdf9465
grist:
  secretEnvs:
    GRIST_SANDBOX_FLAVOR: 100096b4aa98be2ebe0db0a722503354046ea224baddaeb90570f2976bed11d9aa20
    GRIST_SESSION_SECRET: 1000067d7488a1b766b64eda66c0e68378e251c9e27e9a99cd81fcd84fd2fe644555e6e2119808888432887acb4a2424c05abcbda8cfebe2e105cb09792346badfed
    COOKIE_MAX_AGE: 100073cd352aa7141cc3c41446de78b355b9c28ad5e6d22266cd992900b941c15122
    MPROVE_GRIST_API_KEY: 1000d34106c1df3a201cae141a5cd1b1de396b918c1011028e45e45ef39829bffdb8ca6dc851002f883ca5d455ba80e46888f9893890a890ef27ac9e5142663058b1
dwhPostgres:
  secretEnvs:
    PGDATA: 1000c29a085055c965278b55af14d7b84ca82491f6c3d63b83005e0acbc23710590022a96a911d226113e257212a7a33db7c
    POSTGRES_PASSWORD: 1000da1b63c789367fe8ca323fe8bab31f47807f8825ebe627657e65c79c38c6fc7c700af8f4fffee455aea51fb8d9e13c2f9379ca35875a68a9ba7d3ab40f4b7ff7
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 10004b14638fcb3faa936fd6234e2bdacf23301209c85efcf5c9762e7ca512eb3b7f
    CLICKHOUSE_USER: 1000e9f0c1e0a4390eb538fa9112d31da7e0da6a5aabf7a2f05698dab4d30cb0b9fe
    CLICKHOUSE_PASSWORD: 100027e675930f33e7fadba535d7f4993710c2cd1e28a0e18b7f8d05ef18d0af2bd1825230ffb46a7375e54ff407600e79b2089d3cdc27f0dae029b389da753b7e21
mcli:
  secretEnvs:
    NODE_ENV: 100024165f626a3d8a246269765941184715bab978176727f6243477c9af1c2d7bb6
    MPROVE_CLI_HOST: 1000ad219d2451404146a250b46cfd3abc963c6403058e79712fcf7b7453fd38b6b7f4b8d69e44b37766dd000aa6ab282bb1
    MPROVE_CLI_EMAIL: 1000c003467d720024d3dc149100d865fbd3ce615c0d4d6e135afe417979bf33f5a02bdfa187b74ed207ba4dcae54c5e2d9d
    MPROVE_CLI_PASSWORD: 1000b0d8154ce153682154743fa4b97afa0bd57b46ce0467d1436e0b1700f9328ab8
    MPROVE_CLI_PROJECT_ID: 1000bb8a0ed5eee4a5d5d7ac12936722bf9edc20f8f7dd80eeb516d3928b14fdb29e7f9bc5481e947d826f304c17838762b3
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 1000b1c7d2e2004e3b52da4eeda072c0e2a91047b88d995399593b7c5256bb0d0a7e1bce9beb2ece3e0e92dfb98dba8d3db05a2d94fcccb2d320b67ee0daa4c04057
    MPROVE_CLI_TEST_DESTINATION_URL: 1000d60e4d865dc503a87ff99968a191a85c695a03c2de04e2caf31d8364c81d6077c59817fd5211004ca8eb2cf13effd29cf6f9ae95e80b2c3539511a59b2c4f87f
    MPROVE_CLI_TEST_REPOS_PATH: 1000b4d14c021f30f96a11a2d3fdec91898e363cc457508443a1ae0288fe160f969e1c152968602097ae678ca1b5f7f32ac5
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 10003356c593ab9a8939aed872be35792896506aa916c37fa7618637464c044ff66ec8c1d1140f022967a152e62fda4d33ab74a51f2adba615c5aaca61f4463b349d0f7475652aca5d55ed9e99f7cb44a71e
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 1000e3b56e4eea1882c323a8ecfc18d9bdc72d80eac1d4ce8bae59aa2c9cfebe3473ec42c8755682dda49a74a0189a6da11cb3c7b89ff49def587e1d9456b63b40b81e59c3ac639a6d933497307bf78a67572bb9d6f4d7e4b100e3d035f030654cfd6ea6e7c5733b5033b78b4a0b5e77dd7c
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 1000414504fdf446218b6e776c8a87e560780d9ff843da47a59730c1965a8aa877f6c2f915535bbd3addd066dd628ffcd1b85b3f01eba9aa8cc57385b844bf175c14
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 10008e3044d777055a96271f903602d5f0db8c661939114925be6482c653b42068a525a6ccfdcbce002e6beba163773ec541a25d7d46fa3868b636c2133acaf4e34a
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 10002f9cb0e318482abf1e776989d965f2669f84d61c9d8b8be98a6bff176232a45f94f951fff219793befe5120eef4b7569b82d89d67bfa635f6d8b6473f890c387
disk:
  secretEnvs:
    NODE_ENV: 1000297090e990adf5275e9f83f20356bf27b360387cccbd2bf0c52b77136bc01780
    DISK_ENV: 100008672dbb8dff007ad54d0a8bc5856ea7f943ca49e07dfec5cfcadac0099e80ca
    DISK_ORGANIZATIONS_PATH: 10006777adf5f19ab1c7ca5e9923cc0a06d517a54a724bbc44346119af2be95c68c4ede2f375b0d41d0dd30fbb25a8c23557
    DISK_RABBIT_PROTOCOL: 100071140f7beb83ed015ae3b384308cf0a17e072d137278ff96aaa3828834d1281a
    DISK_RABBIT_USER: 10006af53e867e91e22f3a7698b4dd1e0685a72726176b1a3f4ba78f9fb77c4c328e
    DISK_RABBIT_PASS: 10003f0aa9ab07c868e0a0c48b4f589d173814a36984bf05bc8564099d1d7ce37296e26d6bcb1120a19d9342daf424734eebad6f056bcd3cbddfcdc6a579eac41efb
    DISK_RABBIT_HOST: 10006d017eb77e4a7e49e2479d4809af117ab0641dbde4d6db1d3b99887e6afde57c
    DISK_RABBIT_PORT: 10009b198873bccd13bb31f4f0dbeb932e14f1aaa9ec5c8c7b92eb75f166976a8fe0
    DISK_LOG_IS_JSON: 10003b0d6f9ea164b80da57e478da7b618d7dd1fd9fc12b24a67d636f54c99bc8915
    DISK_LOG_RESPONSE_ERROR: 100071829a9bf018fc85702b6444ab6918164cbbdaf40a7d85d23b3e06f357ff9233
    DISK_LOG_RESPONSE_OK: 1000a66e4f866ffe8934127ae482b92de60c7e5b22a2b17e94aead9ebf5b4d508b11
blockmlCommon:
  secretEnvs:
    NODE_ENV: 1000483d566c533da8afe0583ee7138d593e8cabd919f29d5727d2f87ae1c521fa46
    BLOCKML_ENV: 1000cecec5bef7daa1661ae1a235d0cd89c777e09a237173b3c63ec55c1e4b2515b6
    BLOCKML_RABBIT_PROTOCOL: 100048d91fdc7c8a727f05020340e3e53533e6fa21796a879ffa2d7d931889367fcb
    BLOCKML_RABBIT_USER: 1000db6e4350620729f2fa9726a34c8df872057de03321b188b78fede3995b4ea891
    BLOCKML_RABBIT_PASS: 1000187cadcb2fb4d48c3a176e3c0272e3cbf49082c0fa288c20b4d96f46242498088efb517d14c8f3e06c69aedcb26121719dfb52e96b028e1452ee8917b8667f3f
    BLOCKML_RABBIT_HOST: 100090855ccccce1734a8da156eec6ebb1df3e774fbf854368c0eccb183136513797
    BLOCKML_RABBIT_PORT: 1000687f8d6abe966c0dab7f615a6b14d37d5540baaf62a0469be7b5b1abf7a6facb
    BLOCKML_LOG_IO: 1000ba197b8156953a5cabff77ce9356b1fe20ef90e2c1a35ce5eeffe00cf70f0f06
    BLOCKML_LOG_FUNC: 100062134c7f4560499f3258e097e7000ba8b53ceed7c8ee65b59a84ec787ad92089
    BLOCKML_COPY_LOGS_TO_MODELS: 1000c3d7867d0a2d4743fb0292da278ac7b6671a01a7f59fc4050c95969e7fc6047b
    BLOCKML_LOGS_PATH: 100083632a342fefb558e67fdc9b532e207d2ac9770568ee23bd516b8aaf4b258a247094de422c5b9109fc49e3b75a6efda8
    BLOCKML_IS_SINGLE: 100082fde30d22e15b3f5b0a12d570f91c5cfa6aacd2063228ad29163c32eb63f78c
    BLOCKML_IS_MAIN: 10009a5e06f8591c393ff3da90201d943b1960eb507ad93223544f8ad9834305253e
    BLOCKML_IS_WORKER: 1000db20a24c98b434dcb51a1f8db66b443b8ee26722e781e51475e3e830cac0c857
    BLOCKML_CONCURRENCY_LIMIT: 10001576cd8fb2b52adab8741c2fa97e3d877b85d976bb809938cd26dce451cad8c8
    BLOCKML_LOG_IS_JSON: 10007a7f3edb76856a24955be3597024003574fb31fa9f8d0df4d7b4b4937fc71115
    BLOCKML_LOG_RESPONSE_ERROR: 1000d8c4756a037eb8de052014ff9fa304a3f3c1c82aba2b1120d2657c0a66cefa26
    BLOCKML_LOG_RESPONSE_OK: 10008ba0fa9577c60dac4b8d63aaadaa6557a5294986cf55045cf77660a61ffc7c51
backendCommon:
  secretEnvs:
    NODE_ENV: 10000aa0640ceb6a893b07fdc7fa56092bb771d0068383b86ec8ef51fddf357ad16d
    BACKEND_ENV: 100091b3082c25c5413f7acbd53b4c40071ee9148714b1fcc5d994009bdf3a4bfba2
    BACKEND_GRIST_API_KEY: 1000dc847613b35811a54397d2e49c443b50bf132678924d58246d5369438a95a960eef2808c79c166945b6d17e2742d5727fd4aee2ee68e529d48353e2e209955e8
    BACKEND_MYSQL_DATABASE: 10003a056eed8dcc135e27b9ac5342ce00b7243860b9df218496641f50d4c7cd45a7
    BACKEND_MYSQL_PASSWORD: 100087e1883141c55675052b5bfa044e5812a06b9547851a257fdacfa293620660dd6182e7b85ec4f7019a089e0d5bf51d193a922ca227b5dc02704ce0be782de0a5
    BACKEND_MYSQL_HOST: 1000129397313951458cdc9d41bf44a75c2391e21ab3fd459190975b17abc26c4566
    BACKEND_MYSQL_PORT: 100056b886ab51b4640a9e884af0a3a1827a7401217e0a208603f722f76e88aab661
    BACKEND_MYSQL_USERNAME: 1000ec0f23ad37fc3e587571a1828850cd704f365fe0ed413e5c85404fbefeb8d23a
    BACKEND_RABBIT_PROTOCOL: 10006dcba78a358cee3193f5c5d2511f8dd511074d46912578de060903446e77b20a
    BACKEND_RABBIT_USER: 100073acc71d6026d16d41f13a2b67ec137f31a698236b8de41fd11a938cdaa0c1f2
    BACKEND_RABBIT_PASS: 1000e161416a0cfa535a27f8a4cfc549f7745251e5b1dae093da1c4f10ceeddefae7a6f3f05044e8542a6c8661e89110900bc950eb35692659b09cdd34bd1d72e597
    BACKEND_RABBIT_HOST: 100001f90d5aac75aa6135a7b03b0ed3cdf2f1089b069dd60c9db5306f370e3e45be
    BACKEND_RABBIT_PORT: 10006ac3b4e21890b05a3f4431fc7277c7005f1113516d5c49d52d59ef96ef43798b
    BACKEND_IS_SCHEDULER: 10000f8c176530c45d880cde31875d74a5471c295af2f9eb7817d79af80fc0fe898f
    BACKEND_JWT_SECRET: 1000bcbe6669471fe59e745b273bcb4a5635cb1f64b3e1605fef06a543b90cd3d9c899c8c2223adb92f6069fe9845f7158d143dad9dd62c1271095ab6ad21669ec63
    BACKEND_SPECIAL_KEY: 100078a2c9fbfa5b36a0a4706cafd5e385d4e96ca146ef3e19d16f1d098d5c34758f04f1055b3a04662b8b9259bb49b445a8c3b5c46439317bfd472a2bf077be750a
    BACKEND_ALLOW_TEST_ROUTES: 100094a4adc59b5a242da5257f0bbb669d7630eb206c8184be95db8a0c3f342b633d
    BACKEND_FIRST_USER_EMAIL: 1000d18fefa47105593a694d6275897a4bc331163a06fab7736cf17a677d82b2720576257a29ddfd89eb4643c97f7c4b5853
    BACKEND_FIRST_USER_PASSWORD: 1000a77790cc9fe118cb65fdcef59aaadf1a70eca7b867ac71844cc879f29a810ac8
    BACKEND_FIRST_ORG_ID: 100025b266218c7357ede5a36532422a03ce12446df846b87afde4ff2a47a5a0f50e46277a7478c0b6ead7ac523fe7f7e6ad
    BACKEND_FIRST_PROJECT_ID: 1000e1b5f7a3c59ac1ac1c2fcfcdd8b4a97c504c6affcbfdea8065bf2d263ce48f9a819f15115be5dc785788a82587801318
    BACKEND_FIRST_PROJECT_NAME: 1000058bfc3334243982a16855338767b3e40d0c6d521ca1ee2608d8d4c2b2cacb46
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 1000c00bc126c44f70587f33ce0aef077c1a8fda87e968d2ceca2ccb9476b7f35c37
    BACKEND_FIRST_PROJECT_GIT_URL: 100027dd88611ba0eee83da95d4d377d13c3a7d8b4a17fc6607e69ffd761c7f4d2c9479e6ef4f73d61864f8283e5a88cc556e7bceb4e3d2f5b3f16af60aa6238057d
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 1000a43ebad762866792454300ce5241b692a94753c943b729bae087faadc78197bd2eaf02e519598f2e34a548c037d0073930c33f5622534d0f4e394ba1b968cf8a
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 1000ac0fc604478cf40abebca01a86dd0be2a08f9c513d3ef0b9c91ccd6ddcfe4219d846a17c609326cd658dd623d42ea7eb446e351da3358f6d668c55b6454a7cbd
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 100084d3d3536d6ec2890cc5ff2d8292b9200b2574298b6bf7d33dcee0c067b42451
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 1000c6ae4d5fd0a7f585e21827a0f39cc9b3f7e8bb973c6f38d4876382ec00f1adab5508328e4dba86acb73994083cdc0fb28d0cc89815ba26c9cd93bfaeaa602a04
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 1000c4ed8d2f0ff51a1256a4852e8796ac7ce7a8746e7477b03e339cb7cc883dba45e8be3658e7d9473e03619a0c6a9fcf71ebca5a220538acd01a43f2f26c54a48e
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 1000f4c824c16766108ff93aab13581bfee68f5e0c0eb3ea3aa5af842fc5ffe1b47171bf2efe20462d06ed8b4a814e64adbeec24c6ee30d0bbb1ce36ccb1f555d57b
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 1000f3410e6c024f1bb19bfea2de38479ab0a002d1c36440b19655cae9d9188fe387ebb90a8851fd02671a7fe5185d359516
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 1000aba505c49a425117978b8ffafa47e4f8facd64e5580bdcaed0ebc9b4c265635e
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 10002d473d564175213631b988230ae0978b744e01aa89e98410ac26ea14f1d3acbb
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 1000478f7002f1a6a2a30a16d9ea26e674226ce5142cdd2b87663d1c1dee5142e91fa6417b5a43f91d7ff13568dca68220f0
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 10002cc71783385833390a84e376e7299eea7cccc853461c980f4862b929a73204a1
    BACKEND_REGISTER_ONLY_INVITED_USERS: 10004b39ae1ba1ef4536341a43ca3c2731b6a55c8bdf1320485719d2e1146589666d
    BACKEND_HOST_URL: 10006d43406ab54f098d73d083de353869de0db6ff7ea66a4a57c7863b53004f04c7e693b30106f63178eabd5bc5b0c78d5d
    BACKEND_SEND_EMAIL_FROM_NAME: 10005084318569e6759cee83571fdfafa562a15356b0965c56b99aae32a9a422d3e2
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 10003711e5c1662d47a704fc7a677fa1cc0d82da0094248979dadeda4b3288e57a576c6c34a676d7f7782f1bca6efb067f37
    BACKEND_EMAIL_TRANSPORT: 1000f37e7ebc42513cef331706e76a252053f21ce4857b12f02ddc0a1d6bcdbeddd2
    BACKEND_MAILGUN_ACTIVE_API_KEY: 10005eb896d26c87c71e0d4eef5243cf2a6459b0f203d83ce42caf0f314203700bb5293391bb899d252a94ea7c68cd5d5031faae23921787954f6fec2765a95e2c15
    BACKEND_MAILGUN_DOMAIN: 1000e4cc0bd7ab9ca0fbc74342b26be842e0935af965897d1827e9316d557f4fc8b7
    BACKEND_SMTP_HOST: 1000ad8ff8e0e6a6f5340f7fbde52ffaee2e559e8cb156eb3e00355773a3866c9b2087f940cf98f775b9e2f54d8f19f27fd01221642fdb92d9962e4fc61cca37ce57
    BACKEND_SMTP_PORT: 10005453d23b933b5f9f0375797f9882ea0a2bb4962086e279347a38e48dac083a3f
    BACKEND_SMTP_SECURE: 100063972be954a7b5ecbd9d911528a1da42ca3ef181575213c2b1e991c18333672e
    BACKEND_SMTP_AUTH_USER: 100025dcd00c93fa9233a8bac66a9d3f852334bab5c09c37ce8f2bf52b18ff1fff273ab776efec078f0772e6b914dc775c34
    BACKEND_SMTP_AUTH_PASSWORD: 1000c80e66dbcca2e8f267874d93920705bcdc24c45ee33f79b1dedb5a58e7894940b39f41c117ebaa3a363369494dc3413b24452ff7763ee70416c107a5e11db01d
    BACKEND_LOG_IS_JSON: 10002d881ade8889b06c40f2ca8bf8f156c0cd4b81939655ea9a25c0d56fec80b538
    BACKEND_LOG_RESPONSE_ERROR: 1000950ead02e8a225e7bcba62dbb632c182bc409e1fd26d1e5acfa4942c1d748f8f
    BACKEND_LOG_RESPONSE_OK: 1000e2826b97120708f0541f4e7e00f99787d144959446066453fabdb0fcb1d06fae
