ingress:
  host: 1000a27f633b4069bb4c6cbc54c3a1c8a88f9d924b8752f732e273e3694842ac50fc22d2fdbc7b450ba5c668e9b24542d3be
  certProdSecretName: 100040991552149bd7d345f95e2b2f76e3ea662be46fc41f5d88f4f531b18c16915f4704b80861f4c30a743ca9a4b8728737
  certStagingSecretName: 100083e3ae909870736dc718aed12a57bb1f1eb64d38165f0c084a78aeb0c2e433777ac6d40e62386a549f00239bba920abb
  acmeEmail: 10006622e66daf92371edee6d11631f8f6788236a163ab8dd8806f6f0e57ef8f555443e0a79ff43aaaa55d4d584d39d39588
  routeGrafana:
    enabled: 1000cfdbae4a5b43ed0cd288df9c746bc606617c8b4b5975c1614dc8e6edb5f3c49d
    host: 1000450b3d9daf370d6aff100142c90a6964c02071b9da04295ac732aa95fd1c67de5aae67f6f812bf373535aba63381952f
    destination: 1000392442c900bd9b3389f3012dbb00c3c0f4cdcf6deadd19eba1b0a712dbced2ea1a3a05c0cb0d9a59dfcb8ee4b780a0e357f90d34f54374a42092d32b273bd0a7178dc52579b2ea49229bf1ba0709357f
db:
  secretEnvs:
    MYSQL_ROOT_PASSWORD: 10005c99d85c4311c8a532bd472bf0b23ddc375c341aa4eb01916abc5ca02ec4ba918499fdfa73f492e883c07769cabb1dcde91403dcd2dcf1b5a28fc274e31f11ad
    MYSQL_DATABASE: 100060fa7a0f26cfee6f3b3ed4cb9e0c8a6d8d47257c5ffc61ea29a00c67ac3c6cf5
    MYSQL_USERNAME: 1000364671fd0e86e7f6c718caa4c5ef33dbe473e4f3638e43c96d8896889c88f91d
rabbit:
  secretEnvs:
    RABBITMQ_DEFAULT_USER: 1000ccf81c9d510826603d3dc08e01f21c839d65a749fbde4cec4338d845f7bbb0d5
    RABBITMQ_DEFAULT_PASS: 100073c3e396f00636a1ee6ffec25fadd62bdeeac0fe614f40446652eb664058227b54cec4fa25e73a949fd62a682994f19ce2adede025a5fff28cf3d9646d77ea21
    RABBITMQ_ERLANG_COOKIE: 10003b1e4bcd0adb2c47eb87c1a2e1974eefc0db849108741f364f85d6bc984ed80dc2927be364943fd70ad5ded0b425da37c30c9f19456ca507cf041f515373a6e3
grist:
  secretEnvs:
    GRIST_SANDBOX_FLAVOR: 1000b78caea834862ee849a71c03ed7a2eeb23c899426b8052ab6ce2b6d5cb4ae96e
    GRIST_SESSION_SECRET: 100030777603b68c45b744c2b6984a2b12b6e813d0d29b346bf4d50bf65e0fa99b771806f68835ab3f29d8f6055581952d54e8e3e1afdaf801d384ccf87cf5777c18
    COOKIE_MAX_AGE: 1000cd60814c3189b23549fe7c4492a75e50fd949ebde57b01e4037da59ebc28da4e
    MPROVE_GRIST_API_KEY: 10001dbc4f03e5d937d14b9cac707c8e56558f8da7baf15a86530a74adc9b4bcf7245627d922ce34adf39eaaccfd06b8b2d5614640306efba8d6a7d01af33356ec54
dwhPostgres:
  secretEnvs:
    PGDATA: 1000b8c95f1f3f96e7f9e6f034d46ac9e24f6097c3495f2f9e5094876c19b908c01bfb35c74e5c0d34e3539d261ae88bf49c
    POSTGRES_PASSWORD: 1000dc2536b6743445fe02672c5ced98f288add5dcbc28d6d9682ee9ab777a7969835f22689c186ef0fe1b465e16ee51ca17697086d55df3834ef6395eb8329b21d2
dwhClickhouse:
  secretEnvs:
    CLICKHOUSE_DB: 1000f55cfc16582246a13307c355f2ee14b317828ef4073cf9853ccd77ccc7ed2445
    CLICKHOUSE_USER: 1000de073d75dad4b8b0ff98d4d67a997fd2a740ed65cc0958b5277028a2d72fbacc
    CLICKHOUSE_PASSWORD: 1000f5a237a1c66866b7c60f3f8cad1534f7e4da1f47fa9d4e188d8c672d6a0a4a4892f82f79abb0f9ce69417becdab631920711d7facfcd974ab38980027db1cf52
mcli:
  secretEnvs:
    NODE_ENV: 1000568280f42b99ef73fe4b074c8fa864d7ad48d3fd687b5d25e1355e1e2bc66a82
    MPROVE_CLI_HOST: 10002b9f894d7d8a478fff72b0cd57213c3f13c7563dde87c20750324904b25a469aa711ce82110430af5f7c06b09d2bbca4
    MPROVE_CLI_EMAIL: 100036d99b148319a03e2df354402b0372c35efb29e883fc1b3b26725bb16c055cb37decb294038d5b9a41e17bdd44e58b59
    MPROVE_CLI_PASSWORD: 10004f9b269694801a402aa8dde7f772217f6f87759483659ebcb9cf1c601d37ed0d
    MPROVE_CLI_PROJECT_ID: 100032d8c9a9c4c9079dd7ffdc1c24679df2464b50a8bbedbb558232eae093a5a4395b19f7261b2630ab489391b11e066b70
    MPROVE_CLI_TEST_REMOTE_GIT_URL: 1000fcb87958b0eae40b3d8e9ba268566cb4c47939165afb5a7abff599b115d5da59abb3f28b175927a64a1b61b4f660227b25b345baf3a34da2aaa59a7838de997e
    MPROVE_CLI_TEST_DESTINATION_URL: 1000712bdcf5b5831226ab9f6be81f6ad3f4c086450ea078018e3d8a5c322d1017c7ce58bb17fec2e5adccbc7716e5d60fc40c1536b30e374dce6c51ccbb9159eb08
    MPROVE_CLI_TEST_REPOS_PATH: 100013fe2d358da046b966e0a22676b97b7ed86151529ebf39da08235c77dafed0fac50f784dcc3689b29c3aa7436e722a6f
    MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL: 100050c55ffbbd0b00a4decbf4d026d25d3a79adb1eb508dca73a890a2bcdc0c3e2008fae42b68c704a7e80362b4187a28b7f6605ba8330a34f913d44d20760a8a403b0d8c9592cab6b7e61a5d46cd1a1e14
    MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL: 10002b3e0ddcaf86ccc63fea7a1e99280fc471f1213a1792fef306a85cc41564ea9bc71ce09073724e46440c27982b32f03d2e86a92a975f23cbfbcd9c00d4bb8768077106e5d6de91ef6a8d912471536e0a5ae94fa701bdc61fb799ed194fd866d4305920d19a586b9cb0b2ce704d162fa6
    MPROVE_CLI_TEST_PRIVATE_KEY_PATH: 100043ba97fe13f9872474c916e3958bcc9604e9f39833f965c8994f1384934956d8821d10981b0af0a0f55341255d856b9d828f950ba7109479492ea6a7fcf0f4d6
    MPROVE_CLI_TEST_PUBLIC_KEY_PATH: 1000b58ee194e8868b617d230223b37dda06315316b25cb9f0674fff3a41b0748f5593a1237c6f2fe9cd8353b7a7d94aaa0a089b344f49d5103865e287a48d07da5c
    MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD: 100099a2918206b22feac91c9bb4a8c4250a7aa740e8e8449e311fea3496666b4dfd106ca12baf423398ef4d29e8e5071f23202361b4076850195019eb5d1a7db5f3
disk:
  secretEnvs:
    NODE_ENV: 1000db3c4709ffdf988fceb330d33a3227237fc6abace009391dfb40d85c2e518ddc
    DISK_ENV: 1000b93183f584a319ae29dda047bdefada75c5259c354bb291cd5c8408461a3d91f
    DISK_ORGANIZATIONS_PATH: 100095d705061eecf9db8900ddf34c16e911e4daa8045ebc9c1fe1c6fcefb4a9ed16ab6e7ea5c8a30e150e76862dc0692d86
    DISK_RABBIT_PROTOCOL: 100058909c5ee923a23da4f3809497e2687148847b9fc7f6c6839f2920920f6303cf
    DISK_RABBIT_USER: 1000df59dba28021ef5f0c6d0368fa40c2bd0afacf9c3744419d3ea025b5a14e002b
    DISK_RABBIT_PASS: 10002677144702dfe2f2ce39682a3b1bdae21353600fb14875847213c89a305d7487881fe32b7ccf248205ac48198b31ac289f3b9045266e9f3b1804e32108d1b4ce
    DISK_RABBIT_HOST: 10004ccd2564e4a54bd77396db7bf82929e32b46023ee88c229894de73afc1f24782
    DISK_RABBIT_PORT: 10003d3d691d933d45a41c1c49b491db854c0c2d7a1e36de059e684f519686b2882b
    DISK_LOG_IS_JSON: 1000b978a9a2a45b12d6908f68a064d308e51a8f9c9fe467d654868297365057a677
    DISK_LOG_RESPONSE_ERROR: 1000bab8ccd1ce377d0c3d13817cbf109b7f4961841fd5d1f9cb065b3ed0175495f9
    DISK_LOG_RESPONSE_OK: 100011e47546d9c1e8772c3eea61cc38db59bc80c91ccebed61255809b9c431182dd
blockmlCommon:
  secretEnvs:
    NODE_ENV: 100092e3db336e8cc4b55fa6ce512c468f2ae2a6685a602f9687cf765f2fa8c2daad
    BLOCKML_ENV: 1000f8e833f7161a13d6765064de0b8b5440269792a80adbcb6a5dd32082d8d866c5
    BLOCKML_RABBIT_PROTOCOL: 10000abceaed83b265d1e0b385cb92561b57e0b0d531de9e517f929f26586743609a
    BLOCKML_RABBIT_USER: 10007464fcb9382979925eb8925c1cf9cbbebde8c0082fd7ea59e69060247bd92fae
    BLOCKML_RABBIT_PASS: 10005ed424e2ec857e83364e4cc8074a3fb0a24afee487292fbdc6d4961f7c88ceb1b2fbdac35e394998768cd56c13f97500d16c046eef5dc826552a275b86862996
    BLOCKML_RABBIT_HOST: 10006fdbe274e457190f4ea2adf8bb35ea3478922aa2e625c9d07400ab7eb5c00399
    BLOCKML_RABBIT_PORT: 10004b60e44986c1a28bbd03f45eb0b8b63ff0cd2ec76660e90bc7df8cb71542ef10
    BLOCKML_LOG_IO: 1000144ca58d2c50dab19147ac8ddee31c975aaa9f9eefea8a75040156a9dd9e4aa8
    BLOCKML_LOG_FUNC: 1000a89d921a6474cbd30cdd608adef5ba41b940dcb73147802ea042c902a11591d9
    BLOCKML_COPY_LOGS_TO_MODELS: 10004d8ecb7aedaa71fddc12bc13feb155c575225f386f4134a824ab8aaab3a9bc97
    BLOCKML_LOGS_PATH: 1000885bd02d57efcb7186cd73bfc61f431f7409ed34041d547d51987b2b7c06fcae1489e895bd5070943f0eb6f8fd2ea87e
    BLOCKML_IS_SINGLE: 100044ffd2c9272d9a0209003e0432cb1ae06201aeff261392287e7b1211fd9ac156
    BLOCKML_IS_MAIN: 10005604e7a4d83cd994334fc4d1d04b8e97205661cfde9c09f7c769c9f41cfc570c
    BLOCKML_IS_WORKER: 10006756767f23e509389eb63b2935356be33bdc10ac6050473f3da28d7a85227955
    BLOCKML_CONCURRENCY_LIMIT: 10000556997562aabae8f5440be4298900807ea63071e65dc59b8952b09ff1371128
    BLOCKML_LOG_IS_JSON: 1000894c3c978a7d108e4cc3ba6ac30dca58c979d5da3a2e726e9c6fea1fff31cac4
    BLOCKML_LOG_RESPONSE_ERROR: 1000d1e2eceb8b5554e5fe310d25faab3b34ae6f863f0fd145f3009f1965c5c722fa
    BLOCKML_LOG_RESPONSE_OK: 1000cf3d995fa824994df95454b1d749beb8a15d7d8b0eff1aca96fcda192d68587f
backendCommon:
  secretEnvs:
    NODE_ENV: 1000d3776b780ed2a1dc4f33604c08c411f8f0f83cd788bab5573fed3fdb4aa50309
    BACKEND_ENV: 1000e48442a7e48f3cb6f239759be48845eb80863e501af2838b8111ecf11b59713e
    BACKEND_GRIST_API_KEY: 1000284d50c2902fd5024a77fc83c674a1869d411c177c88afefa4b75c8df2f46b2cd426fdc0f63e562c35cc519f9718b77bc53dd3cecd85d04c9a2986076fffdf16
    BACKEND_MYSQL_DATABASE: 1000881bfd6396f41afe7c6a0305c859925b827dc6b92a782cd5aa73cd5240c2fb66
    BACKEND_MYSQL_PASSWORD: 10006b6cbce2d088ba6e5b49a0f745584da0dc2621c3de9f6feeb689c7959cddc5f77813316d1103313d1e7f6151c6cec48fc25293566958681826c58fa9fbc2165b
    BACKEND_MYSQL_HOST: 10005b1058fbbbf54d22e6ab569130b7fe90f864ab5613e0bae67afb88ba315cf6b3
    BACKEND_MYSQL_PORT: 1000e9e72d752a3bdd3e5400a43f15f19c9545d8b538ed8f38ff6ecd78a2272a3a9b
    BACKEND_MYSQL_USERNAME: 1000db47263c9d946fd0142328d6f6a2baf775278c3c297a9b4c029c4b614042064d
    BACKEND_RABBIT_PROTOCOL: 1000ad83222d316bd490475be12831c0de631368328a754156cc9b986d9a5442f24f
    BACKEND_RABBIT_USER: 10001cb0a1c5f121a81663d6414e7f4c7474b049d99148545ab9db38ab55326cba47
    BACKEND_RABBIT_PASS: 10004868a54600963d5c3bd0ee9b777b4b74e355bc36ae4512cf726d88683ff1ceaf43bf86f6be8e11c83d4bd5000176f3aaa8587db0514d22621f858bd78490e289
    BACKEND_RABBIT_HOST: 100066f7e313984868ff532c094ecf89119853eb012cad9476ba1e3dc8600daa95dd
    BACKEND_RABBIT_PORT: 1000c3404d776a3bf33cea3bbc86ce8f6d0b1b6189cd7c13c67fa681ea2005b58c3e
    BACKEND_IS_SCHEDULER: 10004f360ea37ca751a04008c190644975b4156674a3036dabed1d5740bee7d50381
    BACKEND_JWT_SECRET: 1000eba7f5714fc557c1ba2dc9a3b6d5644ed013e1819b15321af495927e77fb8ff43d2a8adcf9addafc691ed92535829c3cf86d65dbc1011852ee9695ff31173390
    BACKEND_SPECIAL_KEY: 10008c717269bf67b3b61847799477348ac61dd867ff7a455f7c2eeab3d482fe7d53c9a1120775330c8fed690c0487ee321127a61b94f7659b19e41d9a9808ccd42a
    BACKEND_ALLOW_TEST_ROUTES: 1000639a8fcc0064ed0afecf9367acd724b43e21ba63b2ab5a10b3ca4d1565d70980
    BACKEND_FIRST_USER_EMAIL: 1000cf298ae66fc9a97dcdd8c442c927a1e93a2953da95aaae752035bc54f291d2dace29a883f0e25443aed52e89713936ab
    BACKEND_FIRST_USER_PASSWORD: 10006fa6123f6cae9eafe847db43fe856ebcaca0b01e8d45d824c05f8fb111a0d0ac
    BACKEND_FIRST_ORG_ID: 1000a5b27ce95b2390fce64d808f7ceffdfeaad1374099c1841844f3c45501b400d2807d231d69634cf87e4bcd0c65ce37a3
    BACKEND_FIRST_PROJECT_ID: 1000a3dda9b5578e81b9c4aedf6c538ee4ae42ecf7bba4ea4d48196ee97f1595503df4e46e690505b6d16f5fa778c01af61c
    BACKEND_FIRST_PROJECT_REMOTE_TYPE: 100027ed4495c8d2ee20666c9b5a98e47e0716c7cc9f6df59f10b818c98910300449
    BACKEND_FIRST_PROJECT_GIT_URL: 1000dfe3a935e63849c653bf6a1a1ea848f9a2a45557fd427e94ea1a160dd953ed51cca23f9ee9eef663f86e12b1ca500af305ba649cfd3e4fa769d51a801c8d7858
    BACKEND_FIRST_PROJECT_PRIVATE_KEY_PATH: 1000598caaf0115ec497bb77cee4f018a5da11b2783cc675ec32600ccb132762b2b087a337e88ea842233266db6ed5ac42afc51c38e4365cd0f997052e1739e18be8
    BACKEND_FIRST_PROJECT_PUBLIC_KEY_PATH: 10002bbd4f9ac5d0a856bf7af165bcd2b7273fafed07285f541f122664abe837a8c5937f923bd52180e98e27aaedd185251ec5da4b94a18777fcfdc747cb358dce95
    BACKEND_FIRST_PROJECT_SEED_CONNECTIONS: 100071920a7226a101d580fee81f3cba7acc666b64ebef5e826d4254f5a882d98dde
    BACKEND_FIRST_PROJECT_DWH_POSTGRES_PASSWORD: 1000e574881a8847c6b60fe30ae8ef3d40c4463d8cf4f8df27217e653036420b8c500bc3a7e50caabc36ffc75cda776c0bd6f07fe4c21f3bf5eb6352ba2c2e90ee9e
    BACKEND_FIRST_PROJECT_DWH_CLICKHOUSE_PASSWORD: 10002bd78482013a111fd2486346cfbd1484e08d094f18f7885908a2f5f9b1f575a71c09cc5f82dceb7980197225aad8e7e826700c9bd4e5d9ef2214fb1219885757
    BACKEND_FIRST_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH: 10001855ec6f690b9a6d35626d929b77ee3d8a1cc571fdf6a0d74bdc4ac74f802060c53e6fd7eda5a5d453b680e5fb659f1af5a8878c745a3bff5a900e4484ffc1f8
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_ACCOUNT: 1000f5f59e385187ccf158d99cf818684e63176342274e2e1c173c8ee97de3e58a3687081d7393a82351dfeebc6356cc685f
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_WAREHOUSE: 10009f83da04ac201c475c9c35287e2f971954bd03ab1bc851ce73c1c791ef3c37a1
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_USERNAME: 1000ea92f289168978f437dd26cfee6474377aa3d62acfebf86816f40ee51f931698
    BACKEND_FIRST_PROJECT_DWH_SNOWFLAKE_PASSWORD: 100058dd662009f73f0d59a450aa191f55b62cfade7e928ce01dad113d400e68f782e89584c77b84b17d81b1e6e95a8551f8
    BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS: 1000e3cb9ac360f3c1dd98af437cb5a077e7bbf675ffce16ecb095d37696fb1a7139
    BACKEND_REGISTER_ONLY_INVITED_USERS: 100078168338a94f3a94ea0f05a6d67edf37811d46eaba15c1cabcd320631f27d7da
    BACKEND_HOST_URL: 1000a8c0421fa205741982053ce7e63e7bc68999e0a4ef8e846dca66086c940f870edba0d4e76cee147130d99ab70411598f
    BACKEND_SEND_EMAIL_FROM_NAME: 100063fa810bf6648af88fa53736190d6dd728d600df5a71986d23849e1bc4244e64
    BACKEND_SEND_EMAIL_FROM_ADDRESS: 10000406c2b1c0162cde13c68835c1562a83529d3ed87351852afc64438bb277f9262bd3d80a7a2420a2109e293dbada5485
    BACKEND_EMAIL_TRANSPORT: 10002f65960a82618ac1fcdd6c13b900e4c4c0a052e14bbbded3f02cabfadc865429
    BACKEND_MAILGUN_ACTIVE_API_KEY: 1000458af51ef7dfa67aae063d21c9471c1ee1e7306429df10d4393b9a234023b4412245c539e72cbeab4fa43036536930f5e573f727cf7dcad23c5f0d1871a322e3
    BACKEND_MAILGUN_DOMAIN: 1000489d18b55fe95c80ca059542f3b1016d11f93dc16a00814371881a73423a9b61
    BACKEND_SMTP_HOST: 1000537e8475367c6ae0449e2b1d94fb6568ecc4650a2fd3e5cab0746b221d00a7a0229062253417417096bad9b1d538f31fa851289c3f2cbbfcf6a63e1c8a92b4b8
    BACKEND_SMTP_PORT: 10008203e5e87e9716570fa5bcab049e04e2c283e23b0c2849ea0c57ca9929e5f807
    BACKEND_SMTP_SECURE: 1000f6d7b5de555a530ee9a842a6b54b75c57d941deb374b85c88aacd6b267d36d7e
    BACKEND_SMTP_AUTH_USER: 1000ecd7806ff84ed1b20db01be8e2e3d5547438b4d66d2640e4a8ca4cce329c7629bdd59737d332b55a60a5eb78543bacf4
    BACKEND_SMTP_AUTH_PASSWORD: 1000d5f7ce6c5bd6ee85a2a061f1da7748cca60b54fb8697d4cd24799805be326cd5a22acc0474686a33f9c2ddd9af0ab1b04772af786d77a97694347f12b5ce3a6d
    BACKEND_LOG_IS_JSON: 100062cf91990d3661a7ffe678e90791a9dcc81057dd3e233b7cdd21e2bc33c5a06b
    BACKEND_LOG_RESPONSE_ERROR: 1000e971e15a3596523d2c33e36173a7ed8f60b0b197fbccb0816b509ffa73c13209
    BACKEND_LOG_RESPONSE_OK: 10002b15d9f835613f635f16dff3ed189a8f91ca4812030bedccd65db9f3cb973b60
